### PR TITLE
fix(#2981): keeps `astro preview` server alive

### PR DESCRIPTION
**Pull request by tony-sull**
## Changes

Fixes a bug that was preventing the `astro preview` server from staying alive

## Testing

Tested locally

## Docs

Bug fix only

### CODE REVIEW

**Comment by matthewp** [comment]
Hm, I'm not sure about this. I don't love the idea of returning a promise that never results as a way to prevent the server from closing. Look at the code for `preview` it doesn't look like the server should be closing when the function completes. Why is it doing so?

**Comment by caioferrarezi** [comment]
Hi, @tony-sull!

I was looking for a solution based on what @matthewp has said and I found this promise chaining added in the main process when the CLI is called https://github.com/withastro/astro/compare/astro%400.26.0...astro@1.0.0-beta.0#diff-77b369f46e8996fe0176373280d502a60bd929bb4c5bc97a1e94163f2591fd23R99-R101

It seems like the `.then(() => process.exit(0))` is killing the node environment when the preview's server promise resolution is executed here https://github.com/withastro/astro/blob/main/packages/astro/src/core/preview/index.ts#L109

Hope it may help!

Thanks!

**Comment by tony-sull** [comment]
> Hm, I'm not sure about this. I don't love the idea of returning a promise that never results as a way to prevent the server from closing. Look at the code for `preview` it doesn't look like the server should be closing when the function completes. Why is it doing so?

For `astro preview` the CLI was returning a promise that only tracked when the server was opened so it killed the process right away

I did find a cleaner solution here though, wrapped the server's `close` and `error` events in a promise so the CLI is actually going to track the server instance itself

**Review by natemoo-re — APPROVED** [review]
Nice solution! LGTM.

**Pull request merged**
