### PR TITLE
Remove dependency on path-to-regexp

### PR DESCRIPTION
**Pull request by uwej711**
## Changes

- This change removes the path-to-regexp dependency since only a small part of that code was used and that could be implemented quite simple without the dependency.

## Testing

The existing tests already cover the changed code so there was no need to add additional tests.

## Docs

This is a purely internal change and there will be no change for the users visible.

### CODE REVIEW

**Comment by uwej711** [comment]
Closing this since the target branch is wrong. Please see https://github.com/withastro/astro/pull/11983

**Comment by bluwy** [comment]
The `next` branch are for breaking changes and for the next major. Does this bring a breaking change? If so, maybe you can describe the breaking change in the other PR. If not, I think `main` would be better as presumably we want to fix the vulnerability exposure in stable as soon as possible.

**Comment by uwej711** [comment]
@bluwy I created a changeset of type minor and here the pipeline complained about not being able to merge so I just thought next might be the right branch ... so I will try again against main. Thanks.

**Comment by uwej711** [comment]
OK will change to patch.

**Pull request closed without merging**
