### PR TITLE
Update to Vite 6.0.0-beta.6

### PR DESCRIPTION
**Pull request by bluwy**
## Changes

Update to latest beta, which shouldn't have any issues for us.

## Testing

Existing tests should pass. Vite ecosystem-ci doesn't test e2e, so would be interesting to see the result here

## Docs

n/a

### CODE REVIEW

**Comment by bluwy** [comment]
There's an off-by-one error in the reported line by sass. Will have to check if this is a bug in Vite or not.

**Comment by bluwy** [comment]
https://github.com/vitejs/vite/pull/18522 should fix it but we can also fix on our side as it's not really a vite breaking change.

**Comment by bluwy** [comment]
I'm planning to bump to beta.6 first, and then bump to beta.8 later as it has more e2e errors that I've not been able to look at yet.

**Comment by Mravuri96** [comment]
@bluwy can we bump to `6.0.0-beta.9`, this fix https://github.com/vitejs/vite/pull/18541 which landed in `beta.8`, will unblock this use case.
```ts
import data from '@gen/data.json' assert { type: 'json' };

export const getStaticPaths = async () => {
   return data;
};
```

**Comment by bluwy** [comment]
I just checked the compat and there's a change in beta.8 that's breaking svelte and solid integrations, so we can't bump it yet. However if you're not using them, you can use `overrides` in your package.json to use the latest beta if needed.

**Comment by Mravuri96** [comment]
> I just checked the compat and there's a change in beta.8 that's breaking svelte and solid integrations, so we can't bump it yet. However if you're not using them, you can use `overrides` in your package.json to use the latest beta if needed.

I am using svelte and had to do this to fix the issue
```js
vite{
  resolve: {
    conditions: ['browser'],
  },
}
```

**Pull request merged**
