### PR TITLE
Fixed an "Uncaught ReferenceError" inside of the @astrojs/vue package

### PR DESCRIPTION
**Pull request by sammibajrami**
## Changes

I was getting an error on page transitions after upgrading all astro related packages in my project:
`Uncaught ReferenceError: app is not defined`

The `app` reference in question was in the client.js script, and it turned out that it was initiated inside of an if statement that didn't run on transitions.

I am making this pull request in the hope that it'll help.
I'm not very familiar with the Astro codebase so if my solution isn't really a solution then feel free to reject the request or to change it or to point me in the right direction to actually solve it myself :)

## Testing

Ran the code, the error was gone and no new one took it's place.

## Docs

Shouldn't affect a user’s behavior in any way.

### CODE REVIEW

**Comment by martrapp** [comment]
@johannesspohr: Could you please take a look, Johannes?

**Comment by bluwy** [comment]
Looks like the same issue is happening for svelte: https://github.com/withastro/astro/pull/12102

**Comment by johannesspohr** [comment]
Thanks for bringing this up. It looks to me like we should move attaching the event listener inside the block where `app` is initialized, as binding it once should be enough to clean everything up when the component is unmounted.
I can't try it right now unfortunately.

**Review by martrapp — CHANGES_REQUESTED** [review]
Hi @sammibajrami, the suggested solution would be to revert the file and only move the addEventlistener from line 52 up to line 47 at the end of the if-block. That would restore the logic as it was before the last fix and ensure that `app` is always defined when referenced.

**Review by martrapp — APPROVED** [review]
Looks good to me!
Thanks a lot, @sammibajrami!

**Comment by sammibajrami** [comment]
Not a problem, and thank you too for pointing me in the right direction!

**Pull request merged**
