### PR TITLE
Do not send body with HEAD and GET on node integration

### PR DESCRIPTION
**Pull request by dimitrov-adrian**
## Changes

- With latest change astro always set body on node integration Request

## Testing

With the default SSR it does not works and get error, after it works.

Error reported:

```
TypeError: Request with GET/HEAD method cannot have body.
    at new Request (node:internal/deps/undici/undici:5599:17)
    at createRequestFromNodeRequest (file:///Users/e01/Workspace/astro-ssr-demo/node_modules/astro/dist/core/app/node.js:11:16)
    at file:///Users/e01/Workspace/astro-ssr-demo/node_modules/astro/dist/core/app/node.js:40:60
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handler (file:///Users/e01/Workspace/astro-ssr-demo/node_modules/@astrojs/node/dist/server.js:14:30)
```

### CODE REVIEW

**Comment by dimitrov-adrian** [comment]
Related issue: #4104

**Comment by JulianCataldo** [comment]
I can relate the exact same issue here

**Review by natemoo-re — APPROVED** [review]
Makes sense! Appreciate the fix.

**Comment by natemoo-re** [comment]
This is a critical one so I'm going to merge even with the unrelated failure.

**Pull request merged**
