### PR TITLE
Resolve sitemap URLs in relation to full site path

### LINKED ISSUE #2422: 🐛 BUG: Sitemap URLs are wrong if site is built at subdirectory
### What version of `astro` are you using?

0.22.14

### What package manager are you using?

npm

### What operating system are you using?

macOS 12.1

### Describe the Bug

If an Astro site is configured to be served from a subdirectory in `astro.config.mjs`, the subdirectory is ignored when building URLs for the sitemap.

For example, with the following config:

```js
buildOptions: {
  site: 'https://astro.build/base-directory/',
},
```

A site with a single index page should include a record for `https://astro.build/base-directory/`, but the actual output is:

```xml
<urlset>
  <url>
    <loc>https://astro.build/</loc>
  </url>
</urlset>
```

This is because of how the URLs passed to the sitemap generator are built:

https://github.com/withastro/astro/blob/04c2e2e4cdba09ed3eecf4fce56420f4f1566656/packages/astro/src/core/build/index.ts#L149

Each `pageName` has a leading slash prepended, which means `pageName` is resolved by the URL constructor relative to the _origin_ and not the full path. I should have a PR ready shortly to fix this unless there’s something I’m missing as to why that leading slash is important (I’m investigating one failing test after removing it).

### Link to Minimal Reproducible Example

https://codesandbox.io/s/pedantic-khorana-5lj9z?file=/README.md

(Might need to open up a secondary terminal on CodeSandbox to run `yarn start` and see the build output — seems to keep running `dev` by default, which doesn’t build `sitemap.xml`.)

### PR DESCRIPTION
**Pull request by delucis**
Fixes #2422

## Changes

Removes leading slash added to path names when creating absolute URLs for use in sitemap generator.

## Testing

I added a test using the existing sitemap generation fixture, but with a site config that includes a base directory in `buildOptions.site` and tested that the generated sitemap URLs include the base directory as expected. The existing sitemap test also still passes.

## Docs

Bug fix only.

### CODE REVIEW

**Comment by delucis** [comment]
I think the test I added is failing on Windows because it re-uses/rebuilds the same fixture as is used to test the sitemap already. ([The error](https://github.com/withastro/astro/runs/4874447300?check_suite_focus=true#step:9:595) is `Error: ENOTEMPTY: directory not empty` in the fixture’s `dist` directory.)

Is there a way to clean-up and reuse the fixture correctly or should I just duplicate the fixture itself in its entirety?

**Comment by matthewp** [comment]
@delucis I would use the `rimraf` package in your test. There's a bug in Vite, it should be clearing it out, but Windows is weird (look at the source-code of rimraf to see what I mean).

**Comment by delucis** [comment]
@matthewp Thanks for the hint. After some trial and error (debugging via CI is a slow process…), I’ve added a `clean` method to the API provided by the fixture loader. Any test can now load a fixture and call `clean` to delete its dist directory. `rimraf` didn’t play nicely with the use of URLs for file paths, but it turned out that plain Node.js could handle this perfectly well.

The test now passes and this should be ready for review. (Smoke test seems to be hanging, but I’m guessing not because of what’s in the PR?)

**Comment by matthewp** [comment]
@delucis I think you need to rebase with `main` to fix the hanging test.

**Comment by delucis** [comment]
Yup! All good now 🎉

**Review by jonathantneal — APPROVED** [review]

**Pull request merged**
