### PR TITLE
test: add firefox to the list of browsers to test

### PR DESCRIPTION
**Pull request by ematipico**
## Changes

Related to https://github.com/withastro/astro/pull/10999

I tried to add the view transitions tests and dev toolbar tests for Firefox, but some scenarios fail.

cc @Princesseuh @martrapp 

## Testing

CI should pass

## Docs

N/A

### CODE REVIEW

**Review by bholmesdev — APPROVED** [review]
You're on `fire` ema

**Comment by bluwy** [comment]
Late to review this, but thanks for adding this Ema!

**Comment by martrapp** [comment]
Happy to see Firefox being added to the list!
I will be looking into view transition e2es

**Comment by martrapp** [comment]
#11093 adds view transition tests

**Pull request merged**
