### PR TITLE
Batch instead of using p-limit

### PR DESCRIPTION
**Pull request by horo-fox**
cc @jlarmstrongiv

## Changes

Potentially fix https://github.com/withastro/astro/pull/10708#issuecomment-2060010637. We use `p-limit` two other places that could probably use a similar strategy, if we want to remove a dependency.

## Testing

If possible, I would like to try installing this branch as a package to ensure it still works. I'm not familiar enough with package managers to know how to do that.

## Docs

Should just fix a potential import issue.

### CODE REVIEW

**Comment by bluwy** [comment]
I don't think we should revert it. Our build setup (Vite) already respects subpath imports, it seems like a different tool from that comment that's not supporting it. @jlarmstrongiv do you have a repro?

**Comment by jlarmstrongiv** [comment]
Here’s the reproduction https://github.com/jlarmstrongiv/astro-p-limit-error it appears the error occurs with the `sst` adapter.  

I suppose I’m in favor of reverting it because breaking `sst` builds in a patch release isn’t ideal

**Comment by bluwy** [comment]
I can't get the project to build. I get `CredentialsProviderError: Could not load credentials from any providers` which perhaps I'm missing some env vars to get this work.

I don't think we're intentionally breaking things here. The package is using subpath imports which should be supported by any tooling that also supports subpath exports. It seems like SST is using esbuild to bundle things:

- https://github.com/sst/sst/blob/0acf9c68e9731755105899e20cad1fba1b118d3c/packages/sst/src/runtime/handlers/node.ts#L150
- https://github.com/sst/sst/blob/0acf9c68e9731755105899e20cad1fba1b118d3c/packages/sst/src/constructs/SsrFunction.ts#L343

And AFAIK esbuild also supports subpath imports. So it seems like there's a bug in SST somewhere that prevents it working.

**Comment by jlarmstrongiv** [comment]
@bluwy I’ve let SST know in the Discord, I’m assuming they’ll ( @bayssmekanique ) follow up here.  Other users have started to confirm astro + sst breaking in Discord too.

> I can't get the project to build. I get CredentialsProviderError: Could not load credentials from any providers which perhaps I'm missing some env vars to get this work.

Here’s instructions on ensuring your AWS credentials are set up properly https://docs.sst.dev/advanced/iam-credentials

---

> I don't think we're intentionally breaking things here. The package is using subpath imports which should be supported by any tooling that also supports subpath exports. It seems like SST is using esbuild to bundle things:
> And AFAIK esbuild also supports subpath imports. So it seems like there's a bug in SST somewhere that prevents it working.

You’re reasoning is sound.  SST does use esbuild behind the scenes (so does Vite).  And it certainly wasn’t international.  Nonetheless, it broke all astro + sst builds in a patch update.  Hopefully, this issue will be resolved from either the sst side or astro side.

**Comment by bayssmekanique** [comment]
This does appear to be an issue that will affect more than just `sst` users. Anyone using Deno, Bun, tsx, or esbuild will face this issue according to the issue comments: https://github.com/sindresorhus/p-limit/issues/75

I was not able to reproduce

**Comment by Princesseuh** [comment]
> This does appear to be an issue that will affect more than just `sst` users. Anyone using Deno, Bun, tsx, or esbuild will face this issue according to the issue comments: [sindresorhus/p-limit#75](https://github.com/sindresorhus/p-limit/issues/75)
> 
> ~My understanding is that esbuild doesn't implement the resolution, it relies on Node's implementation, so this could be an issue of the build-time environments node version not being compatible.~ nvm, I misunderstand Evan's comment but looking at the code he does perform his own module resolution.

Looking at esbuild's issues, support for subpath imports was added multiple years ago. Are you saying that it doesn't work even in esbuild's latest version? Bun also supports subpath imports (though there's apparently bugs in it on some OS)

**Comment by bluwy** [comment]
Closing as we haven't heard of similar reports.

**Pull request closed without merging**
