### PR TITLE
Fix adding missing re-routes in de/docs and adjusting headline

### PR DESCRIPTION
**Pull request by borisv**
## Changes

- Fix! Adds missing re-routes to de/ in German docs' left side menu in config.ts
- Adjusts headline according to the left side menu in de/getting.started.md

## Testing

Proof read!   
Fixed route links checked!

## Docs

This is part of the documentation...

### CODE REVIEW

**Review by iKasch — APPROVED** [review]
🚀

**Review by borisv — COMMENTED** [review]
Added a few other re-route fixes inside of pages/de to this PR. Testing all links via Netlify preview...

**Comment by borisv** [comment]
Added re-routes in pages/de/* where applicable.
Replaced snowpackjs in github links with withastro where applicable.

I think I must stop using two forks in parallel - sort of confusing that is...

**Review by tony-sull — APPROVED** [review]
Looks good to me, thanks for cleaning up these links to point to the correct German pages!

**Comment by tony-sull** [comment]
@borisv Just thought I'd check before merging this in, are there any other docs pages you wanted to check before I merge this in?

**Comment by borisv** [comment]
Thanks for asking, for now that's all there is. I'll do a new PR for the next bunch of fresh pages.

**Comment by drwpow** [comment]
Thank you! We are currently working on a bugfix to the docs, so will hold off until that’s merged. But otherwise looks good to me and we’ll merge when the docs bug has been fixed.

**Comment by borisv** [comment]
Something did reset the config.ts containing all re-routing changes from this PR. 
I'll do a new PR with those changes again...

**Comment by drwpow** [comment]
I believe #2120 supersedes this? I’ll close this PR but please re-open or comment if I’m mistaken.

**Pull request closed without merging**
