### PR TITLE
Remove try/catch from solid component check

### LINKED ISSUE #3280: 🐛 BUG: Solid integration swallows component errors server-side
### What version of `astro` are you using?

v1.0.0-beta.22

### Are you using an SSR adapter? If so, which one?

N/A

### What package manager are you using?

pnpm 

### What operating system are you using?

Mac

### Describe the Bug

Error messages in Solid components are swallowed by server pre-rendering. This makes it difficult to debug solid components. In the example `BrokenComponent` throws a useful error message but it only "Unable to render BrokenComponent!" appears in the logs. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8cnxwy-lzkgtf?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by nonphoto**
Fixes #3280

## Changes

Remove try/catch from solid component check function. Solid components can be any function. Catching the errors in the check function prevents useful errors from being displayed in dev mode.

## Testing

The test suite seems to be failing right now for "returns 404 for invalid URLs". Aside from that I'm not sure how to best test this as I'm not familiar with how this would affect other UI frameworks like React on the same site.

## Docs

Ideally this shouldn't affect the docs.

### CODE REVIEW

**Comment by matthewp** [comment]
The reason for the try/catch is to work when using multiple JSX frameworks in the same project. If you look at the React integration it does the same thing, but tries to figure out if the error is coming from somewhere else: https://github.com/withastro/astro/blob/main/packages/integrations/react/server.js#L37-L39

Can we do something similar here instead of removing the try/catch altogether?

**Comment by nonphoto** [comment]
I'm not sure of any other way to determine if it's a Solid component. Maybe there's a way to disqualify React and Preact components though.

Do you think it would be enough to just run through the checks in the order the integrations appear in the config? That way if React appears first in the config it would always pick that first unless the React check fails. It would also help to have a directive to manually specify component framework ie `integration:solid-js`.

**Comment by matthewp** [comment]
What if we did a try/catch when running .check(). https://github.com/withastro/astro/blob/main/packages/astro/src/runtime/server/index.ts#L204-L209

Save the errors that are throw. If all checks fail then we know the error was real, rethrow the error. Make sense?

**Comment by nonphoto** [comment]
I think that would work. It's a bit odd from the perspective of the integration author though (at least for solid) because you would need to run `createComponent` just for the error side effects. I think anything that gives _some_ feedback about what went wrong is better than the current option though.

**Comment by nonphoto** [comment]
@matthewp implemented the above, let me know if that works.

**Review by matthewp — APPROVED** [review]
Looks great!

**Comment by nonphoto** [comment]
For the changeset would this apply to everything that depends on `astro`? Not familiar with how monorepos work.

**Comment by matthewp** [comment]
@nonphoto Sorry for the late reply. This only needs to apply to `astro`.

**Comment by matthewp** [comment]
Going to merge to get the fix in and then add a changeset.

**Comment by nonphoto** [comment]
Thanks!

**Pull request merged**
