### PR TITLE
Docs: add yarn workaround to node integration docs

### PR DESCRIPTION
**Pull request by Jutanium**
## Changes

This documents a workaround for the node integration [issue](https://github.com/withastro/astro/issues/4974) that people are asking about in [support threads](https://discord.com/channels/830184174198718474/1025507121481134131).

## Testing

Docs only

## Docs
cc @withastro/maintainers-docs for feedback!

### CODE REVIEW

**Comment by matthewp** [comment]
Isn't this also fixed with `shamefully-hoist=true` in the `.npmrc`? Assuming so that's probably a better suggestion.

**Comment by Jutanium** [comment]
@matthewp This issue only occurs with Yarn, which doesn't have that option, right?

**Comment by bluwy** [comment]
I can reproduce the issue with npm too. Only pnpm works as it's strictly hoisted. This is because of how Vite externalizes dependencies: e.g. if `path-to-regexp` can be resolved from the project root (possible in npm/yarn, not in pnpm), `path-to-regexp` will be externalized and not bundled into `path-to-regexp`. `pnpm` on the contrary would bundle `path-to-regexp`.

I suppose we can hardcode `path-to-regexp` as `ssr.noExternal` by default to fix it, but this is a general nodejs ESM-CJS issue if some user uses another dependency themselves like `path-to-regexp`.

**Review by bluwy — APPROVED** [review]
I suppose it's good to document this for now until we get a fix in 👍

**Review by delucis — APPROVED** [review]
LGTM, Dan! I guess you _could_ say “to the `vite.ssr.noExternal` array” or “to the `noExternal` array in the Vite SSR config”, but this is good as-is, I think.

**Review by sarah11918 — APPROVED** [review]

**Comment by matthewp** [comment]
Better than what we had, etc

**Pull request merged**
