### PR TITLE
Update to oslo 1.2.1 package and fix depricated functions

### PR DESCRIPTION
**Pull request by RaphaelBossek**
## Changes

Update to oslo 1.2.1 with rewriting depricated functions.

## Testing

Regular build of Astro.

## Docs

Internal incompatible use of depricated function from @oslojs/encoding; now oslo/encoding from oslo 1.2.1 package.

### CODE REVIEW

**Review by ematipico — CHANGES_REQUESTED** [review]
The changes of the examples seem unrelated, could you remove them?

**Comment by bluwy** [comment]
> Internal incompatible use of depricated function from @oslojs/encoding; now oslo/encoding from oslo 1.2.1 package.

Do you have source on this? It seems like the functions it exports are not deprecated to me. `oslo` also brings in some unrelated dependency that we don't likely want.

**Comment by bluwy** [comment]
Seems like that's because Node.js can only use the CJS version of `@oslojs/encoding`: https://publint.dev/@oslojs/encoding@0.4.1. Maybe it's worth seeing if they're open to using the `"exports"` field to fix this.

**Comment by RaphaelBossek** [comment]
A quick pnpm patch for 0.3.0 and 0.4.1 versions of `@oslojs/encoding` does not fix the issue:
```
diff --git a/package.json b/package.json
index 6333763408ae083c5e3a3270bb2874bc90681a23..429680a32a29510eb1f18d813d081bf929414588 100644
--- a/package.json
+++ b/package.json
@@ -6,8 +6,7 @@
   "files": [
     "/dist/"
   ],
-  "main": "dist/index.js",
-  "module": "dist/index.js",
+  "exports": "./dist/index.js",
   "types": "dist/index.d.ts",
   "keywords": [
     "auth",
```

**Comment by bluwy** [comment]
Looks like I was mistaken, it already exports ESM everywhere. There's a bug in my tool 🥲 I'm not sure how that error happens though

**Comment by RaphaelBossek** [comment]
Backported my implementation from arctic@2.0.0-next.5 to arctic@1.9.2 to avoid this issue.

**Pull request closed without merging**
