### PR TITLE
Make smoke tests more deterministic

### PR DESCRIPTION
**Pull request by FredKSchott**
## Changes

- Moves the actual download/setup/sync logic of our remote smoke tests to a nightly CI task. Instead of downloading on demand, we now download once nightly.
- Now smoke tests should pass or fail with more reliability, since all test contents will static and checked in across every PR and test run. Essentially, we're back to "local" behavior for test running.
- Uses the same "create PR" flow as our yarn.lock upgrade script.

## Testing

- Is test. I will run the nightly job manually after merging to confirm that it worked.

## Docs

- N/A

### CODE REVIEW

**Comment by natemoo-re** [comment]
I know I jokingly say this all the time, but this actually seems like a case for submodules? When people clone this repo, they'll just get an empty file unless they pass `--recurse-submodules`, which is what we'd do in CI.

**Comment by FredKSchott** [comment]
Submodules would probably fix some bugs with our current implementation, but doesn't change the main pro/cons around determinism. Likewise, false positives/negatives are possible (likely?) in the current system due to network, fs, git, etc. Basically, if I see a smoke test failure (locally or CI) and you can't reproduce on your machine, there's a huge surface area to go debug whats wrong.

**Review by natemoo-re — APPROVED** [review]
I'm still not a big fan of this code being checked into our repo, especially since some contributors have already mentioned that the monorepo is difficult to clone on a slow connection. But I won't block this PR if you think this is the best approach for the time being.

**Comment by FredKSchott** [comment]
Lets try it out for a few weeks and if we don't like it I'm happy to revert. I agree that a longer initial download time is a pain but I have faith that the confidence boost + being able to turn smoke tests back on will be well worth it

**Pull request merged**
