### PR TITLE
chore(@astrojs/vercel): migrate tests to `node:test`

### PR DESCRIPTION
**Pull request by mingjunlu**
## Changes

- Migrates tests of `@astrojs/vercel` to `node:test` ([#9873](https://github.com/withastro/astro/issues/9873))
- [edge-middleware.test.js](https://github.com/withastro/astro/blob/main/packages/integrations/vercel/test/edge-middleware.test.js) is untouched since it contains snapshot testing, which [Node.js doesn't support for now](https://github.com/nodejs/node/issues/48260)

## Testing

- `pnpm --filter @astrojs/vercel run test`

## Docs

- No docs added since this PR only deals with tests

### CODE REVIEW

**Review by ematipico — APPROVED** [review]
Can you remove `mocha` and `chai` from the dependencies and update the lock file?

**Comment by mingjunlu** [comment]
> Can you remove `mocha` and `chai` from the dependencies and update the lock file?

Sure, but [edge-middleware.test.js](https://github.com/withastro/astro/blob/main/packages/integrations/vercel/test/edge-middleware.test.js) would be left out of testing. Is that alright?

Background: [edge-middleware.test.js](https://github.com/withastro/astro/blob/main/packages/integrations/vercel/test/edge-middleware.test.js) contains snapshot testing, but [Node.js doesn't support that for now](https://github.com/nodejs/node/issues/48260)

**Comment by ematipico** [comment]
Sorry I didn't read that you didn't move all the files

**Comment by mingjunlu** [comment]
No problem! I just noticed that the two test cases using snapshot testing were already skipped.

I guess it's fine to migrate that file?

**Pull request merged**
