### PR TITLE
refactor: enforce node prefix

### PR DESCRIPTION
**Pull request by florian-lefebvre**
## Changes

- Updates fs import with prefix
- enable biome rule to catch such thing in the future
- depends on #11725

## Testing

should pass

## Docs

N/A, no changeset since internal only

### CODE REVIEW

**Review by ematipico — APPROVED** [review]

**Comment by ematipico** [comment]
@florian-lefebvre does this PR fixes https://github.com/withastro/astro/issues/11720 ?

**Comment by ematipico** [comment]
Looking at failure, I believe that even though that's the fix, the data store becomes part of the runtime where Node.js can't be used. 

I believe the fix is going to be more convoluted than expected.

**Comment by florian-lefebvre** [comment]
Leaving the PR to someone else then, I don't have enough context about the content layer

**Comment by ascorbic** [comment]
@ematipico it's unrelated. I have a fix for that here #11725

**Comment by alexanderniebuhr** [comment]
I think this is a good and important change, because this will fix Cloudflare if used with the compatibility flag, but doesn't fix the issue if the user decides not to use the compatibility flag.

**Pull request merged**
