### PR TITLE
Encode ampersands in markdown code blocks

### LINKED ISSUE #3487: 🐛 BUG: Ampersands (`&`) contained in Markdown are not HTML-encoded
### What version of `astro` are you using?

astro@1.0.0-beta.38

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

When comparing the rendered HTML output of our Astro Docs repo (built on Astro beta 17) with the HTML output of the latest betas, I discovered a difference:

Ampersands in Markdown seem to be no longer converted to encoded entities in the HTML output. An excerpt from a regular paragraph on the /en/guides/imports/ page was this before:

```html
can support compile-to-CSS languages like Sass &#x26; Less via plugins.
```

And now it's this:

```html
can support compile-to-CSS languages like Sass & Less via plugins.
```

This happens both in regular paragraphs (as just mentioned) and in `<code>` blocks, causing Markdown code like this to lead to a seemingly empty code block in the browser:

```md
Use `&nbsp;` to get a non-breaking space in HTML.
```

The old betas encoded the ampersand in the HTML output, the new ones don't.

## Comparison:
- Beta 38: https://stackblitz.com/edit/github-gx2mt3-uv4jeg?file=src/pages/index.md
- Beta 17: https://stackblitz.com/edit/github-gx2mt3-nekpaq?file=src/pages/index.md

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gx2mt3-uv4jeg?file=src/pages/index.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by tony-sull**
Closes #3487 

## Changes

Updates rehype to encode ampersands in code blocks

## Testing

Added tests for markdown `<code>` and fenced code blocks

## Docs

N/A

### CODE REVIEW

**Review by FredKSchott — APPROVED** [review]
LGTM! A shame we have to do all of these as one-offs. For a future PR, is there a more generic encoding function or html encoder npm package that we could call on this? No worries if not, just a thought.

**Review by natemoo-re — APPROVED** [review]
LGTM!

**Comment by tony-sull** [comment]
@FredKSchott I believe @hippotastic is actually working on a larger update that moves more of the work out of our custom markdown plugins - hopefully the days of one-off markdown fixes are coming to an end!

**Comment by hippotastic** [comment]
Hey, thanks for mentioning that I'm working on something in that area! 😄 Just to clarify a bit - I'm working on two main things right now:
1. A large amount of new test cases which ensure that our Markdown-to-HTML pipeline works as it should, and doesn't crash or produce invalid output. I didn't trust our test coverage so far, so I always ran a build of our Astro Docs site and performed a side-by-side file comparison of the build output between Astro versions to find any issues introduced by Markdown-related code changes. This is how I also found this bug that Tony just fixed. This is of course not something we can expect other contributors to do, and our tests should cover that.
2. A preprocessor that is able to transform documents that are valid Markdown as per the CommonMark/GFM spec to valid MDX documents that (A) do not crash the parser in trivial cases and (B) produce HTML output that comes as close as possible to the Markdown author's recognizable intention. This is important to make migration to Astro as smooth as possible - if you look at a document and think that it looks valid, it should just work and not fail the build due to a seemingly unclosed nested paragraph.

**Pull request merged**
