### PR TITLE
Update remark/rehype dependencies

### PR DESCRIPTION
**Pull request by mashehu**
The remark/rehype updates change the minimum required node version to 18. Not sure if that is then also needed for this package. 

This resolves the following error for me:
```
TypeError: Failed to parse Markdown file "/Users/matho180/nf-core.astro/src/content/about/about.md":
Cannot read properties of undefined (reading 'inTable')
    at Object.exitCodeText (file:///Users/matho180/nf-core.astro/node_modules/mdast-util-gfm-table/lib/index.js:123:17)
    at compile (file:///Users/matho180/nf-core.astro/node_modules/mdast-util-from-markdown/lib/index.js:352:40)
    at fromMarkdown (file:///Users/matho180/nf-core.astro/node_modules/mdast-util-from-markdown/lib/index.js:187:29)
    at parser (file:///Users/matho180/nf-core.astro/node_modules/@astrojs/markdown-remark/node_modules/remark-parse/lib/index.js:18:12)
    at Function.parse (file:///Users/matho180/nf-core.astro/node_modules/@astrojs/markdown-remark/node_modules/unified/lib/index.js:273:12)
    at executor (file:///Users/matho180/nf-core.astro/node_modules/@astrojs/markdown-remark/node_modules/unified/lib/index.js:393:31)
    at new Promise (<anonymous>)
    at Function.process (file:///Users/matho180/nf-core.astro/node_modules/@astrojs/markdown-remark/node_modules/unified/lib/index.js:380:14)
    at Object.render (file:///Users/matho180/nf-core.astro/node_modules/@astrojs/markdown-remark/dist/index.js:89:35)
    at Object.load (file:///Users/matho180/nf-core.astro/node_modules/astro/dist/vite-plugin-markdown/index.js:62:46)
```

## Changes

- What does this change?
- Be short and concise. Bullet points can help!
- Before/after screenshots can help as well.
- Don't forget a changeset! `pnpm exec changeset`

## Testing

No new tests needed. Old tests should catch changes introduced with this PR.

## Docs

No new docs needed. It's just an update of the dependencies.

### CODE REVIEW

**Comment by mashehu** [comment]
Needs https://github.com/silvenon/remark-smartypants/pull/78 to be merged first, to fix type error.

**Comment by bluwy** [comment]
Aren't these breaking changes? It wouldn't be safe to bump the majors until we release Astro 4. We do have backlogs to upgrade our remark/rehype/mdx deps etc when we start to work on Astro 4 though.

**Comment by mashehu** [comment]
Yes, it needs an update of the types in remark-smartypants (PR with changes is here https://github.com/silvenon/remark-smartypants/pull/78). Should I set this PR as draft until that is fixed? (sorry, I am a first time contributor, so not 100% sure how you handle these things)

**Comment by ematipico** [comment]
Yeah it's best to have it as a draft for now. Once it's ready to be reviewed, you can mark it as ready for review. Thank you for understanding!

**Comment by bluwy** [comment]
> I don't think that these are breaking changes. The only change with the new dependencies is the minimum node version, which astro is already ahead of. Or do you mean because of the underlying changes of remark/rehype plugins?

We allow users to configure remark/rehype plugins under `markdown.remarkPlugins` and `markdown.rehypePlugins`, so they will be affected. Last I checked, the new majors introduce breaking APIs, e.g.
- https://github.com/remarkjs/remark/releases/tag/15.0.0
- https://github.com/vfile/vfile-message/releases/tag/4.0.0 (via unified -> vfile -> vfile-message)

**Comment by bluwy** [comment]
We've upgraded the dependencies in #9138 (for Astro 4). Closing this for now, thanks for the initial PR!

**Pull request closed without merging**
