### PR TITLE
fix(vercel): Fix srcset generation not working on Vercel

### PR DESCRIPTION
**Pull request by Princesseuh**
## Changes

We were wrongfully not including the hooks for srcset generation in the Vercel service. This fixes that. I'll note that it's still a little bit wonky on the user side, because they need to make sure that the dimensions they're outputting are part of their Vercel config, but that's normal for Vercel.

Fixes https://github.com/withastro/astro/issues/10623

## Testing

Tested manually by deploying to Vercel.

## Docs

N/A

### CODE REVIEW

**Comment by Princesseuh** [comment]
!preview vercel-src

**Review by ematipico — APPROVED** [review]

**Comment by pijusz** [comment]
I've tried with newest updates, 
```javascript
"@astrojs/vercel": "^7.5.3",
"astro": "^4.6.1",
```
doesn't seem to work still, rollbacked to 
```
"@astrojs/vercel": "~7.3.6"
```
that one works.

**Comment by Princesseuh** [comment]
> I've tried with newest updates, 
> ```javascript
> "@astrojs/vercel": "^7.5.3",
> "astro": "^4.6.1",
> ```
> doesn't seem to work still, rollbacked to 
> ```
> "@astrojs/vercel": "~7.3.6"
> ```
> that one works.

7.3.6 did not have the code at all to handle srcset. Your issue might be unrelated to this

**Comment by pijusz** [comment]
You are right, it was not even using densities. So it seems like srcset doesn't work for me for Image Components.

**Comment by pijusz** [comment]
My current Vercel Config:
```javascript
  adapter: vercel({
    edgeMiddleware: false,
    functionPerRoute: false,
    webAnalytics: {
      enabled: true,
    },
    speedInsights: {
      enabled: true,
    },
    imageService: true,
    imagesConfig: {
      sizes: [80, 320, 640, 768, 1024, 1280, 1920, 2580],
      formats: ["image/avif", "image/webp"],
      minimumCacheTTL: 60,
      domains: ["cdn.sanity.io"],
    },
  }),
```

**Comment by Princesseuh** [comment]
I would suggest creating a new issue with a reproduction.

**Comment by pijusz** [comment]
Needed to add more "sizes", since each density is each new size.

**Pull request merged**
