### PR TITLE
Resolves #4825

### LINKED ISSUE #4825: No assets folder when outDir outside cwd
### What version of `astro` are you using?

1.2.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I have a pnpm monorepo containing an astro app in one folder and a create-react-app in another.
My goal is to build the create-react-app, then build the astro app into a subfolder of the built create-react-app.

For the most part, this works fine. The only problem is that the `public` folder isn't copied into the `outDir` destination, so images and css 404 on the deployed site.

### Link to Minimal Reproducible Example

https://github.com/rob-gordon/nested-astro-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fixes #4825 

## Changes

- What does this change?
- Be short and concise. Bullet points can help!
- Before/after screenshots can help as well.
- Don't forget a changeset! `pnpm exec changeset`

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks! This looks great. We have another PR that's fixing the lint issues, then this can be updated.

**Comment by rishi-raj-jain** [comment]
@matthewp merged the lint fixes

**Comment by matthewp** [comment]
Thanks! Can you add a changeset? `pnpm changeset` and make it be a `patch`.

**Review by matthewp — CHANGES_REQUESTED** [review]
Just needs a changeset, `pnpm changeset`

**Pull request merged**
