### PR TITLE
chore: Migrate `ssr-*.test.js` to `node:test`

### PR DESCRIPTION
**Pull request by xMohamd**
## Changes

- See #9873
- Migrates `packages/astro/test/ssr-*.test.js`

## Testing

All tests pass.

## Docs

N/A

### CODE REVIEW

**Comment by ktym4a** [comment]
https://github.com/withastro/astro/issues/9873#issue-2107543646

> Node.js test runner doesn't handler deep nested `describe,` so it's possible your test could hang and timeout. If that happens, lift the `describe` function.

maybe, this one?

**Comment by xMohamd** [comment]
> Seems like there's a real test failure, not sure why.

according to actions  the error in `ssr-error-pages.nodetest.js`, I tried to figure out what an error was, but I couldn't
All tests passed in my machine
```
 # tests 9
 # suites 6
 # pass 9
 # fail 0
 # cancelled 0
 # skipped 0
 # todo 0
 # duration_ms 29035.554382
```

**Comment by xMohamd** [comment]
> [#9873 (comment)](https://github.com/withastro/astro/issues/9873#issue-2107543646)
> 
> > Node.js test runner doesn't handler deep nested `describe,` so it's possible your test could hang and timeout. If that happens, lift the `describe` function.
> 
> maybe, this one?

Maybe I'll try to revert the function to the old version using chai. If there is still an error, I'll revert the whole file

**Comment by xMohamd** [comment]
IDK, what's happen here, but according to actions the new error in `ssr-split-manifest.nodetest.js`.
Same as previous error everything run smoothly in my machine and all tests passed
```
starting /workspaces/astro/packages/astro/test/ssr-split-manifest.nodetest.js
TAP version 13
# Subtest: astro:ssr-manifest, split
    # Subtest: should be able to render a specific entry point
    ok 1 - should be able to render a specific entry point
      ---
      duration_ms: 44.262958
      ...
    # Subtest: should give access to entry points that exists on file system
    ok 2 - should give access to entry points that exists on file system
      ---
      duration_ms: 0.782257
      ...
    # Subtest: should correctly emit the the pre render page
    ok 3 - should correctly emit the the pre render page
      ---
      duration_ms: 0.403291
      ...
    # Subtest: should emit an entry point to request the pre-rendered page
    ok 4 - should emit an entry point to request the pre-rendered page
      ---
      duration_ms: 41.484234
      ...
    # Subtest: when function per route is enabled
        # Subtest: should correctly build, and not create a "uses" entry point
        ok 1 - should correctly build, and not create a "uses" entry point
          ---
          duration_ms: 20.26849
          ...
        1..1
    ok 5 - when function per route is enabled
      ---
      duration_ms: 4348.331221
      type: 'suite'
      ...
    1..5
ok 1 - astro:ssr-manifest, split
  ---
  duration_ms: 11989.247563
  type: 'suite'
  ...
1..1
# tests 5
# suites 2
# pass 5
# fail 0
# cancelled 0
# skipped 0
# todo 0
# duration_ms 16853.496375
```

**Comment by ematipico** [comment]
@xMohamd 

If you see this kind of logging 

```
TAP version 13
# Subtest: astro:ssr-manifest, split
```

It means that **mocha** is running a `*.nodetest.js` file, which should not happen

**Pull request merged**
