### PR TITLE
Replace `send` dependency with `sirv` 

### PR DESCRIPTION
**Pull request by boehs**
## Changes

- See title
- This is because sirv is lighter weight and probably faster

## Testing

- No test changes

## Docs

- None, internal only

### CODE REVIEW

**Comment by boehs** [comment]
Yes I know what I'm doing, this pull request has been intentionally marked as a draft.

**Comment by boehs** [comment]
The failures are multiplying! Still same issue though :/

**Comment by boehs** [comment]
Quick update: I'm suspicious it's windows being windows and not actually my fault. Test randomly started passing, nate is rerunning to be sure

**Comment by boehs** [comment]
Screenshot from 2022-02-19 18-14-33
wtf

**Comment by natemoo-re** [comment]
Lol I'm sorry we've left you struggling with this @boehs! #2709 should fix it (I hope)

**Pull request closed without merging**
