### PR TITLE
Don’t use Buffer.byteLength() as Deno can’t use it

### LINKED ISSUE #4323: Edge runtime error: Buffer is not defined
### What version of `astro` are you using?

1.0.5

### Are you using an SSR adapter? If so, which one?

Deno

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When deploying to Deno Deploy or running locally with Deno, I receive this error:
```
Server running on port 8085
01:43:51 pm [ssr] ReferenceError: Buffer is not defined
    at renderPage (file:///Users/pgwsmith/Royal%20Icing/regenerated-astro/dist/server/entry.mjs:5767:28)
    at async render (file:///Users/pgwsmith/Royal%20Icing/regenerated-astro/dist/server/entry.mjs:6560:10)
    at async App.renderPage_fn (file:///Users/pgwsmith/Royal%20Icing/regenerated-astro/dist/server/entry.mjs:7499:22)
    at async App.render (file:///Users/pgwsmith/Royal%20Icing/regenerated-astro/dist/server/entry.mjs:7451:22)
    at async Server.handler (file:///Users/pgwsmith/Royal%20Icing/regenerated-astro/dist/server/entry.mjs:7580:14)
    at async Server.#respond (https://deno.land/std@0.132.0/http/server.ts:298:18)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-tdn4cu?file=package.json

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by BurntCaramel**
## Changes

Closes #4323 

- What does this change?
- Be short and concise. Bullet points can help!
- Before/after screenshots can help as well.
- Don't forget a changeset! `pnpm exec changeset`

### CODE REVIEW

**Comment by matthewp** [comment]
PR Looks great! Can a test be added? I think maybe this happens when using MDX, is that right? There are tests in packages/integrations/deno/test/ to use as a starting point.

**Comment by BurntCaramel** [comment]
@matthewp I’ve added test for .md and .mdx files with Deno. I brought back `Buffer.byteLength()` and it fails, and passes with my fix.

**Comment by QuiiBz** [comment]
Maybe the changeset should be renamed to talk about "all edge runtimes" instead of only Deno? `Buffer` isn't a Web API, so none of the edge runtimes support it.

**Comment by matthewp** [comment]
This looks fantastic! Just going to rerun CI and hopefully we can get this out in the next release. Thanks so much for adding the test!

**Comment by matthewp** [comment]
When https://github.com/withastro/astro/pull/4347 is merged we can update this PR.

**Pull request merged**
