### PR TITLE
fix: updates <Picture /> to pass HTML attributes down to the <img /> element

### LINKED ISSUE #3909: 🐛 BUG: `<Picture />` component passes props as attributes to the underlying `picture` element
### What version of `astro` are you using?

1.0.0-beta.65

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When passing props such as `class` or `alt` to the `<Picture />` component, they are added as attributes to the underlying `picture` element. It would probably be better if they ended up being added to the child `img` element.

Issue with the current behaviour that I ran into (see repro):

- Lighthouse lists a missing `alt` attribute. It needs to be added to the `img` element.
- CSS property `object-fit` does nothing on the `picture` element, it works when added to `img`.

<br>

Other image components make it possible to add attributes to the `img` element via a separate prop.

```html
<!-- Astro Imagetools -->
<Picture attributes={{ class: "my-class" }} />

<!-- Nuxt Image -->
<nuxt-picture :imgAttrs="{ class: 'my-class' }" />
```

<br>

But I don’t think that this is really necessary, and we should just pass all props to the `img` instead. In my experience I have yet come across a use case where I needed to add attributes to the `picture` element. If a container is required for styling purposes you can always wrap it in a `div` and add your styles there. If anything I think we should rather do it the other way around and support passing attributes to the `picture` element via a dedicated `pictureAttrs` prop.

All examples on MDN or in HTML specs that I came across use `picture` attribute-less, as a plain container to wrap the `img` and its additional `source`s.

They have some notes to prevent usage mistakes:

> The picture element itself does not display anything; it **merely provides a context** for its contained img element that enables it to choose from multiple URLs
— *https://html.spec.whatwg.org/multipage/embedded-content.html#the-picture-element*

> Use these properties on the child img element, **not** the picture element
— *https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture#usage_notes*

### Link to Minimal Reproducible Example

https://codesandbox.io/s/nifty-wiles-cn6p8w?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by emmanuelchucks**
`class` for direct img styling, `width` & `height` to prevent layout shift, etc need to be passed to the underlying img tag to work.

Closes #3909

## Changes

- Passes attributes on the Picture component to underlying img
- For example, styling with class is reflected on image
- Setting width and height to prevent layout shift also now works

## Testing

This change only corrects a slight oversight that doesn't need much testing.

## Docs

 /cc @withastro/maintainers-docs for feedback! 

This is the expected behavior for most users, just like next/image
https://nextjs.org/docs/api-reference/next/image#other-props

### CODE REVIEW

**Comment by panwauu** [comment]
The width and height attributes were removed in #4797

Related discussion: 
#3909 (Mentioned by you)
#4985 (Problem with passing styles to image and picture)

**Comment by panwauu** [comment]
1. How would you handle changing sizes? 

So for example on a smaller screen you load the 500x300 version instead of 1000x600 would you update the properties? I guess with css `width: 100%; height: fit-content;` you could still work.

2. I think it could be confusing to pass on properties like class to the img

I would assume that class on Picture applies the class to the pictue tag as usual. Maybe we could have a different asstribute like `imgClass` to pass a class to the img tag but this would result in a problem with the css scoping.

Overall, I think that a change is necessary to the <Picture /> component, but we need to think about how to do it.

**Comment by emmanuelchucks** [comment]
### For the first issue raised:

When `{...attrs}` is passed to `` tag, 
```astro
<Picture
  src="https://images.unsplash.com/photo-1620189507187-1ecc7e2e9cff?ixlib=rb-1.2.1&dl=austin-wilcox-z_U6bPp_Rjg-unsplash.jpg&q=80&fm=jpg&crop=entropy&cs=tinysrgb"
  alt="Emmanuel and his wife in native Ghanaian attire"
  widths={[200, 400, 600, 800, 1000, 1200, 1600]}
  sizes="100vw"
  width={3448}
  height={5168}
  aspectRatio={3448 / 5168}
/>
```
generates the following html

```html
<picture width="3448" height="5168" class="astro-DDSVHVWK">
  <source
    type="image/avif"
    srcset="
      /_image?f=avif&w=200&h=300&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb    200w,
      /_image?f=avif&w=400&h=600&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb    400w,
      /_image?f=avif&w=600&h=899&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb    600w,
      /_image?f=avif&w=800&h=1199&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb   800w,
      /_image?f=avif&w=1000&h=1499&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb 1000w,
      /_image?f=avif&w=1200&h=1799&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb 1200w,
      /_image?f=avif&w=1600&h=2398&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb 1600w
    "
    class="astro-DDSVHVWK"
    sizes="100vw"
  />
  <source
    type="image/webp"
    srcset="
      /_image?f=webp&w=200&h=300&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb    200w,
      /_image?f=webp&w=400&h=600&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb    400w,
      /_image?f=webp&w=600&h=899&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb    600w,
      /_image?f=webp&w=800&h=1199&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb   800w,
      /_image?f=webp&w=1000&h=1499&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb 1000w,
      /_image?f=webp&w=1200&h=1799&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb 1200w,
      /_image?f=webp&w=1600&h=2398&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb 1600w
    "
    class="astro-DDSVHVWK"
    sizes="100vw"
  />
  <img
    src="/_image?f=webp&w=1600&h=2398&ar=0.6671826625386997&href=https%3A%2F%2Fimages.unsplash.com%2Fphoto-1620189507187-1ecc7e2e9cff%3Fixlib%3Drb-1.2.1%26dl%3Daustin-wilcox-z_U6bPp_Rjg-unsplash.jpg%26q%3D80%26fm%3Djpg%26crop%3Dentropy%26cs%3Dtinysrgb"
    class="astro-DDSVHVWK"
    loading="lazy"
    decoding="async"
    alt="Emmanuel and his wife in native Ghanaian attire"
    width="3448"
    height="5168"
  />
</picture>
```
It loads the right size at each breakpoint and still prevents layout shift. Is there something I'm missing?

### Second issue raised: 

I can see how that would be confusing especially to beginners. Maybe we can make it clear in the docs? The `picture` was never really meant to be styled directly anyway. Considering that `alt`, `loading`, `decoding`, `object-fit`, `object-position`, etc only work when passed to ``. I believe this is the more consistent behavior.

**Comment by paularmstrong** [comment]
I just ran into this and was about to file an issue. I would just like to second @emmanuelchucks responses that this PR impelements what I expect to happen when passing attrs to the `Picture` component: they should get applied to the ``, not the `<picture>` element.

**Comment by carlcs** [comment]
@emmanuelchucks  Author of the issue you’re addressing here, so thanks for creating the PR. As explained in the issue I think it’s the right choice to add the attributes to the `` element.

But why are you still adding them to the `<picture>` element as well, or was that just an oversight?

**Comment by emmanuelchucks** [comment]
@carlcs It seems to break something in the tests. That was my initial hunch.

**Comment by tony-sull** [comment]
Thanks for getting this PR moving, @emmanuelchucks!  I've been busy on other projects the last couple weeks and haven't had much time to work on images, but I know the big discussions right now are related to styling pictures and the width/height attributes

I think the tests are selecting picture elements by ID right now.  I'm also +1 on only spreading the attributes onto the `img` tag, we'd just need to find a different way to select the picture in tests (maybe `getById().parentElement`?)

**Comment by tony-sull** [comment]
Pushed up a change that only includes attributes on the `` + test fixes to update how the test elements are selected

I like this change and think it takes care of both current pain points (styling the picture & layout shift), going to leave this open for a bit to get more feedback in case anyone has concerns with attributes no longer going on `<picture>`

**Comment by matthewp** [comment]
lgtm

**Pull request merged**
