### PR TITLE
remove change in type of original Options from remark-rehype

### PR DESCRIPTION
**Pull request by pedro199288**
## Changes

- What does this change?
This PR removes a change that was introduced in the type of original Options from `remark-rehype` package. This was done in this PR https://github.com/withastro/astro/pull/4138  in `packages/markdown/remark/src/types.ts`.
The reason for this PR is that when passing a valid configuration for remark-rehype (that actually works correctly), typescript is returning an error.

**Before the PR change:**
image

The above error is:
```
Type '{ heading: (state: Parameters<Handler>[0], node: Parameters<Handler>[1], parent: Parameters<Handler>[2]) => { type: string; tagName: string; properties: { someProp: string; }; children: never[]; }; }' is not assignable to type '(state: State, parent: MdastNodes) => ElementContent[]'.
  Object literal may only specify known properties, and 'heading' does not exist in type '(state: State, parent: MdastNodes) => ElementContent[]'.
```

**After the PR change:**
image

No error appears

Maybe I missed something from the original PR but as it is is giving a typescript error with a config that actually works.

## Testing

No test was updated because this is just related to typescript

## Docs

/cc @withastro/maintainers-docs for feedback!

Haven't add docs but I can if necessary

### CODE REVIEW

**Comment by pedro199288** [comment]
I don't know why that error appear but it continues appearing even if I left the code as it was before 😕

**Comment by bluwy** [comment]
The change makes sense to me, but I'm stumped with the TypeScript error too. Looks like it's a bug there: https://github.com/microsoft/TypeScript/issues/42873

If I do:

```ts
export type RemarkRehype = Omit<RemarkRehypeOptions, ''>
```

instead, which is kinda silly, it works. Maybe you can try this and merge up main? I can't seem to merge main locally, there's some sort of history mismatch.

**Comment by matthewp** [comment]
@pedro199288 do you plan to still work on this?

**Comment by pedro199288** [comment]
@bluwy thanks for the support. What you suggested looks silly, but the fact that it doesn't work without that, also looks silly to me. So I will give a try, thanks! :)

**Comment by pedro199288** [comment]
> @pedro199288 do you plan to still work on this?

Yeah I will give it a third and last try this week or the next one. If don't manage to fix it I'll let you know

**Comment by pedro199288** [comment]
I've tried what @bluwy suggested but it didn't work just with that. I've changed two files in my last commit. Curiously, only doing one of these changes didn't fix the issue with the build step but adding the two changes did so (I don't know why). 

You can see that I set `preserveSymlinks: true` but probably there is a reason why this was with its default to `false`? That "solution" was one of the suggestions in the typescript bug previously mentioned https://github.com/microsoft/TypeScript/issues/42873#issuecomment-1381702742 but I'm not sure if it is a valid solution for this project

**Comment by matthewp** [comment]
@pedro199288 all tests are passing now, are you saying this isn't working? Or just that you're unsure about the option you added?

**Comment by pedro199288** [comment]
@matthewp yeah it works fine for me also. It's just that I'm not sure if the change in tsconfig might be a problem for whatever reason that I'm not aware of. Other than that it looks good to me :)

**Comment by natemoo-re** [comment]
Hey @pedro199288, sorry for the delay on this! This change _seems_ good to me, but I agree that the `"preserveSymlinks": true` and `Omit` changes are a bit concerning.

Happy to try to resolve these if you're still interesting in getting this change in.

**Comment by pedro199288** [comment]
Hey @natemoo-re ! sorry for the late response. But yeah sure, it'd be nice if you can help with this

**Comment by ematipico** [comment]
@pedro199288 I don't think the team has the bandwidth to help you with this PR. It's OK if you aren't interested anymore to this PR

**Comment by natemoo-re** [comment]
We're planning to fix this in https://github.com/withastro/astro/pull/9147 and release in Astro 4.0.

**Comment by bluwy** [comment]
Closing as https://github.com/withastro/astro/pull/9147 is merged

**Pull request closed without merging**
