### PR TITLE
Adding support for toml data entry

### PR DESCRIPTION
**Pull request by q1b**
## Changes

- This will add support for `.toml` extension 
- using [js-toml](https://github.com/sunnyadn/js-toml) package

## Testing

I checked the repository, yet unable to see existing tests for JSON, YAML and TOML data entry points,
If so, there is need for adding tests for these data entry points let me know, I am happy to contribute

## Docs

Adding Support for .toml file in src/content folder with existing data formats json, yaml

### CODE REVIEW

**Comment by jacobdalamb** [comment]
What is this for? Sorry if it's obvious/dumb question.

**Comment by false-fox** [comment]
+ support

**Review by ematipico — CHANGES_REQUESTED** [review]
Some things you need to address:
- change the changeset, and make it a `minor`
- expand the changeset, and explain the new feature with an example. We want to explain things to users 
- open a PR to update the documentation 
- add an example in `examples/` folder

**Comment by q1b** [comment]
yes, let me do it tonight

**Pull request closed without merging**
