### PR TITLE
chore: only-allow pnpm

### PR DESCRIPTION
**Pull request by shengxinjing**
## Changes
only pnpm is allowed to manage deps

### CODE REVIEW

**Comment by shengxinjing** [comment]
thanks for reply, only-allow the recommended practice of [pnpm](https://pnpm.io/only-allow-pnpm) and I think it's worth it compared to the benefits

**Comment by bluwy** [comment]
We also have this script in Vite and I didn't noticed any slowdowns. Though I'm also not sure if this is really needed, the repo install wouldn't work without pnpm. Maybe it's still useful for new contributors though.

**Comment by natemoo-re** [comment]
If this is something the `vite` repo also does, I'm cool with it! Not strictly necessary but might help a few new contributors.

**Comment by Princesseuh** [comment]
I agree that it can be useful for new contributors. Seeing that Vite uses it and pnpm recommends it makes me confident enough in this change

**Comment by tony-sull** [comment]
Interesting to note that pnpm recommends this script in [their docs](https://pnpm.io/only-allow-pnpm), I'm on board with adding this as well

> If you use npm v7, use npx -y instead.

Not sure if this note matters for us, we support back to node `14.18.0 || >=16.12.0`, should we use `npx -y` here to support older versions of npm?

**Review by natemoo-re — APPROVED** [review]

**Comment by matthewp** [comment]
Looks like the ayes have it, merging.

**Pull request merged**
