### PR TITLE
Fix arabic docs

### PR DESCRIPTION
**Pull request by X7md**
## Changes
Try to fix arabic docs by remove unnecessary `<Code/>`

## Testing
Never Tested

### CODE REVIEW

**Comment by X7md** [comment]
> ✔️ Deploy Preview for _astro-docs-2_ ready!
> 
> 🔨 Explore the source changes: [885ae24](https://github.com/withastro/astro/commit/885ae2404d2559b35303593f3ccd18e51e9b7359)
> 
> 🔍 Inspect the deploy log: https://app.netlify.com/sites/astro-docs-2/deploys/61e52b5ed0551000076d7d1a
> 
> 😎 Browse the preview: https://deploy-preview-2408--astro-docs-2.netlify.app

Screenshot_20220117-114422_Chrome


Looking good now.

**Review by jonathantneal — APPROVED** [review]
Great catch, @X7md. I wonder how that got in there? 🤔

**Comment by X7md** [comment]
> Great catch, @X7md. I wonder how that got in there? 🤔

Not sure, but I noticed that when snowpack rename to withastro.

I was confused why RTL Layout broken, and I noticed none closed `<Code>` tag.

**Comment by X7md** [comment]
> > Great catch, @X7md. I wonder how that got in there? 🤔
> 
> Not sure, but I noticed that when snowpack rename to withastro.
> 
> I was confused why RTL Layout broken, and I noticed none closed `<Code>` tag.

After review my previous commit to Arabic Documentation... That was my bad 😅.

**Pull request merged**
