### PR TITLE
Improve test infrastructure for integrations/deno

### PR DESCRIPTION
**Pull request by deeprobin**
## Changes

With this pull request, I am migrating the current tests of the Deno integration from JavaScript to TypeScript.
In addition, optimizations were made by e.g. unnecessary awaits.

## Testing

*✅ Tests passing*

## Docs

Internal change, no api change -> no docs

### CODE REVIEW

**Review by natemoo-re — COMMENTED** [review]
Looks great! I don't think the `changeset` is necessary since this is an internal change only?

**Comment by deeprobin** [comment]
@natemoo-re I thought so too. I assumed it is necessary to use one in the PR template because of the information.

**Comment by deeprobin** [comment]
Changeset removed

**Comment by matthewp** [comment]
Looks like this is causing TS issues. I think that's the reason why I originally did not use TS. Feel free to fix, however.

**Comment by deeprobin** [comment]
> Looks like this is causing TS issues. 
> ```
> @astrojs/deno:test: error: TS2694 [ERROR]: Namespace 'Deno' has no exported member 'PermissionOptions'.
> @astrojs/deno:test: export const defaultTestPermissions: Deno.PermissionOptions = {
> @astrojs/deno:test:                                           ~~~~~~~~~~~~~~~~~
> ```

I could see us solving this problem by upgrading the Deno version in the GitHub workflow.

https://github.com/withastro/astro/blob/f38e5560851759323854b70c7a5277ba9bf05710/.github/workflows/ci.yml#L133-L136

```diff
      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
-          deno-version: v1.19.3
+          deno-version: v1.26.1
```

**Comment by matthewp** [comment]
Perfect, thank you!

**Pull request merged**
