### PR TITLE
Chore: remove memory test from CI

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes

Remove our memory smoke test from CI **only** (test still present and manually runnable)

### Why?
- after speaking with @natemoo-re, it sounds like this memory test addressed out-of-date concerns for the compiler
- this test causes issues with Vite 3, which relies on resolving the `astro` package to force-optimize dependencies. Since this test imports and calls the `dev` command directly (rather than using `execa`), Vite fails to resolve `astro` as an installed dependency. We can refactor this test to use `execa` instead if we feel this test is necessary!

## Testing

Remove `mk.js` + command call from the CI

## Docs

N/A

### CODE REVIEW

**Comment by FredKSchott** [comment]
If it’s not bothering anyone, can we leave the script in the repo? I remember this randomly being useful a couple of times when I was tracking down perf issues.

**Comment by bholmesdev** [comment]
@FredKSchott This test _is_ breaking Vite 3 (see PR comments) but maybe we can refactor to use `execa` instead? I'm not sure if that breaks the spirit of these tests

**Comment by FredKSchott** [comment]
It’s not just a test! You can run the script yourself and it starts in a “watch” mode.

To be super clear, +1000 on removing from CI. But would love to keep the script for personal/maintainer use

**Comment by bholmesdev** [comment]
@FredKSchott Ah gotcha! Removing from the CI would be perfect, yes 👍

**Comment by bholmesdev** [comment]
Update: looks like manually running _outside_ the CI also breaks with Vite 3... experimenting with a refactor to use `execa` instead

**Pull request merged**
