### PR TITLE
fix(sitemap): add missing `xslURL` property to `SitemapOptions` type

### LINKED ISSUE #12153: [sitemap] `xslURL` option not declared in `SitemapOptions` type
### Astro Info

```block
﻿﻿Astro                    v4.15.12
Node                     v20.15.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Trying to define `xslURL` in the options for `@astrojs/sitemap` (see #11485), but `astro check` fails because "`Object literal may only specify known properties, and 'xslURL' does not exist`" in the `SitemapOptions` type.

### What's the expected result?

Should be able to define `xslURL` and run `astro check` without issue.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-uxjrgn?file=astro.config.ts&view=editor

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by mingjunlu**
## Changes

- Adds missing `xslURL` property to `SitemapOptions` type
- Closes #12153

## Testing

- Manually tested with the [reproduction repo](https://stackblitz.com/edit/github-uxjrgn?file=astro.config.ts&view=editor)

## Docs

- N/A

### CODE REVIEW

**Review by bluwy — APPROVED** [review]
It also seems like we're missing `canonicalURL` here. Maybe we can add it together. And `canonicalURL` also doesn't seem documented in the docs, which we probably also should 🥲 

I'm also fine doing those later if preffered so approving the PR.

**Review by ematipico — APPROVED** [review]

**Comment by mingjunlu** [comment]
> It also seems like we're missing `canonicalURL` here. Maybe we can add it together. And `canonicalURL` also doesn't seem documented in the docs, which we probably also should 🥲
> 
> I'm also fine doing those later if preffered so approving the PR.

@bluwy Sure! Let me turn this PR into a draft for now. I'll add more commits later on.

**Comment by mingjunlu** [comment]
I found this PR: [#3677 Integration Docs Next Steps](https://github.com/withastro/astro/pull/3677)

It seems that the `canonicalURL` option was removed intentionally. Does anyone remember the context?

**Comment by bluwy** [comment]
Oh interesting. Maybe @bholmesdev knows about this one. Anyways seems like it's another can of worms, and I'm fine with merging this PR for now 😅

**Pull request merged**
