### PR TITLE
fix(NodeApp): fix responses with null bodies never completing

### LINKED ISSUE #9925: Node.js SSR redirect timeout
### Astro Info

```block
Astro                    v4.3.0
Node                     v20.11.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When returning an HTTP 30X (for example via an `Astro.redirect` in a `.astro` component), the HTTP response is not flushed and therefore not completed, resulting in a timeout while waiting for it.

This behavior was introduced by 2f6d1faa6f2d6de2d4ccd2a48adf5adadc82e593 in #9908.

### What's the expected result?

The HTTP response should be flushed immediately since (in most cases) there is no HTTP body.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-y5eicp?file=README.md

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by lilnasy**
## Changes
- Fixes #9925

## Testing
- Added a test case for redirects, thanks @friedemannsommer.
- Adjusted a test introduced in #9908 to address flakiness.
- Cherry-picked #9930 to unbreak remaining tests.

## Docs
Does not affect usage.

### CODE REVIEW

**Comment by lilnasy** [comment]
Do you mean for the tests?

**Comment by friedemannsommer** [comment]
> Do you mean for the tests?

@lilnasy Yes correct, I mean the test implementation.

**Comment by lilnasy** [comment]
The test looks great to me, I want to add that. Although adding a new fixture also means adding its build-time to the CI. If you could make it use an existing fixture, I will add it.

**Comment by friedemannsommer** [comment]
> The test looks great to me, I want to add that. Although adding a new fixture also means adding its build-time to the CI. If you could make it use an existing fixture, I will add it.

@lilnasy The only other fixture with the "SSR" prefix that has "@astrojs/node" in it's dependencies is "ssr-api-route". Should I migrate the tests into this fixture then?

**Comment by lilnasy** [comment]
Could you use the one used in the current test?

**Comment by friedemannsommer** [comment]
> Could you use the one used in the current test?

@lilnasy Sure i'll use your implementation as a base then, give me ~5 minutes.

**Comment by friedemannsommer** [comment]
@lilnasy It took me a bit more than 5 minutes, sorry for that.
I've added the examples i used to your changes here: https://github.com/friedemannsommer/astro/commit/713d0191a344050a7cbc706aba8f93df17e17934

**Comment by lilnasy** [comment]
I need to adjust errors.test.js. I can cherry pick your commit afterwards, thanks!

**Pull request merged**
