### PR TITLE
Move to shiki and stabilize dual themes support

### PR DESCRIPTION
**Pull request by bluwy**
## Changes

`shikiji` has been merged into `shiki` 1.0. This PR also moves back to `shiki`. There weren't any significant changes, so this PR is mainly package name change and small compat code added.

`markdown.shikiConfig.experimentalThemes` is also stabilized as `markdown.shikiConfig.themes` together with the move to `shiki`. It is not considered experimental by `shikiji` or `shiki` anymore.

## Testing

Existing tests should pass

## Docs

I've updated some links in the jsdoc to use the new site https://shiki.style. I've also made a docs PR: https://github.com/withastro/docs/pull/6898

### CODE REVIEW

**Comment by soerenmartius** [comment]
QQ: Wouldn't it make sense to add functionality such as [decorators](https://shiki.style/guide/decorations) to the `<Code/>` component apo also?

**Comment by bluwy** [comment]
I guess we could too, along with [transformers](https://shiki.style/guide/transformers#transformers) which is already supported in `markdown.shikiConfig`. I'm not sure what the current stance is for `Code.astro` since decorators and transformers are shiki-specific features, but I don't mind exposing it.

**Comment by soerenmartius** [comment]
> I guess we could too, along with [transformers](https://shiki.style/guide/transformers#transformers) which is already supported in `markdown.shikiConfig`. I'm not sure what the current stance is for `Code.astro` since decorators and transformers are shiki-specific features, but I don't mind exposing it.

That'd be awesome!

**Comment by CaptainOfPhB** [comment]
@bluwy Can you fix conflicts and merge them into master? I can't wait to use the Shiki :)

**Comment by bluwy** [comment]
I can fix them up later today, but this will only be merged for the next minor, which is scheduled some time next week. There shouldn't be any significant changes on the user-side though.

**Review by sarah11918 — APPROVED** [review]
Approving this (and the accompanying docs PR) for docs!

**Pull request merged**
