### PR TITLE
Add note about imports to migration guide

### LINKED ISSUE #2441: 📘 DOC: When switching from version 0.20 to 0.21 (or 0.22) imports need to be first in the astro frontmatter
It took me three attempts to switch from astro 0.2 to a more recent version.
Finally I figured out the problem. It is due to `import` statemenents in the astro frontmatter.

* With astro 0.20 you could mix them arbitrarily with other javascript code 
* With astro 0.21 and up, you cannot anylonger, instead you get syntax error which at least for me was totally confusing. You need to have all the import statements first

This is breaking change which is not described in the migration guide https://docs.astro.build/en/migration/0.21.0/

It would be great if the documentation could be adapted respectively.
Thank you very much

### PR DESCRIPTION
**Pull request by boehs**
closes #2441

## Changes

- See title

## Testing

- No code changes

## Docs

- Updates 0.21.0.md

### CODE REVIEW

**Comment by boehs** [comment]
cc @schlichtanders

**Comment by jonathantneal** [comment]
This seems like a bug we should fix and not a practice we should encourage. Astro `define:vars` relies on such a restriction not being true.

**Review by jonathantneal — CHANGES_REQUESTED** [review]
This seems like a bug we should fix and not a practice we should encourage. Astro `define:vars` relies on such a restriction not being true.

**Comment by jonathantneal** [comment]
Yea, if we call it out as a bug, that would be fine.

**Review by jonathantneal — APPROVED** [review]
Thank you. I hope this will help folks who encounter the issue.

**Pull request merged**
