### PR TITLE
"-y" parameter

### PR DESCRIPTION
**Pull request by hamer1818**
i used -y parameter for faster loading

## Changes

- What does this change?
  ```npx astro add vue``` 
- Be short and concise. Bullet points can help!
- Before/after screenshots can help as well.
- Don't forget a changeset! `pnpm exec changeset`

## Testing

it's work

### CODE REVIEW

**Review by ankit-gautam23 — COMMENTED** [review]
LGTM

**Comment by bluwy** [comment]
I'm not sure about this. For first-time users, this would auto-accept prompts that they might not want to accept.

**Comment by delucis** [comment]
I agree with @bluwy. Maybe we should document `-y` in the CLI reference in docs but in this context we should show the basic command that lets people choose whether they want to accept changes or not.

**Comment by bluwy** [comment]
Closing this for now as the docs changes can be done separately.

**Pull request closed without merging**
