### PR TITLE
feat(vite-plugin-markdown): support importing markdown files from outside root project 

### PR DESCRIPTION
**Pull request by MoustaphaDev**
## Changes

This change adds support for importing markdown files from outside the root directory of a project, which is very common in monorepo setups

## Testing

TODO - I'll need some assistance for this one
## Docs

TODO - Not sure if it needs documentation but will do if guided
/cc @withastro/maintainers-docs for feedback!

### CODE REVIEW

**Review by natemoo-re — COMMENTED** [review]
I'm not positive about this change, but if this is all it takes to unblock this, that would be very exciting.

Suggestion: you can use `new URL('../jsx-runtime/index.js', import.meta.url)` instead of manually manipulating the `import.meta.url` string, then convert it to a Node path using [`fileURLToPath`](https://nodejs.org/api/url.html#urlfileurltopathurl), then convert it back to a proper import path with Vite's `normalizePath` utility. It's roundabout, but a more robust approach than what you're doing here.

// using absolute path allows imports outside of `src/`
				const astroJsxRuntimeURL = 				const astroJsxRuntime = normalizePath(fileURLToPath(astroJsxRuntimeURL))

**Comment by MoustaphaDev** [comment]
> I'm not positive about this change, but if this is all it takes to unblock this, that would be very exciting.
> 
> Suggestion: you can use `new URL('../jsx-runtime/index.js', import.meta.url)` instead of manually manipulating the `import.meta.url` string, then convert it to a Node path using [`fileURLToPath`](https://nodejs.org/api/url.html#urlfileurltopathurl), then convert it back to a proper import path with Vite's `normalizePath` utility. It's roundabout, but a more robust approach than what you're doing here.

Thanks for the suggestion I refactored it. I hope this PR is not a *works my machine* thing

**Comment by MoustaphaDev** [comment]
I agree this is quite uncommon (supporting imports for markdown imports in monorepo setups was the motivation behind this PR) and I don't know yet how I'd go about testing this

**Comment by natemoo-re** [comment]
From my perspective this is actually a really common pattern! Imagine a top-level `docs` folder for a project where the site logic itself is in some nested directory—docs contributors can just edit pure Markdown files without worry about the site structure.

If this is all it takes to unblock that, I'd be super happy.

**Comment by MoustaphaDev** [comment]
Interesting, I didn't think of that real world use case (just wanted to add that feature because why not 😅). Anyway, looking forward for your suggestions before I submit the PR

**Comment by matthewp** [comment]
I'll remove my objection given @natemoo-re's reasoning. So once @natemoo-re is satisfied with the code I think it's ready to go.

@MoustaphaDev can you mark this PR as being ready for review.

**Comment by MoustaphaDev** [comment]
Done !

**Pull request merged**
