### PR TITLE
sort newest to oldest

### PR DESCRIPTION
**Pull request by jeff-r-koyaltech**

### CODE REVIEW

**Comment by jeff-r-koyaltech** [comment]
I'm just experimenting to see if the tests happen to pass..

**Comment by bluwy** [comment]
Good catch! This makes sense, however I think we still want the order for MDX and markdown guide posts to be the top. In this PR, it'd look like: 
image

Can you update the publish date so that "Markdown Style Guide" is at the top, and "Using MDX" follows second?

**Comment by jeff-r-koyaltech** [comment]
For sure, I'll do that today, thanks for your feedback

**Comment by jeff-r-koyaltech** [comment]
Ok, I think these changes will do it. Here's a screenshot:

Updated blog posts

**Comment by jeff-r-koyaltech** [comment]
Based on what I'm reading at https://github.com/withastro/astro/blob/main/CONTRIBUTING.md, a changeset is not required for this PR.

Locally, I have some tests failing when I do `pnpm run test`, but they don't seem related to my work. I'm wondering if my dev environment isn't quite right since this is my first contribution.

Here are the last few console lines from my failing tests, in case you're curious or concerned:
```
astro:test: test at file:/Users/jeff/src/personal/astro/packages/astro/test/experimental-content-collections.test.js:10:2
astro:test: ✖ Query (998.957917ms)
astro:test:   Error: Cannot find module '/Users/jeff/src/personal/astro/packages/astro/test/fixtures/content-collections/dist/content/without-config/columbia.mjs' imported from /Users/jeff/src/personal/astro/packages/astro/test/fixtures/content-collections/dist/content/entry.mjs
astro:test:       at finalizeResolution (node:internal/modules/esm/resolve:255:11)
astro:test:       at moduleResolve (node:internal/modules/esm/resolve:908:10)
astro:test:       at defaultResolve (node:internal/modules/esm/resolve:1121:11)
astro:test:       at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
astro:test:       at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
astro:test:       at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
astro:test:       at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
astro:test:       at importModuleDynamically (node:internal/modules/esm/translators:146:35)
astro:test:       at importModuleDynamicallyCallback (node:internal/modules/esm/utils:176:14)
astro:test:       at /src/content/without-config/columbia.md (file:///Users/jeff/src/personal/astro/packages/astro/test/fixtures/content-collections/dist/content/entry.mjs:27:52)
astro:test:       at file:///Users/jeff/src/personal/astro/packages/astro/dist/content/runtime.js:64:33
astro:test:       at file:///Users/jeff/src/personal/astro/node_modules/.pnpm/p-limit@6.1.0/node_modules/p-limit/index.js:24:31
astro:test:       at run (file:///Users/jeff/src/personal/astro/node_modules/.pnpm/p-limit@6.1.0/node_modules/p-limit/index.js:24:56) {
astro:test:     code: 'ERR_MODULE_NOT_FOUND',
astro:test:     url: 'file:///Users/jeff/src/personal/astro/packages/astro/test/fixtures/content-collections/dist/content/without-config/columbia.mjs',
astro:test:     id: 'src/pages/collections.json.js'
astro:test:   }
astro:test: 
astro:test: test at file:/Users/jeff/src/personal/astro/packages/astro/test/experimental-content-collections.test.js:189:3
astro:test: ✖ Generates expected pages
astro:test:   'test did not finish before its parent and was cancelled'
astro:test: 
astro:test: test at file:/Users/jeff/src/personal/astro/packages/astro/test/experimental-content-collections.test.js:195:3
astro:test: ✖ Renders titles
astro:test:   'test did not finish before its parent and was cancelled'
astro:test: 
astro:test: test at file:/Users/jeff/src/personal/astro/packages/astro/test/experimental-content-collections.test.js:203:3
astro:test: ✖ Renders content
astro:test:   'test did not finish before its parent and was cancelled'
astro:test: 
astro:test: test at file:/Users/jeff/src/personal/astro/packages/astro/test/experimental-content-collections.test.js:174:2
astro:test: ✖ Static paths integration (781.606917ms)
astro:test:   Error: Cannot find module '/Users/jeff/src/personal/astro/packages/astro/test/fixtures/content-static-paths-integration/dist/content/blog/first-post.mjs' imported from /Users/jeff/src/personal/astro/packages/astro/test/fixtures/content-static-paths-integration/dist/content/entry.mjs
astro:test:       at finalizeResolution (node:internal/modules/esm/resolve:255:11)
astro:test:       at moduleResolve (node:internal/modules/esm/resolve:908:10)
astro:test:       at defaultResolve (node:internal/modules/esm/resolve:1121:11)
astro:test:       at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
astro:test:       at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
astro:test:       at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
astro:test:       at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
astro:test:       at importModuleDynamically (node:internal/modules/esm/translators:146:35)
astro:test:       at importModuleDynamicallyCallback (node:internal/modules/esm/utils:176:14)
astro:test:       at /src/content/blog/first-post.md (file:///Users/jeff/src/personal/astro/packages/astro/test/fixtures/content-static-paths-integration/dist/content/entry.mjs:18:44)
astro:test:       at file:///Users/jeff/src/personal/astro/packages/astro/dist/content/runtime.js:64:33
astro:test:       at file:///Users/jeff/src/personal/astro/node_modules/.pnpm/p-limit@6.1.0/node_modules/p-limit/index.js:24:31
astro:test:       at run (file:///Users/jeff/src/personal/astro/node_modules/.pnpm/p-limit@6.1.0/node_modules/p-limit/index.js:24:56) {
astro:test:     code: 'ERR_MODULE_NOT_FOUND',
astro:test:     url: 'file:///Users/jeff/src/personal/astro/packages/astro/test/fixtures/content-static-paths-integration/dist/content/blog/first-post.mjs'
astro:test:   }
astro:test:  ELIFECYCLE  Command failed with exit code 1.
astro:test:  ELIFECYCLE  Test failed. See above for more details.
astro:test: ERROR: command finished with error: command (/Users/jeff/src/personal/astro/packages/astro) /usr/local/bin/pnpm run test exited (1)
astro#test: command (/Users/jeff/src/personal/astro/packages/astro) /usr/local/bin/pnpm run test exited (1)

 Tasks:    4 successful, 5 total
Cached:    0 cached, 5 total
  Time:    4m32.222s 
Failed:    astro#test

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Test failed. See above for more details.
```

**Review by bluwy — APPROVED** [review]
Amazing. Looks great! No worries about the changeset and the failing tests locally. I've not seen that error before but it's probably a fluke.

**Review by Princesseuh — APPROVED** [review]

**Pull request merged**
