### PR TITLE
feat: use devalue to serialize content layer data

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

Switches content layer to use devalue for the data store serialization, so it supports Dates etc

## Testing
Added a test

### CODE REVIEW

**Comment by matthewp** [comment]
Why can't we serialize Dates as ISO strings? I'm worried that the big perf gain of this feature is going to be erased if we start making it be JS again.

**Comment by ascorbic** [comment]
@matthewp the problem is that zod transform and coerce allows values to be converted to `Date` objects. If we serialise these as strings, we won't be able to convert them back and the types will be wrong.

**Comment by ascorbic** [comment]
I've benchmarked it, and it makes no appreciable difference to the performance when building 10k pages. It's all in one module, so it doesn't have the problem with the old implementation which was having one module per entry.

**Comment by matthewp** [comment]
Won't we run into this problem when we do a sqlite backed storage anyways? If so it's worth tackling it now, imo.

**Comment by matthewp** [comment]
Could we save the raw, untransformed value so that when we rehydrate with Zod it gets us back to where we want to be?

**Comment by ascorbic** [comment]
Do we have access to the schema at runtime? I transformed before insertion because I didn't think we have access to the schema then. For the sqlite backend we'd want to preserve types too if possible.

**Comment by ascorbic** [comment]
If you're concerned about the use of JS, we could serialise to devalue JSON instead, though I think that's a bit slower.

**Comment by ematipico** [comment]
My gut tells me we should prefer a JSON format over JavaScript

**Comment by matthewp** [comment]
Yes, avoiding JS is my biggest issue here. So if using devalue JSON unblocks then that works for me for now. It does feel like a little bit of architectural problem if we don't have full control over serialization though. Maybe that's something we can fix later.

**Comment by ascorbic** [comment]
OK, makes sense. I'll benchmark that and assuming it's ok then I'll update the PR to use it.

**Comment by ascorbic** [comment]
So it turns out it's actually slightly _faster_ to use devalue stringify (i.e. write to JSON rather than JS). Just a matter of 150ms or so with 10k entries, but that will teach me to not do my own benchmarks.

**Review by matthewp — APPROVED** [review]

**Pull request merged**
