### PR TITLE
Remove extra newlines around components in Markdown

### LINKED ISSUE #3493: 🐛 BUG: Using HTML inside markdown produces additional space.
### What version of `astro` are you using?

beta-38

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The <Content /> component seems to produce additional whitespace when using HTML tags inside markdown files. This issue seems to arise because a newline is inserted for content after the HTML tag. This behavior does not follow the HTML spec. Notice the space before the full stop in the reproduction.

FYI, it didn't produce the extra space in beta-34.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ut8fqd?file=src%2Fcontent%2Ftest.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by hippotastic**
## Changes

- Fixes #3493.
- Removes the extra newlines that the previous code wrapped around `mdxJsxFlowElement` and `mdxJsxTextElement` elements with children in Markdown. These extra newlines caused unwanted whitespace to be introduced into the resulting HTML output.

## Testing

- Updated test cases to reflect the new correct output.
- Ran all tests locally.
- Built Astro Docs using the new code without apparent issues.

## Docs

- Just a bugfix.

### CODE REVIEW

**Comment by hippotastic** [comment]
@natemoo-re PTAL :) The failed Windows test should be a fluke.

**Review by natemoo-re — APPROVED** [review]
LGTM, thanks as always!

**Comment by ahmed2m** [comment]
I think this bug (or a variation of it) is present now in .astro files?
https://replit.com/@ahmed2m/Astro-spacing-problem#src/pages/index.astro
image

**Comment by hippotastic** [comment]
@ahmed2m I don't think that this is a bug. In my opinion, what you're seeing here is regular HTML whitespace handling which doesn't have anything to do with Astro. Your code will lead to the same results without even using Astro, but only plain HTML.

Newlines, tabs and spaces are all considered whitespace characters in HTML, and all whitespace characters will be collapsed to one single space (not zero!) by the browser when displaying the page. If you do not want to introduce whitespace into the output, but still wrap lines in your code, you can do something like this:

```htm
    <h2>
      Instead, you can add whitespace before the closing bracket of the
      <span class="test">span</span
      >, which works well!
    </h2>
```

See an example here:
https://stackblitz.com/edit/web-platform-hqtn6w?file=index.html

Hope that helps! :)

**Comment by ahmed2m** [comment]
Yeah, I was using JSX for the longest time and it collapses new lines/spaces into nothing that I thought that's like an html thing.

My problem is I use the prettier plugin and somehow it ALWAYS formats like jsx, (usually) break lines around tags

**Pull request merged**
