### PR TITLE
New `create-astro` UI

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Refactors `create-astro` with some updates we've been wanting for a while.
- Most notably, this is a complete redesign of the `create-astro` UI!
  - Say hello to Houston 👋🏻 
  - Say hello to a new loading spinner!

https://user-images.githubusercontent.com/7118177/189745357-c05f24bc-c48a-4842-8093-fd724a960b25.mp4

**Condensed UI**

CleanShot 2022-09-12 at 15 02 54@2x

**Expanded UI**

CleanShot 2022-09-12 at 15 03 48@2x

## Testing

Manually, test updates are TODO.

## Docs

TODO

### CODE REVIEW

**Comment by FredKSchott** [comment]
Apologies for the spam, just using this PR to test out the new CI action! Will delete these comments after done testing.

**Comment by FredKSchott** [comment]
!preview test

**Comment by FredKSchott** [comment]
!preview test

**Comment by FredKSchott** [comment]
!preview test

**Comment by FredKSchott** [comment]
!preview test

**Comment by matthewp** [comment]
Closing to clean up the open PRs, please resubmit once this is ready for review.

**Pull request closed without merging**
