### PR TITLE
Update deno integration dependencies

### PR DESCRIPTION
**Pull request by lino-levan**
## Changes
- Bumps the `deno_std` dependency to be up to date

## Testing
- No new tests are required since we are just changing the dependency version

## Docs
- I have also updated the dependency in the docs

### CODE REVIEW

**Comment by lino-levan** [comment]
Failing tests are unrelated to this change and look to be flaky?

**Review by delucis — APPROVED** [review]
Docs look good 👍

**Comment by matthewp** [comment]
@lino-levan Yeah, likely a flakey test, I'll rerun it. Thank you!

**Comment by lino-levan** [comment]
super weird... it looks like the failing test isn't erroring out but instead timing out. Wondering if there was a performance regression of astro somewhat recently that's causing the test to fail sometimes?

**Comment by delucis** [comment]
Just tried re-running the failing test. Let’s see what happens 🤞

**Comment by lino-levan** [comment]
Cool, looks like that worked. Thanks @delucis!

**Comment by matthewp** [comment]
Closes https://github.com/withastro/astro/issues/5565

**Pull request merged**
