### PR TITLE
feat: implement concurrency for asset generation

### PR DESCRIPTION
**Pull request by itsmatteomanf**
## Changes

Adds concurrent image generation for `astro:assets` using `p-limit` to improve performance.

## Testing

Actually not sure it needs actual tests, the core functionality is similar.

## Docs

Might be worth mentioning it in docs, but not done anything as of now.

### CODE REVIEW

**Comment by Princesseuh** [comment]
!preview concurrent-assets

**Comment by ematipico** [comment]
Unfortunately we can't generate preview releases from forks. A person with write permissions needs to create a new PR and create the preview from there.

**Comment by Princesseuh** [comment]
> Unfortunately we can't generate preview releases from forks. A person with write permissions needs to create a new PR and create the preview from there.

Yeah, I realized that yesterday. I'll take over it

**Comment by Princesseuh** [comment]
Let's continue at https://github.com/withastro/astro/pull/8821

**Pull request closed without merging**
