### PR TITLE
Fix usage of the Image component with the Vercel adapter

### PR DESCRIPTION
**Pull request by matthewp**
…" (#5360)"

This reverts commit 20e60c6e0857f7b6938494df6027e8c1ad74cdc1.

## Changes

- Allows the image component to be used within Vercel.
- Bundles the squoosh worker along with the other SSR code.
- Moves the wasm files into the chunks folder, like in SSG.

## Testing

- Test app https://astro-test-image-ssr-matthew6.vercel.app/

## Docs

N/A

### CODE REVIEW

**Comment by matthewp** [comment]
!preview vercel-image

**Comment by matthewp** [comment]
!preview vercel-image-2

**Comment by matthewp** [comment]
!preview vercel-image-2

**Comment by matthewp** [comment]
Updated working test app: https://astro-test-image-ssr-matthew6.vercel.app/

**Review by tony-sull — APPROVED** [review]
Looks good!  Glad the `assetIncludes` vite config exists so we can piggy back on that here :+1:

**Pull request merged**
