### PR TITLE
Support the Markdown component in SSR

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- This adds support for the `<Markdown>` component in SSR.

## Testing

- Tests added.

## Docs

N/A, bug fix

### CODE REVIEW

**Review by natemoo-re — APPROVED** [review]
LGTM!

**Comment by matthewp** [comment]
@natemoo-re tests are not passing because the Deno adapter needs everything to be bundled, but we can't bundle `@astrojs/markdown-remark` because it depends on a lot of Node builtin packages.

Should we go back to bundling this package like we used to?

**Comment by natemoo-re** [comment]
Ooh good point, I did not consider all of that... hmm. Let's chat in person probably!

**Comment by matthewp** [comment]
Fixes https://github.com/withastro/astro/pull/3036

**Comment by thepassle** [comment]
@natemoo-re Was any resolution found wrt bundling the `@astrojs/markdown-remark` package?

**Comment by matthewp** [comment]
@thepassle It can't be bundled. The solution is that we import it dynamically on usage. This means it only works on Node.js runtimes, unfortunately. We are discussing alternatives for the future.

**Comment by thepassle** [comment]
Thanks for looking into it, I appreciate it 🙂 At least im unblocked for now 😄

**Pull request merged**
