### PR TITLE
Add tests: Special chars in component import paths

### PR DESCRIPTION
**Pull request by hippotastic**
## Changes

- Adds (currently failing) tests for component imports with special characters in the import path, which get regularly reported in our support channel.
- The fix for the underlying issues still needs to be developed and can then be tested against the tests in this PR.
- Related issues: https://github.com/withastro/astro/issues/3639
- The following special characters in import paths are tested both from `.astro` and `.mdx` files now:
  - Carets (`^`)
  - Emoji (`🚀`)
  - Spaces (` `)
  - Round brackets (`()`)
  - Square brackets (`[]`)

## Testing

- This PR is all about testing. :)

## Docs

- Not a visible change.

### CODE REVIEW

**Comment by Princesseuh** [comment]
Left a comment on the issue about my exploration of this: https://github.com/withastro/astro/issues/3639#issuecomment-1212343852

The fix I committed work, as the tests shows. However, I do believe there might be an underlying issue here somewhere?

**Comment by matthewp** [comment]
@hippotastic These look great! Are you planning on also fixing or do you just want to submit test cases? If the latter we can get this change in by making the tests with `.skip` (like `describe.skip`). This allows the CI to continue to run but we have test cases in the codebase. Then you could link to the tests from within the issue so that when someone grabs the issue they'll already have tests to work off of.

**Comment by hippotastic** [comment]
@matthewp Great idea! I actually thought this PR would be much more short-lived than it turned out to be. Both Erika and Nate already tried their best to get the underlying issue fixed so we could merge these tests. Do you maybe want to give fixing the issue a shot? It's certainly too advanced for me. :)

I'll adapt the test cases as suggested to have CI skip them by tomorrow.

**Comment by matthewp** [comment]
Yes, I'd love to take a look. Maybe in a separate PR though, would still love to get the tests in first!

**Comment by matthewp** [comment]
Thanks so much!

**Pull request merged**
