### PR TITLE
[DO NOT MERGE] Add vanilla JS example

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Adds an example of using Astro with no client-side framework or dependencies

## Testing

N/A

## Docs

N/A

### CODE REVIEW

**Comment by matthewp** [comment]
Looks good to me @natemoo-re, is this ready to be reviewed?

**Comment by FredKSchott** [comment]
chatted in person, but I think a better example to showcase here would be to not try to build something component-like with vanilla JS (and worry about component state, etc).  and instead just do something that runs once on document ready, and maybe writes something or `alert()`s, or something else. 

I think that would be more in line with what a vanilla-js user was looking for.

**Comment by jonathantneal** [comment]
> I think a better example to showcase here would be to not try to build something component-like with vanilla JS

Was it something about this particular demonstration, or in general? I’m probably some context missing, as demonstrating components with JavaScript without a framework seem pretty useful, if the goal of these examples are to demonstrate parity with each other.

**Comment by natemoo-re** [comment]
Would love to circle back to this but happy to close for now.

**Comment by FredKSchott** [comment]
ditto! I still like the idea of a vanilla JS example, and would be happy to come back to this and figure out the best way to showcase.  I think my main issue was that the template and the script were separate, so that the component was split across two different files. As far as examples go, I wasn't sure if we actually wanted to promote this pattern as written as a "best practice".

**Pull request closed without merging**
