### PR TITLE
[🚧 WIP] Add SBOM (and automate the process)

### PR DESCRIPTION
**Pull request by ran-dall**
[Please Don't ship WIP](https://dont-ship.it/)

This commit adds an SBOM to the repository and will automate the process for future use.

SBOM is using [the Cyclone DX 1.4 SBOM specification](https://cyclonedx.org/docs/1.4/json/) and is currently being generated in XML (this may change in the future to JSON, if it's determined preferable).

Special Thanks to @aFuzzyBear for assistance with the Astro-specific knowledge required to complete these audits.

### CODE REVIEW

**Review by aFuzzyBear — COMMENTED** [review]
Getting these `bom.` files for each of astros user facing products is great, really good first step in applying good practice and due diligence, Thank you @ran-dall  for this work my friend 👊💚

**Comment by ran-dall** [comment]
I added the script to autogenerate the `sbom`s. I also replaced the `.xml` `sbom`s with `.json` `sbom`s.

The script isn't the most elegant thing in the world, but it works, which, for now, is good enough for me.

**Comment by matthewp** [comment]
Is this still being worked on?

**Comment by ran-dall** [comment]
@matthewp Yes, I need to meet with @natemoo-re and discuss what we will do with this. I would also love to find a smarter way of automating this.

**Comment by matthewp** [comment]
Going to close for now as this is stale, please feel free to reopen when you are closer to being ready.

**Pull request closed without merging**
