### PR TITLE
chore(tests): allow mocha to reattempt failing cases

### PR DESCRIPTION
**Pull request by lilnasy**
## Changes
Internal

## Testing
Does not affect behavior.

## Docs
Does not affect usage.

### CODE REVIEW

**Comment by lilnasy** [comment]
Might be a better idea to use mocha's `--retry` flag.

**Review by natemoo-re — APPROVED** [review]
LGTM! Makes sense for our sometimes flaky tests.

Does make it a little harder to track down flakes, but I suppose it's better if CI just handles flakes properly.

**Comment by lilnasy** [comment]
Yeah, I was hoping mocha would report the tests it had to retry. Doesn't seem like it.

**Comment by lilnasy** [comment]
Apparently, It emits an event on every retry. So there is a way to get the info.

**Comment by natemoo-re** [comment]
> Yeah, I was hoping mocha would report the tests it had to retry. Doesn't seem like it.

Looks like they do have a [`EVENT_TEST_RETRY`](https://mochajs.org/api/tutorial-custom-reporter) event that bubbles up to the reporter, so maybe it's just that our reporter doesn't display that event?

**Comment by lilnasy** [comment]
It works.
image

It requires creating a custom reporter that replaces the default reporter. Maybe there's a way to extend the default, or inherit from it. I'd rather do that in a different PR.

**Comment by bluwy** [comment]
I'm not really sure if this would be a good change. Since mocha tests (integrations/unit) should generally be stable, I think we should judiciously only retry certain tests that we find flaky, instead of enabling it globally. 

We have `this.retries()` littered to handle this. I think a global retry count would make more sense for e2e tests.

**Comment by lilnasy** [comment]
From what I've noticed, pretty much any test that uses fetch is vulnerable. I don't see per-test retry being viable.

**Comment by bluwy** [comment]
We could probably add some code to `fixture.startDevServer` or `fixture.preview` to ensure the server is really ready before before starting the fetches. But otherwise I don't feel comfortable setting a global number of retries.

It also affects local development as maybe there's 10 fails from a refactor, but because of the retries that 10 fails take forever to show up as they keep repeating intentionally failing code.

**Review by bluwy — CHANGES_REQUESTED** [review]
Blocking until we can find a middleground 😬

**Comment by lilnasy** [comment]
Those are good ideas!

They are more investment though. I think we should invest there but without blocking this PR.

With the custom reporter (maybe upstream: https://github.com/mochajs/mocha/issues/5014), we can let the logs guide us to the flaky tests at a convenient time. Currently, they intrude on and interrupt normal development.

**Comment by bluwy** [comment]
These changes also affect normal development in another way though (like I mentioned above). I could be persuaded if it's retries only on CI, and not locally, but at that point the effort would be similar to fixing the core fetching issue.

**Comment by lilnasy** [comment]
`pnpm test:ci`?

**Comment by bluwy** [comment]
Yeah if we want to go that way, it would be `pnpm test:ci`. But I'm not really sure if it's worth the effort. I've also researched this before which the [Mocha docs](https://mochajs.org/#retry-tests) discourages the use of retries, so I think that would be the last resort.

I've added some additional logs for `fetch failed` before at https://github.com/withastro/astro/blob/9cd6a6657b328cec4ad98020e2bcd73c34a869ce/packages/astro/test/test-utils.js#L169-L179 but seems like it always gets buried. (appending directly to `err.message` could be better)

I think there's a few ways we should try before going with this PR. It casts a very wide net that we can easily miss flaky tests to come up again in the future.

**Comment by ematipico** [comment]
@lilnasy is this PR still relevant? it has 3 weeks of inactivity

**Comment by lilnasy** [comment]
Just waiting on @bluwy further comments.

**Comment by lilnasy** [comment]
What would be a middleground you are comfortable with?

**Comment by lilnasy** [comment]
> We probably just need to set some time to debug why the tests are flaky.

I disagree.  Tests are means to an end IMO. I am hesitatnt to consider them a source of maintenance burden in themselves.

**Pull request closed without merging**
