### PR TITLE
chore: updated esbuild

### PR DESCRIPTION
**Pull request by JuanM04**
## Changes

Update esbuild to its latest version (`0.14.25` --> `^0.14.32`). Also, our lockfile updates will install patch version automatically

### CODE REVIEW

**Comment by matthewp** [comment]
I think this is ok, just want to check if we pinned of a reason, cc @FredKSchott @natemoo-re

**Comment by natemoo-re** [comment]
@matthewp not that I can remember. Maybe an issue introduced in a `patch` version that has since been fixed.

**Comment by FredKSchott** [comment]
iirc it MIGHT have been that certain hashes changed across versions, which made it hard to keep snapshot tests in sync. But, it looks like tests are still passing. I'm not sure.

It may have been that we were trying to match Vite or Snowpack's internal version? But they're now on `"esbuild": "^0.14.27"` so that's no longer accurate either.

If anyone has time to git blame that would be great, but otherwise the fact that this update was painless kind of proves that it's not completely unsafe.

**Comment by JuanM04** [comment]
The last update was made by @FredKSchott: #2750

**Comment by FredKSchott** [comment]
LGTM!

**Pull request merged**
