### PR TITLE
format and organize imports on main auto-formatter

### PR DESCRIPTION
**Pull request by FredKSchott**
## Changes

- does what the title says. Equivalent to running "Organize Imports" in VSCode, but automated on every file, on every commit to main.
- Powered by TypeScript, so it's smart enough to remove unused imports.
- This feels like an important part of formatting, but I wanted to get team thoughts before merging.
- Adds ~30 seconds to formatting, so this only runs in CI.
- Bonus: Running "Organize Imports" can help you automatically resolve merge conflicts on imports, which are annoying to resolve manually.

## Testing

- Tested and run locally, in this PR.

## Docs

- N/A

### CODE REVIEW

**Comment by FredKSchott** [comment]
Ah interesting, we have an odd import on in `packages/integrations/deno/src/server.ts`:

```diff
- import './shim.js';
import type { SSRManifest } from 'astro';
import { App } from 'astro/app';
// @ts-ignore
import { Server } from 'https://deno.land/std@0.132.0/http/server.ts';
+ import './shim.js';
```

We really shouldn't rely on import order in ESM: your runtime doesn't give any guarantee on how these imports run afaik. I think this is why TS feels that its safe to reorder.

Two ways to fix:
1. refactor to remove this trick. If it's not causing trouble for anyone, then I don't think this is worth the effort right now given that I don't think its an easy fix. We probably should add a TODO/NOTE in the codebase for people to watch out for it.
2. wait for this already-merged TS PR to get merged: https://github.com/microsoft/TypeScript/pull/48330. Definitely the easier of the two, but could involve waiting a few more days. I'll close this PR for now and wait for that feature to be released before re-opening, but happy to keep the convo going between now and then.

**Comment by JuanM04** [comment]
@FredKSchott what about [`eslint-plugin-simple-import-sort`](https://github.com/lydell/eslint-plugin-simple-import-sort/)? It keeps those polyfills at the top and works with the already implemented ESLint

**Comment by jasikpark** [comment]
https://www.npmjs.com/package/@ianvs/prettier-plugin-sort-imports should do the job as a prettier plugin 👍

**Comment by IanVS** [comment]
^ I forked that package off from the original specifically to avoid moving side-effect imports.  For some reason the maintainers didn't think it was a problem to move them around.

**Comment by FredKSchott** [comment]
Update: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#groups-aware-organize-imports

Looks like we'll need to wait a bit longer than I wanted, since it's gotten rolled up into the 4.7 beta. Should be at least in Release Candidate in another week or two.

**Comment by FredKSchott** [comment]
Err, on second thought, this won't be out officially until end of May. At least that means before our official v1.0 release! I'm okay waiting, even if I'm sad :)

**Pull request closed without merging**
