### PR TITLE
Allow custom 404 route to handle API route missing methods

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- When we encounter an API route that doesn't have a definition for the method, this should be a 404 and not a 500. Use the custom 404 page if present.
- Fixes https://github.com/withastro/astro/issues/4561

## Testing

- Tests added for dev and prod.

## Docs

N/A, bug fix

### CODE REVIEW

**Comment by bluwy** [comment]
Looks like the tests are failing

**Comment by jazoom** [comment]
I'd suggest there be another way to handle this.

Serving a 404 page might be appropriate for a user navigating with a web browser to a missing page, but it's not appropriate to respond to, for example, a DELETE request to an incorrect API URL.

**Review by tony-sull — COMMENTED** [review]
💯 this should be a 404 rather than 500, I'm a little worried about the extra response time added by using the custom 404 page though

Thoughts on returning a 404 with either an empty body or a simple error message?

**Comment by matthewp** [comment]
@tony-sull I guess my main thought is that if we don't return the custom 404 page people will report that as a bug. I think the expectation is that *all* 404s go through 404.astro. I think we should prioritize correctness here.

**Review by tony-sull — APPROVED** [review]
LGTM (followed up offline re: rendering 404 HTML)

**Comment by matthewp** [comment]
Thanks @tony-sull

**Pull request merged**
