### PR TITLE
fix: Lookbehind regex crashing on Safari

### LINKED ISSUE #4865: Lookbehind regex crashing on Safari
### What version of `astro` are you using?

1.3.0

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

File [`src/runtime/server/render/util.ts`](https://github.com/withastro/astro/blob/f8c2d828bd6fd15fabac334a489d1c3ab7e2d209/packages/astro/src/runtime/server/render/util.ts) uses the following regex with lookbehind `/(?:(?<!^)\b\w|\s+|[^\w]+)/g`, which is [not supported](https://caniuse.com/js-regexp-lookbehind) on Safari.

My code [https://github.com/marcoseiza/PersonalWebsite#personal-website](https://github.com/marcoseiza/PersonalWebsite#personal-website).

Live Website With problem (Not permanent) [https://meizayaga.com/blog](https://meizayaga.com/blog)

### Link to Minimal Reproducible Example

https://meizayaga.com/blog

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
Attempts to fix #4865 

I'm not a regex master, but given that here negative lookahead, shall behave same as lookbehind (as for matching spaces (or anything)). To me these two regexs seem same as checked on regex101.com's explanation.

This happens as the component is loaded with client:idle that requires that chunk of JS to be inserted as an island so it runs in the browser eventually.

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
Just saw that this is server render, and hence won't run in the browser. Closing this.

**Review by bluwy — APPROVED** [review]
I've had my fair share of removing negative lookbehind to support Bun, and this looks good to me 😄 

As to how this got into the client code, I'm not sure if it's intended or a bug @matthewp

**Comment by matthewp** [comment]
Yeah, I think this never runs in the browser @rishi-raj-jain

**Comment by rishi-raj-jain** [comment]
@matthewp It does, https://github.com/withastro/astro/issues/4865#issuecomment-1257228891

**Comment by matthewp** [comment]
That reproduction doesn't make sense to me, this code is not used by the client, unless perhaps if you are using `client:` on an Astro component which is not supported. Is that what is happening?

**Comment by matthewp** [comment]
Oh interesting, ok thank you.

**Pull request merged**
