### PR TITLE
fix: handle trailing slash on the image endpoint

### PR DESCRIPTION
**Pull request by Princesseuh**
## Changes

Add a trailing slash to the image endpoint based on the trailing slash config, like we do for base

Fixes https://github.com/withastro/astro/issues/11568

## Testing

Added tests

## Docs

N/A

### CODE REVIEW

**Review by bluwy — COMMENTED** [review]
Instead of adding `import.meta.env.*`. Maybe we can add the trailing slash to `endpoint.route` directly here? https://github.com/withastro/astro/blob/b0827022afa52a13d49c37c6c549212aecd32cc5/packages/astro/src/core/config/schema.ts#L648-L670

**Comment by Princesseuh** [comment]
> Instead of adding `import.meta.env.*`. Maybe we can add the trailing slash to `endpoint.route` directly here?
> 
> https://github.com/withastro/astro/blob/b0827022afa52a13d49c37c6c549212aecd32cc5/packages/astro/src/core/config/schema.ts#L648-L670

I thought about it, but I figured that this value is generally useful to users when building URLs (much like BASE_URL or ASSET_PREFIX is) so we might as well expose it, what do you think?

**Comment by Princesseuh** [comment]
Okay, I'll adjust and we can kick the can of "how to access config values in Astro" even further down the road 🫡

**Review by bluwy — APPROVED** [review]

**Review by ematipico — APPROVED** [review]
Why does the PR point `next` and not `main`?

**Comment by Princesseuh** [comment]
> Why does the PR point `next` and not `main`?

you can't customize the endpoint in main, so this is not relevant

**Review by florian-lefebvre — APPROVED** [review]

**Pull request merged**
