### PR TITLE
Allow image-pool to be used as its own Worker

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Dynamically import image-pool so it can be launched as its own worker with `import.meta.url`. This makes it work correctly when bundled for SSR.
- Customize the chunk name so that it finds its wasm modules.
- Give a good error message when an unsupported adapter is used.
- Closes https://github.com/withastro/astro/issues/5253
- Closes https://github.com/withastro/astro/issues/5307

## Testing

- Tested with example project provided here: https://github.com/withastro/astro/issues/5253
- Tested with `@astrojs/node`
- Tested with `@astrojs/vercel/serverless`.

## Docs

N/A, bug fix

### CODE REVIEW

**Review by tony-sull — COMMENTED** [review]
Is there specific about the hosted SSR environments that allowed @astrojs/image to work in our SSR tests and locally with the node adapter but break in Netlify/Vercel?  Or are the existing SSR tests broken?

**Comment by matthewp** [comment]
!preview vercel-image

**Comment by matthewp** [comment]
!preview vercel-image

**Comment by matthewp** [comment]
@tony-sull The problem is because of this line: https://github.com/withastro/astro/blob/7f3b0398e0350d268f5d07fa2d2520efed7af9be/packages/integrations/image/src/vendor/squoosh/image-pool.ts#L15

It's not able to find that file to launch as a worker. I'm not 100% sure why; my guess would be that the cwd is not relative to node_modules perhaps. For Vercel it might be inside of their `.vercel` folder instead.

The fix is to make image-pool.js it's own separate bundle (chunk) and then launch itself as a worker instead, see here: https://github.com/withastro/astro/blob/7f3b0398e0350d268f5d07fa2d2520efed7af9be/packages/integrations/image/src/vendor/squoosh/image-pool.ts#L15

Here's a demo app example

- ❌ `main` branch - https://astro-test-image-ssr.vercel.app/
- ✅ PR branch - https://astro-test-image-ssr-matthew6.vercel.app/

**Review by tony-sull — APPROVED** [review]
Excellent fix!

Really interesting to see that the build output ends up in different locations in the hosted build, not sure the right way to test that as part of our CI 🤔

**Review by natemoo-re — APPROVED** [review]

**Pull request merged**
