### PR TITLE
Teardown compiler to improve rendering perf

### PR DESCRIPTION
**Pull request by bluwy**
## Changes

Use `@astrojs/compiler` `teardown()` API to remove the internal WASM instance and cache after we're finished with the Vite build.

## Testing

All existing test should pass. `!bench memory` _should_ show an improvement too, but it doesn't because the technique to capture "heap used" includes the garbage collection root (for some reason).

But when testing with docs locally, I can see the optimization working where Vite build memory gets offloaded during rendering.

## Docs

n/a. internal refactor.

### CODE REVIEW

**Comment by bluwy** [comment]
!bench memory

**Comment by bluwy** [comment]
This is good for review now. The `!bench memory` results above should be the same as the latest commit as they're using the same compiler.

**Review by natemoo-re — APPROVED** [review]

**Comment by bluwy** [comment]
Hmm. This seems to make CI tests even longer! I guess it's a double-edge sword with the `teardown()` API, where running builds many times causes the WASM instance to instantiate more times, slowing it down 🤔 

Maybe we can skip teardown for tests for now.

**Comment by bluwy** [comment]
!bench memory

**Review by natemoo-re — APPROVED** [review]
Change to toggle the setting makes sense, still approved! 👍

**Pull request merged**
