### PR TITLE
Update build.inlineStylesheets docs

### PR DESCRIPTION
**Pull request by TheOtterlord**
## Changes

Updates `build.inlineStylesheets` docs to clarify it affect project styles, not all styles (e.g. `client:*` injected styles).
Closes https://github.com/withastro/docs/issues/3769

## Testing

N/A

## Docs

/cc @withastro/maintainers-docs for review

### CODE REVIEW

**Review by ElianCodes — APPROVED** [review]
Hey @TheOtterlord! Thanks for taking care of this PR! Looks good to me!

**Comment by ElianCodes** [comment]
Maybe we'll also cc @natemoo-re here, as the author of the original issue.
(also updating branch, to see if CI passes this time)

**Comment by lilnasy** [comment]
Looks great to me!

**Review by natemoo-re — APPROVED** [review]
Looks great, thanks for updating!

**Pull request merged**
