### PR TITLE
Support Typescript paths/aliases in astro.config.ts

### PR DESCRIPTION
**Pull request by zokkis**
## Changes

- add vite-aliases to createViteServer to support tsconfig paths in astro.config.ts
- fixes https://github.com/withastro/astro/issues/9782

### CODE REVIEW

**Review by matthewp — CHANGES_REQUESTED** [review]
Blocking because this is marked as `major` and we want to avoid accidentally merging a major change. I think this could actually be marked as `minor` though.

**Comment by matthewp** [comment]
Going to discuss this internally with the core team. My initial thoughts are:

- This is a nice quality-of-life improvement and does something people might expect; not knowing that configs run in a different context.
- This won't work with `astro.config.mjs` files since they do not load through Vite. Will people find that surprising?
- Other Vite plugins we have won't exist in the config still. Will people find that confusing? What is special about tsconfig aliases that they should be present in the config but not other features?

**Comment by gitZokki** [comment]
> Blocking because this is marked as `major` and we want to avoid accidentally merging a major change. I think this could actually be marked as `minor` though.

Sorry for the confusion. This is my first PR outside my work and I followed the [instructions](https://github.com/withastro/astro/blob/main/CONTRIBUTING.md) to run `pnpm exec changeset`

But yes, I will change this with my next commit

**Comment by gitZokki** [comment]
> Going to discuss this internally with the core team. My initial thoughts are:
> 
>     * This is a nice quality-of-life improvement and does something people might expect; not knowing that configs run in a different context.
> 
>     * This won't work with `astro.config.mjs` files since they do not load through Vite. Will people find that surprising?
> 
>     * Other Vite plugins we have won't exist in the config still. Will people find that confusing? What is special about tsconfig aliases that they should be present in the config but not other features?

The 2. point -> yes this works with mjs files, I tried it (with my fix)
The 3. point -> I only found one other instance where plugins are loaded and this are the following

```
			astroVitePlugin({ settings, logger }),
			astroScriptsPlugin({ settings }),
			// The server plugin is for dev only and having it run during the build causes
			// the build to run very slow as the filewatcher is triggered often.
			mode !== 'build' && vitePluginAstroServer({ settings, logger, fs }),
			envVitePlugin({ settings }),
			markdownVitePlugin({ settings, logger }),
			htmlVitePlugin(),
			mdxVitePlugin({ settings, logger }),
			astroPostprocessVitePlugin(),
			astroIntegrationsContainerPlugin({ settings, logger }),
			astroScriptsPageSSRPlugin({ settings }),
			astroHeadPlugin(),
			astroScannerPlugin({ settings, logger }),
			astroInjectEnvTsPlugin({ settings, logger, fs }),
			astroContentVirtualModPlugin({ fs, settings }),
			astroContentImportPlugin({ fs, settings }),
			astroContentAssetPropagationPlugin({ mode, settings }),
			vitePluginMiddleware({ settings }),
			vitePluginSSRManifest(),
			astroAssetsPlugin({ settings, logger, mode }),
			astroPrefetch({ settings }),
			astroTransitions({ settings }),
			astroDevToolbar({ settings, logger }),
			vitePluginFileURL({}),
			!!settings.config.i18n && astroInternationalization({ settings }),
```

`configAliasVitePlugin` - is now added
`astroLoadFallbackPlugin` - was already in
`astroVitePlugin` - is maybe interesting - I don't know anything about this but after reading the Doc this should allow to import .astro files and maybe there is a use for this? - but whats the difference to `astroPostprocessVitePlugin`
`astroScriptsPlugin` - this loads some sort of scripts? Maybe not so usefull?
`vitePluginAstroServer` - I think this should be omitted, because its only usefull in dev-mode?
`envVitePlugin` - its usefull for better ENV
`astroIntegrationsContainerPlugin` - 'Connect Astro integrations into Vite, as needed.' maybe useless for the config?
`astroScriptsPageSSRPlugin` - more scripts? Not so usefull?
...

So there are some Plugins for html/mdx/transitions/devTools which are not usefull for the config but there are some that are quite interesting. And I think that adding this can improve and unify things a lot. 

Please keep in mind, that this is my first time ever using vite but I'm willing to learn and maybe help to improve the aliases/plugin support in the config

**Comment by Eveeifyeve** [comment]
This would be useful since you don't have to keep adding paths every time you have a path aliases.

**Comment by zokkis** [comment]
> We discussed this internally and decided we don't want to make more differences between `astro.config.ts` and `astro.config.mjs`. So while we appreciate the effort here, it's not a feature we want in Astro.

Looks like nobody of you understood the problem...

**Pull request closed without merging**
