### PR TITLE
Indentation fixes (spaces --> tabs mostly)

### PR DESCRIPTION
**Pull request by mrienstra**
## Changes

- Replace ` {2}` with `\t` (spaces to tabs) where applicable.
- Found & fixed some other indentation issues
- Note that `prettier` is insisting on using a pair of spaces when indenting ternary operators, see [Google search: site:github.com/prettier/prettier/issues ternary spaces tabs](https://www.google.com/search?q=site%3Agithub.com%2Fprettier%2Fprettier%2Fissues+ternary+spaces+tabs), I left these alone, as they will just reappear next time `prettier` runs. They can be located with:
  ```
  ^\t+[:?].+\n\t+ {2}
  ```
- In several cases, I took `.astro` files with mixes tabs and spaces and converted them to spaces-only, but maybe I should back out those changes, and convert spaces-only `.astro` files to tabs-only, as that seems to be (slightly) more common?
- In general, my personal take is that this codebase should change to spaces only, or failing that, `.astro` files and `.md` files should only use spaces (`.md` files are already mostly spaces-only). The Astro Docs repo uses spaces, and having both repos synced would reduce the occurrence of mixed indentation due to copy-and-pasting without "show invisibles" / "show spaces" enabled in code editors.

## Testing

n/a, no actual code changes.

## Docs

n/a, no actual code changes.

### CODE REVIEW

**Comment by Princesseuh** [comment]
Hello, it's definitely intended that we use tabs instead of spaces.

This is for accessibility reasons and was a deliberate change on our part 😄 If the docs is using spaces, I would consider it an issue on their end, as our other codebases (at least, language-tools and prettier-plugin-astro) are all using tabs

**Comment by mrienstra** [comment]
There were 3 `.astro` files that I had converted from a mixture of spaces & tabs, to:
- spaces in the first commit
- tabs in the second commit

**Comment by mrienstra** [comment]
Hmm... Pretty sure test failure is unrelated to changes in this PR... 🤔

**Comment by mrienstra** [comment]
@Princesseuh, is there anything I can do to move this forward? E.g., do you need me to remove all changes to `/fixtures/` files?

**Comment by Princesseuh** [comment]
> @Princesseuh, is there anything I can do to move this forward? E.g., do you need me to remove all changes to `/fixtures/` files?

Hey, sorry for not following up! In my opinion yeah, we should leave fixtures as is for now. The rest looks good!

**Comment by matthewp** [comment]
Agree, @mrienstra if you wouldn't mind removing the fixture changes I think we can get this in. Thanks!

**Comment by matthewp** [comment]
Going to close for inactivity. Please feel free to reopen when this is ready to go.

**Pull request closed without merging**
