### PR TITLE
Reverting #2649 (fine-grained HMR support)

### PR DESCRIPTION
**Pull request by tony-sull**
## Changes

The fine-grained HMR support causes an issue with tailwind, [2660](https://github.com/withastro/astro/issues/2660) is what I ran into

Filing this PR in case its our only option for now, but I'd hate to see this feature go!  Happy to close this out and never merge in the `revert`

There's still an underlying issue somewhere that's preventing Tailwind styles from being available as soon as the dev server fires up.  That's what's really making this more hmr behavior more obvious, our websocket hmr is intercepting the change and never triggering a rebuild.

## Testing

Build and tests are still passing

## Docs

Just reverting, no docs needed

### CODE REVIEW

**Comment by matthewp** [comment]
lgtm, unless there is a quick fix known it makes sense to revert to fix the regression and then bring this back later.

**Comment by FredKSchott** [comment]
yup, agreed on strategy. Stability > features if it comes down to it

**Comment by natemoo-re** [comment]
Fixed properly without a rollback in https://github.com/withastro/astro/pull/2681.

**Comment by FredKSchott** [comment]
NICE! awesome work

**Pull request closed without merging**
