### PR TITLE
refactor(vercel): Build Output API v3

### PR DESCRIPTION
**Pull request by JuanM04**
## Changes

Now with Build Output API (v3)!

- Multiple deploy targets: `edge`, `serverless` and `static`.
- When building to `serverless`, the code isn't transpiled to CJS anymore.
- Meta: removed `.output/` from gitignores

**The users that migrate from v0.1 will have to do this:**

1. Change the import inside `astro.config.mjs`:
   ```diff
   - import vercel from '@astrojs/vercel'
   + import vercel from '@astrojs/vercel/serverless'
   ```
2. Rename the `ENABLE_FILE_SYSTEM_API` environment variable to `ENABLE_VC_BUILD`, as Vercel changed it.
3. The output folder changed from `.output` to `.vercel/output` — you may need to update your `.gitignore`.

### CODE REVIEW

**Comment by TooTallNate** [comment]
This is very cool! I'd love to test it out. Can you add testing instructions?

Also, if you have any questions and/or feedback regarding the new Build Output API, we'd love to hear from you over [here](https://github.com/vercel/community/discussions/577).

Cheers!

**Comment by JuanM04** [comment]
@TooTallNate Thank you! I've been doing the following:

1. Clone this branch and run `pnpm install && pnpm build`
2. Clone one of the Astro starters (you can use `pnpm create astro`)
3. In the new project, add the local Vercel integration (`pnpm add -D @astrojs/vercel@link:~/path/to/astro/packages/integrations/vercel`)
4. Follow the instructions in the integration README
5. Deploy to Vercel with
   ```sh
   ENABLE_VC_BUILD=1 astro build
   vercel deploy --prebuilt
   ```

**Comment by TooTallNate** [comment]
Worked great for me 😄 https://my-astro-site-4nt1lu3gs-tootallnate.vercel.app/

**Comment by JuanM04** [comment]
Hey, @TooTallNate, I've been doing some testing about copying `node_modules/` inside the function folder (a60f182654d5c3852587b253bedbd9332c106b6c), and I think I'm having problems with symlinks. Do you know why this can be happening? Maybe Vercel doesn't support symlinks in its `output/`?

**Comment by JuanM04** [comment]
Just as a note, this new version of the adapter fixes problems with Prisma: https://discord.com/channels/830184174198718474/845451724738265138/973950046531883048

**Review by matthewp — APPROVED** [review]

**Pull request merged**
