### PR TITLE
jquery framework integration

### PR DESCRIPTION
**Pull request by JLarky**
image

<a href="https://www.loom.com/share/120ac82dd07e49ba80e50dd94cbbd956">
<p>Astro+jQuery=❤️ - Watch Video</p>
</a>

### CODE REVIEW

**Comment by orenelbaum** [comment]
Thank you! Now I can finally use Astro with my favorite framework

**Comment by JLarky** [comment]
Okay, on a more serious note :) I think I found a few ways to use jquery that I think are closer to how it was intended to be used :) https://github.com/withastro/astro/commit/60c3c5e8e2155957d7898a438dc6e6d4c96fabfe https://github.com/withastro/astro/commit/8f8a58bbf090fd7da37dd4729b62814462aa67c2 (my benchmark was this html https://github.com/withastro/astro/commit/321db8cdc258193b6c02b50d76e2b52c6f2043d9)

CDN-hosted script tag doesn't seem like a modern way to do things :) and I had to use `.html` template for it to work :)
Imports for jquery are busted in hundred different ways, I was able to find some vite configuration https://github.com/vitejs/vite/discussions/9415 that might probably help.

this PR was intended as a joke, but in my mind it touches 3 real issues:
- if Astro wants to compete with PHP, then it should have a working jquery example :)
- `client:` directives should work for "regular" frameworks like Alpine or jQuery (I think I asked about this once on discord before)
- configuration of global script tags should be improved. I think it's awkward that alpine is included now on every page even if it doesn't use it (but I guess the same problem is there for tailwind and party town integrations). As well as you can't configure those scripts once they are installed. So it would be cool to have something like `import "Counter.alpine"`, or `<script type="application/jquery">` to trigger the inclusion of global script

**Comment by matthewp** [comment]
This is really cool! But I think we don't want to take on new packages unless they are from a maintainer, even though this one is small and very cool. I encourage you to publish it yourself and if the telemetry data shows that it's highly used we'll reconsider bringing into core. Nevertheless I appreciate the spirit!

**Comment by JLarky** [comment]
> This is really cool! But I think we don't want to take on new packages unless they are from a maintainer, even though this one is small and very cool. I encourage you to publish it yourself and if the telemetry data shows that it's highly used we'll reconsider bringing into core. Nevertheless I appreciate the spirit!

That makes sense. I still think that jQuery example folder should be there in the official repo, so that it shows up in astro.new

**Comment by matthewp** [comment]
@JLarky Yeah, I agree that an example is still useful. If you want to move the integration into your own repo and have this PR just for the example I think that would be great!

**Pull request closed without merging**
