### PR TITLE
Exit gracefully when encountering a Node.js bug

### LINKED ISSUE #8411: Build fails with Node 20.6
### Astro Info

```block
Astro                    v3.0.8
Node                     v20.6.0
System                   Linux (x64) // also Windows (x64)
Package Manager          pnpm        // also npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

image

### What's the expected result?

Users are able to build their projects.

### Link to Minimal Reproducible Example

Any astro project on Node 20.6

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by lilnasy**
## Changes
Closes #8411 
image

## Testing
Does not affect behavior. Existing tests should pass.

## Docs
Does not affect usage.

### CODE REVIEW

**Comment by bluwy** [comment]
I'm not really sure if we should do anything due to a Node.js bug, it looks like an urgent regression affecting many other projects and the Node issue shows there's currently work on it.

**Review by matthewp — APPROVED** [review]

**Review by bluwy — CHANGES_REQUESTED** [review]
Temporarily blocking this for now to see if Node will be fixing this soon. If not we can go ahead and merge this.

**Comment by ematipico** [comment]
I also think we should wait and see.

**Comment by lilnasy** [comment]
I agree about waiting. Although, a warning by astro would be helpful because the issue will probably send users on a wild goose chase. I doubt many will expect it to be because of node.

If the majority opinion is against it, I don't mind closing this PR.

**Comment by lilnasy** [comment]
Has a PR: https://github.com/nodejs/node/pull/49500

**Comment by lilnasy** [comment]
The PR was merged, although node is yet to cut a release.

**Comment by natemoo-re** [comment]
Node will surely cut a release soon, now that a fix has been merged. I'm going to close this, but appreciate the PR as always!

**Pull request closed without merging**
