### PR TITLE
fix(vercel): now works with monorepos

### LINKED ISSUE #5020: Vercel deployments broken with pnpm
### What version of `astro` are you using?

1.4.6

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

When deploying an Astro site inside a pnpm monorepo to Vercel with the `@astrojs/vercel/serverless` adapter, the deployment succeeds, but all requests fail with 500 errors. See this deployed example - [https://pnpm-astro.vercel.app/](https://pnpm-astro.vercel.app/)

The only error being thrown in the logs is:

```
ERROR	Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@astrojs/vercel' imported from /var/task/entry.js    at new NodeError (node:internal/errors:372:5)
```

This is essentially a duplicate of [https://github.com/withastro/astro/issues/4567](https://github.com/withastro/astro/issues/4567), but I'm re-opening this specifically for pnpm / Vercel functionality.

I'll also note that `shamefully-hoist=true` in the root `.npmrc` doesn't seem to have any effect, [even though it was fixed](https://github.com/withastro/astro/issues/4567#issuecomment-1270586418) in `>1.4.0`

### Link to Minimal Reproducible Example

https://github.com/sammccord/pnpm-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by JuanM04**
## Changes

Fixes #5020

`@astrojs/vercel` now supports monorepos correctly by adding files outside the project root (like the node_modules/ in the monorepo root)

## Testing

```bash
$ pnpm add @astrojs/vercel@next--monorepos
```

### CODE REVIEW

**Comment by JuanM04** [comment]
!preview monorepos

**Comment by JuanM04** [comment]
!preview monorepos

**Comment by JuanM04** [comment]
!preview monorepos

**Review by matthewp — APPROVED** [review]
Looks great! Thanks so much.

**Comment by matthewp** [comment]
Yep!

**Comment by matthewp** [comment]
@JuanM04 done!

**Comment by JuanM04** [comment]
Thanks!!

**Pull request merged**
