### PR TITLE
Add support for incremental builds

### PR DESCRIPTION
**Pull request by natemoo-re**
# WIP, interested in feedback

## Changes

- Adds incremental support to `astro build`

`astro build` now accepts a set of output paths that Astro should rebuild.

```bash
# static: rebuild `src/pages/index.astro`
astro build "/"
# dynamic: rebuild `/authors/nate` from `src/pages/authors/[author].astro`
astro build "/authors/nate"
# dynamic: rebuild all `/authors/...` paths from `src/pages/authors/[author].astro`
astro build "/authors/*"
# combined: rebuild `src/pages/index.astro` and `src/pages/authors/[author].astro`
astro build "/" "/authors/*"
```

You can also specify source files that have been updated! Astro can trace these inputs to determine exactly which pages need to be rebuilt. 🎉

```bash
# single page source, builds any paths generated by this file
astro build "src/pages/authors/[author].astro"
# shared component, builds any page that uses this component
astro build "src/components/Navigation.astro"
# multiple files
astro build "src/pages/index.astro" "src/components/Navigation.astro" "src/components/Counter.svelte"
```

## Testing

TODO. Manual but definitely needs automated testing.

## Docs

TODO

### CODE REVIEW

**Comment by FredKSchott** [comment]
I love this as an exploration! Two things to consider before considering the PR itself:

- This should definitely get an RFC! This PR would be a great prototype to show that it is possible, what is difficult about it, etc.
- I'd really strongly push us to consider this after SSR support is complete. So much will change when we go to building pages ahead of time that I worry much of this will become outdated (or if merged before SSR, will make SSR that much more difficult to ship).

**Comment by thisislawatts** [comment]
Wow, this is really cool to see @natemoo-re. Thanks for sharing the exploration. I think this would be a great fit for a use case I have in mind.

The scenario contains multiple content types, such as user profiles and recipes. This incremental build would allow the build system to react to an edit event on a recipe document and then rebuild only the `/recipes/*` section. :sparkles: 

I don't have much context on the challenges facing the SSR work, but good luck! I will be sure to track this PR and/or RFC

**Comment by natemoo-re** [comment]
I'm going to close this since we're pushing incremental builds out beyond v1.0. 

SSR will likely come first and have a huge impact on our build process. But the basic techniques are outlined in this PR!

**Comment by kaushalyap** [comment]
@FredKSchott @natemoo-re Any plans to bring incremental builds now that 1.0 is out?

**Comment by FredKSchott** [comment]
We're beginning to plan our post-v1.0 roadmap! Please comment here: https://github.com/withastro/rfcs/discussions/247

**Pull request closed without merging**
