### PR TITLE
feat(ViewTransitions): use `scrollend` instead of `scroll` where supported

### PR DESCRIPTION
**Pull request by kurtextrem**
## Changes

The [scrollend](https://developer.chrome.com/blog/scrollend-a-new-javascript-event/#event-details) mechanism seems like a better way to record the scroll position compared to throttling, so we could use it whenever a browser supports it.

Additionally, I've removed the `{passive}` flag from the `scroll` event, as it does nothing ([source](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener?retiredLocale=de#improving_scrolling_performance_with_passive_listeners:~:text=You%20don%27t%20need%20to%20worry%20about%20the%20value%20of%20passive%20for%20the%20basic%20scroll%20event.%20Since%20it%20can%27t%20be%20canceled%2C%20event%20listeners%20can%27t%20block%20page%20rendering%20anyway.)).

- [x] TODO: run `pnpm exec changeset`

## Testing

I've tested it locally, but maybe I'm missing out how you are testing changes to this component.

## Docs

Open question: Does it make sense to document we're using `scrollend` in modern browsers? Personally, I don't think so (implementation details), but maybe it's interesting for some techy folks.

### CODE REVIEW

**Review by martrapp — COMMENTED** [review]
Definitely an improvement! 😃

**Comment by matthewp** [comment]
sgtm. Need a changeset and to not be in draft status. `pnpm changeset`

**Comment by kurtextrem** [comment]
@martrapp @matthewp Thank you! I've added a changeset.

**Comment by matthewp** [comment]
Ok, want to talk through this just a little more. Does `scrollend` wait until the user releases their fingers from the trackpad / screen? If so, is that what we want? When reading an article your fingers may remain the entire time as you scroll slowly. Does `scrollend` allow us to keep the scroll position as people do this slow scroll?

**Comment by kurtextrem** [comment]
>  When reading an article your fingers may remain the entire time as you scroll slowly

The `scrollend` event only fires after you lift your finger (check out the demo at the [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollend_event#using_scrollend_with_an_event_listener) page), but at least I can not think of a manual way to trigger a link after scrolling without lifting your finger. A back gesture (on Android) can also not be triggered without lifting the finger at least once again.

However, if you scroll around, keep your finger at some position and e.g. some random non-Astro JS triggers a navigation after a specific timeout, `scrollend` will never fire. In that case the scroll position is lost, but I'm not sure if the implementation is trying to cover that (at least not from the comment in the code, as far as I can tell).

**Comment by martrapp** [comment]
you could try to keep scrolling the mouse wheel while you press one handed Alt-<left-arrow>. That seems to be a corner case we can simply ignore.

**Comment by martrapp** [comment]
… I assume, we could even define the router without listening to scroll events

**Review by matthewp — APPROVED** [review]

**Review by martrapp — COMMENTED** [review]
Would be happy to approve, but ...
image
😃

**Comment by matthewp** [comment]
Oh! Sorry about that. I'll take this comment as an approval. I guess access is only for maintainers (which you are on track to become imo).

**Pull request merged**
