### PR TITLE
fix(error pages): account for trailingSlash

### LINKED ISSUE #9079: Custom 404 in SSR with `trailingSlash = always` not working
### Astro Info

```block
Astro                    v3.5.3
Node                     v18.16.0
System                   Windows (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Custom 404 file not being served when `trailingSlash = always` using node adapter

If the value of trailingSlash is either `ignore` or `never` it works fine, contents of custom 404.astro are served for any path or file not found

### What's the expected result?

Expected result would be the 404.html content being served regardless the trailingSlash value

NOTE: run the reproduction using `npm i && astro build && node dist/server/entry.mjs`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qag26k?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by lilnasy**
## Changes

- Fixes #9079
- Route pattern regex includes a slash, now the path being matched does too.

## Testing
- Removed `custom-404-server` fixture and test as `ssr-api-route-custom-404` tested for the same thing.
- Removed `status-code` fixture and test as `custom-404` tested for the same thing. Migrated the build test case unique to `status-code`.
- Renamed `ssr-api-route-custom-404` fixture and test to `ssr-error-pages` as its scope wasn't limited to api routes.
- Added tests relevant to the fix in `ssr-error-pages`.

## Docs
Does not affect usage.

### CODE REVIEW

**Comment by lilnasy** [comment]
!preview 404-trailing-slash

**Review by natemoo-re — APPROVED** [review]
😅 Wow, my two favorite issues have joined forces! LGTM.

**Review by ematipico — APPROVED** [review]
Can we add a test case? So we are covered for possible regressions

**Comment by lilnasy** [comment]
Sure, but I can't get to it until next week.

**Comment by florian-lefebvre** [comment]
@lilnasy can you add the missing test?

**Comment by lilnasy** [comment]
Ah, completely forgot about this one!

**Review by florian-lefebvre — APPROVED** [review]

**Pull request merged**
