### PR TITLE
fix: telemetry to respect config for disabled state

### PR DESCRIPTION
**Pull request by Belar**
## Changes

- Fixed telemetry to respect config for a disabled state
  If a config holds a “disabled” state (a falsey value, e.g. `”enabled” : false`), read with `getConfigWithFallback`, it will be interpreted as a “no value”, resulting in a trigger of a fallback. For example, it causes telemetry to re-enable itself on a call of `enabled` getter.

## Testing

- Tested logic manually
- Added relevant case to package’s unit tests

## Docs

Not applicable.

## Notes

- I’m not sure about a policy for adding new dependencies. Would say Sinon is in a similar category as Chai (an existing dependency).

### CODE REVIEW

**Comment by matthewp** [comment]
Thank you for submitting the PR! A few things:

- `setEnabled` is documented as taking only a boolean. So we shouldn't need to cover this being passed other falsey values like `null` and `undefined`. Those are not supported arguments.  If you want, you could have checks in `setEnabled` to throw if passed a non-boolean.
- We currently don't use any mocking libraries in Astro. I'm very appreciative at how far you've gone to test this change, but I don't think we want to start using sinon just for this.
  - An alternative idea is to allow passing in a fetch function into the constructor. This would give you the ability to essentially do the same thing.

**Review by matthewp — CHANGES_REQUESTED** [review]
Changes requested above.

**Comment by matthewp** [comment]
Going to close for now to clean up the PRs. Please feel free to resubmit if you make the above requested changes (and link to this original PR). Thank you!

**Comment by Belar** [comment]
Thanks for the review @matthewp.

OK, dependency injection, to leverage in tests, should do. 

Regarding the fix. The issue is not how `enabled` is being set, it’s how any config’s property is being read - “meaningful”, false(y) value (e.g. `false`) is treated as a “no value” and triggers a fallback for a default (e.g. for `enabled` it's `true`). Extra checks for `setEnabled` would keep the bug in place, a valid argument (`false`) is affected.

I would like to revisit the issue, resubmit a fix, but would be nice to first clarify the above. Could you give it another look?

**Pull request closed without merging**
