### PR TITLE
fix(lit): reactive property values not set

### PR DESCRIPTION
**Pull request by woutervroege**
## Changes
- Lit reactive property values were not in SSR mode. While the initial static render is correct, consecutive renders are incorrect because of this. See #3035 for more info.
- The proposed change makes sure every reactive property value is set using 'setAttribute'. This fixes the issue for all cases expect properties that explicitly have no attribute counterpart (`attribute: false`) in the static props config.

## Testing
- User tested (no automated tests)

## Docs
- Visible change.

### CODE REVIEW

**Comment by matthewp** [comment]
Looks like this breaks a test, mind checking as to why? @woutervroege

**Comment by woutervroege** [comment]
@matthewp I cannot find a proper test fix. The root cause of this failure is due to the face that some non-string values are used inside `instance.setAttribute`, which is expecting only `string` values further down the line (see `@lit-labs/ssr/lib/util.escape-html.js:19`).

**Comment by matthewp** [comment]
If the goal is to call setAttribute when there is also a property, why not move that line inside of the `if` and check if it is a string and set the attribute in that condition?

**Comment by woutervroege** [comment]
This wouldn't do it, as it would break object values to be bound as [object] instead of stringified json.

Another thing I tried is to stringify all attribute values but somehow this also didn't fix the issue.

I think we got to fix the root issue, which is why the lit-elements don't have proper initial state based on the 'setProperty' method.

**Comment by matthewp** [comment]
Ok, thanks for doing the research! As it doesn't sound like there's anything we can do on our end, going to close this PR.

**Comment by woutervroege** [comment]
@matthewp not sure yet, we'll have to confirm with the lit peeps whether it's some issue on their side

**Pull request closed without merging**
