### PR TITLE
Shiki config allow themes

### PR DESCRIPTION
**Pull request by duncanwerner**
## Changes

- What does this change?

Allows `themes` in ShikiConfig (syntax highlighter for MDX) #4245

- adds type in interface declaration
- adds validation type

## Testing

Tested against new & existing Astro projects

## Docs

This is a shiki twoslash feature, it's documented there. All this patch does is stop breaking it.

### CODE REVIEW

**Comment by natemoo-re** [comment]
Thanks for the PR @duncanwerner! I'll leave this for @bholmesdev since he has the most context here!

By the way, the CI failure is on our end, nothing you need to worry about.

**Comment by bholmesdev** [comment]
Thanks for the fix @duncanwerner! Admittedly, I'm not comfortable merging this PR _just_ yet, since the `themes` property will be ignored by regular Markdown. I will wait to merge until we migrate Markdown to use Shiki twoslash as well 👍

**Comment by duncanwerner** [comment]
I get that. It's annoying because I'll have to patch it or work around, but I see your point, no worries.

Heads up that if you are looking to unify on twoslash, it doesn't actually work at the moment -- Shiki works but the twoslash features don't. It's not an issue with Astro, it seems like twoslash and mdx just don't play well together. I assume you know that, because you're already including `rehype_raw`, but that doesn't solve the twoslash problem. I have a workaround but it's a bit hacky -- if I find something better I will post an issue.

**Comment by bholmesdev** [comment]
@duncanwerner We're aware and tracking here https://github.com/withastro/astro/issues/4258! I've tracked down the issue with a hotfix I'm testing right now

**Comment by matthewp** [comment]
@bholmesdev is this PR ready now given that #4258 is closed?

**Pull request closed without merging**
