### PR TITLE
Remove @astrojs/lit

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

This removes the Lit integration as an official integration. The reasons for doing so in 5.0:

- Only 1% of Astro users use this integration.
- SSR support in Lit is at a lower-level of support due to be a Labs project: https://lit.dev/docs/libraries/labs/, and has been in this state since we added support a couple of years ago.
- The maintenance cost of fixing bugs in this integration is too high given the low usage. Some PRs for upgrading Lit versions have taken quite a long time. We can't justify the core team being responsible for this going forward.
- There used to be community contributions to fix bugs but this has fallen off for various reasons.

Given that, this PR removes the integration as one that is officially supported by the Astro core team. Interested community members are encouraged to fork the integration and continue the development in another repository.

## Testing

- Tests removed

## Docs

- https://github.com/withastro/docs/pull/9065

### CODE REVIEW

**Comment by Princesseuh** [comment]
There's a hack here you might be able to remove too: https://github.com/withastro/astro/blob/64f81e92d1ddd325f7f80508eb88590814c070a8/packages/astro/src/runtime/server/render/component.ts#L288

**Comment by Princesseuh** [comment]
in packages/astro/src/runtime/server/render/component.ts there's also a mention of the integration for the error message

**Review by Princesseuh — APPROVED** [review]

**Review by ematipico — APPROVED** [review]

**Comment by JosefJezek** [comment]
Please don't remove Lit, this small lib has not alternative. SSR support is on the way.

FYI @justinfagnani

**Comment by kr05** [comment]
That's unfortunate, I have been actively using this integration for the past 2 years. Lit support was the main reason for choosing to try out Astro in the first place. Does that mean we won't be able to use lit with Astro 5?

**Comment by leo29plns** [comment]
I was drawn to Astro because of Lit and its philosophy, so it's a bit unfortunate to see Lit support phased out in Astro 5, though I understand the reasons behind it :/ Now, let's create some extremely exciting code with React (yes, irony ahah)

**Comment by Princesseuh** [comment]
Note that it's most definitely allowed and encouraged to fork the integration and continue using it in Astro 5, it should work just fine.

**Comment by metagrapher** [comment]
> ## Changes
> This removes the Lit integration as an official integration. The reasons for doing so in 5.0:
> 
> * Only 1% of Astro users use this integration.

You cannot know this for certain, your telemetry of usage can only see what is reported. 

The ratio of people who choose *not* to provide telemetry data, to those who do allow telemetry reporting, is probably quite high among the demographic of people who would use Lit instead of React, Svelte, or Vue, all of whom have privacy implications built in to them. A great number of EU users, and an increasing number of US users, are not keen on allowing Facebook a backdoor to their website just to compile React, for example.

Just as well, 1% of 100,000 users is 1000 users. 
That is 1000 web devs who you did _consider_, simply by virtue of having their needs on the roadmap at all, even if slow, and of whom you choose to no longer consider the needs because you have deemed them insignificant.

> * The maintenance cost of fixing bugs in this integration is too high given the low usage. Some PRs for upgrading Lit versions have taken quite a long time. We can't justify the core team being responsible for this going forward.

There is a community for these things, and you all used to operate as a nice open source stack community, but is that no longer happening?

> * There used to be community contributions to fix bugs but this has fallen off for various reasons.
> 

I'm guessing then is it time to fork the whole project, now that this has become official?

It seems that there are legitimate concerns that would go unaddressed without some dedicated people working on it--those people could be volunteers, or if there are companies who depend on the integration, they could put dev resources into maintaining the parts that suit them--, in the least the community could have been asked to support this before killing it, as is the tradition in open source software dev.

**Comment by kr05** [comment]
I think it's mainly the feeling of disappointment about yet another project that drops support for Lit. I've been a staunch Lit advocate for many years now and it always feels like we are swimming against the current. I really wish more people saw the value proposition Lit provides and that more people used it, but that's unfortunately not the case and I completely understand when projects don't want to dedicate resources for such a small user base. The only thing I will say is, that small user base greatly appreciates the work you have done to give Lit a home within Astro, and although it does hurt to lose official support, hopefully we can figure out a path forward to ensure Lit keeps its place within Astro.

**Comment by metagrapher** [comment]
> Anedoctally, from asking around and support threads, we've also found that people sometimes used the Lit integration only for the Lit part and not really the SSR, making the integration not useful (and actually making the components made with it worse, as they went through an unnecessary wrapper). In both cases however, you can still use Lit and Lit SSR directly without a dedicated integration, though for the latter it might be less ergonomic.
> 

I understand, and this makes sense. There's probably not that much benefit to the SSR integration, agreed. Since Lit is basically web components made ergonomic, I do think that it could still be seen as a baseline way to deal with client-side script without resorting to suggesting loading React or Vue, which do seem to somewhat undermine the whole point of Astro. So, this is a super pertinent point you make.

> We're sorry for the inconvenience, in a perfect world, we'd maintain everything.

I understand and appreciate that you've at least put a lot of thought and consideration into the decision. It probably isn't as inconvenient as I initially suspected, as you pointed out; and as @kr05 mentioned, it's probably mostly just the disappointment of yet another project dropping support for Lit.


🔭...At risk of tangenting into ticket-scope-creep....

I think it would be ideal that Lit be the de facto method of demonstrating islands and client side interaction in Astro, given its lightweight nature and that you don't need to know or understand React or Vue to get there. That adjustment might even have a complementary effect of making Astro more approachable generally, especially to people who don't prefer React. Then the use of Vue and React become dressing, and not default. As well, it would highlight the framework agnostic nature of Astro better than demoing React.

I'd note that a lot of UI libraries and templates for Astro are really just React and so don't take advantage of Astro very well, and still require me to load React into my project, and that's frustrating.

(I'm specifically using Astro because it is not React and Vue, and I don't often need to reach for Lit... but there are times when client-side interaction is necessary, so I find the tutorials referencing React to be cumbersome and prevalent. This is verging on a whole other issue. I'm happy to create a new ticket if this is not the place for this documentation discussion, but it felt relevant. 🙏🏼)

**Comment by matthewp** [comment]
I like and use Lit often. I never personally used it in Astro though. If I did I would be maintaining an integration for it. It's really not that difficult, just a small amount of code, and you already have the existing code to start from. The fact that there isn't one already is because no one is motivated enough to do the very small amount of work required. Such is life.

**Comment by marceloverdijk** [comment]
If it is really a very small amount of work, I don't understand why it was dropped...
Official integration always feels better than a community forked alternative.

**Comment by trusktr** [comment]
Anyone can submit an internation. See:

- https://astro.build/integrations/?categories%5B%5D=frameworks
- https://docs.astro.build/en/reference/publish-to-npm/#integrations-library

So all someone needs to do is copy the small amount of code and submit it as a separate package, along with some docs and tests, just like those other 3rd party integrations that get listed on Astro's official integration listing.

It isn't the end of the world. It's about people. **Who** will be maintaining the Lit integration next?

Maybe whoever will do it can even get the project blessed to live in Lit's GitHub org...

**Comment by trusktr** [comment]
About React/Vue/etc being a default over custom elements (cc @metagrapher), yeah that's just a dumb hype bubble, and shows how Astro isn't aligned with the Web Platform as much as we wish it was.

Custom Elements are only going to get better...

**Comment by jlukic** [comment]
https://github.com/withastro/astro/pull/13359

I've authored a PR for the Lit package that adds Astro 5 support for SSR. The maintainers have decided they do not want to include Lit it in Astro moving forward and suggest third party hosting. This is their prerogative as maintainers and I respect that. 

I'll be checking with the Lit team to see if they would like to host the package, otherwise I'll host under the @semantic-ui org. I should have something by the end of week the community can use.

**Comment by oddcelot** [comment]
nice @jlukic 
was going to take this on this week, so thanks a lot 🙏

**Comment by jlukic** [comment]
I've published a compatible Lit package for Astro 5. Please be sure to use `^5.1.0` as the `5.0.x` versions had some issues from disentangling astro's build pipeline.

```npm install @semantic-ui/astro-lit`

https://www.npmjs.com/package/@semantic-ui/astro-lit/

**Comment by krumware** [comment]
Thanks for the package @jlukic ! Switching to that resolved an issue for us with content collections.

Example of the error:
```
13:34:26 ▶ redacted/index.astro
13:34:26   └─ /redacted/index.htmlCannot read properties of undefined (reading 'length')
  Location:
    /redacted/node_modules/@lit-labs/ssr/lib/render-value.js:770:28
  Stack trace:
    at getLast (file:///redacted/node_modules/@lit-labs/ssr/lib/render-value.js:770:28)
    at renderTemplateResult.next (<anonymous>)
    at renderValue.next (<anonymous>)
    at renderTemplateResult.next (<anonymous>)
    at renderValue.next (<anonymous>)
```

Just adding the thought, we're observing resurging interest in web components, so hopefully Lit will get another look by the team. Otherwise, it would be helpful if the documentation https://docs.astro.build/en/guides/integrations-guide/lit/ can be updated to reference the above community project to help direct users to an effective alternative.

**Comment by jlukic** [comment]
Worth mentioning here, I am now on Astro 6 and [astro-lit](https://www.npmjs.com/package/@semantic-ui/astro-lit/) still works for Lit components.

**Pull request merged**
