### PR TITLE
feat: remove @astrojs/image completely

### PR DESCRIPTION
**Pull request by Princesseuh**
## Changes

What the title says

## Testing

Hey, I somehow made the CI faster!

## Docs

Will be part of the migration guide

### CODE REVIEW

**Comment by matthewp** [comment]
I assume the Node test failing is that it's using the image integration (didn't check). Probably I would just remove that test.

**Comment by Princesseuh** [comment]
> I assume the Node test failing is that it's using the image integration (didn't check). Probably I would just remove that test.

Hmm, it's actually in the `astro:assets` test, but I don't see how this PR is related

**Comment by matthewp** [comment]
You sure? It says its happening in `packages/integrations/node/test/image.test.js`

**Comment by matthewp** [comment]
I created a backup of this branch in case a merge/rebase failure occurs: https://github.com/withastro/astro/tree/feat/remove-astro-image-backup

**Review by natemoo-re — APPROVED** [review]

**Pull request merged**
