### PR TITLE
fix: _image endpoint returning a 404 for local images

### LINKED ISSUE #8735: _image endpoint returning a 404 for local images
### Astro Info

```block
Astro                    v3.2.2
Node                     v18.16.1
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/svelte
                         @storyblok/astro
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

After enabling the Vite Basic SSL plugin (@vitejs/plugin-basic-ssl) and serving my local dev on https my images that are stored within the `src` folder are returning a 404 when trying to load from the `_image` endpoint.

### What's the expected result?

The endpoint should return a 200 and the image should show.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-x9jtgg https://codesandbox.io/p/sandbox/condescending-mirzakhani-8qpy34  ------ I have added a stackblitz link that won't run dev and a codesandbox that will run dev but not connect! So I didn't know what to do. They both break because of the ssl plugin but the code is there

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #8735

### CODE REVIEW

**Review by ematipico — COMMENTED** [review]
Is it possible to add a test?

**Comment by rishi-raj-jain** [comment]
@ematipico 

I'll take a look at this later today, I am sure there must be a test for this already?

**Comment by Princesseuh** [comment]
Adding a test is a bit complicated because this specific issue happens for two reasons:
- Windows paths weren't handled properly
- which..
- made it use the fallback solution (using a fetch)
- which...
- failed because of a unusual setup (using https in dev with another Vite plugin)

**Comment by ematipico** [comment]
What's your suggestion here @Princesseuh ? Should manual testing be enough?

**Comment by Princesseuh** [comment]
> What's your suggestion here @Princesseuh ? Should manual testing be enough?

I'd say it's okay for now, it's a quite precise setup. We have a lot of tests using the endpoint, more general failures will be caught.

**Review by ematipico — APPROVED** [review]

**Review by Princesseuh — APPROVED** [review]

**Comment by rishi-raj-jain** [comment]
Awesome! Shall I update the branch or we're gonna proceed with merging?

**Comment by Princesseuh** [comment]
> Awesome! Shall I update the branch or we're gonna proceed with merging?

I'll merge it, thank you for your contribution!

**Comment by rishi-raj-jain** [comment]
My pleasure, on my way to fixing more of P3 bugs.

**Pull request merged**
