### PR TITLE
fix(cli): load polyfill before loading config during `astro add`

### PR DESCRIPTION
**Pull request by negativems**
I tried to import Vue Astro adapter and I got an error. The error is the next one:

image

And I tried to import any other adapter and I get the same error when using the Vercel serverless adapter.

After seeing the problem, I added the node crypto import into the Vercel adapter and the error gone:

image

Edit:

This is my astro.config.mjs

image

### CODE REVIEW

**Review by florian-lefebvre — COMMENTED** [review]
Must have been introduced with the edge middleware verification, good catch! Can you please add a changeset?

**Comment by ematipico** [comment]
This is weird, though, we have a polyfill for crypto: 

https://github.com/withastro/astro/blob/e24db1d8a683897d4c179f3511f8e38950884e7f/packages/astro/src/core/polyfill.ts#L6-L10

**Comment by ematipico** [comment]
@negativems, what's your local version of Node.js? What's the version of the runtime in Vercel?

**Comment by ematipico** [comment]
@negativems  can you try this version of the vercel adapter, and see if that fixes your issue?

`@astrojs/vercel@experimental--vercel-crypto-fix`

**Comment by lilnasy** [comment]
!preview node-crypto-error

**Review by lilnasy — APPROVED** [review]
Thanks for taking this on!

**Review by bluwy — APPROVED** [review]

**Review by bluwy — APPROVED** [review]

**Review by ematipico — APPROVED** [review]

**Pull request merged**
