### PR TITLE
fix(intergration defined middleware): prevent importing non-existent user middleware

### PR DESCRIPTION
**Pull request by lilnasy**
## Changes
- Fixes (partially) #9047
- Refactor middleware/vite-plugin to ignore userMiddleware when it doesnt exist.

## Testing
new fixture

## Docs
Doesn't affect usage

### CODE REVIEW

**Review by matthewp — APPROVED** [review]
Thanks!

**Review by MoustaphaDev — APPROVED** [review]
Nice refactor!

**Comment by lilnasy** [comment]
Do not merge until green.
The tests are not right, but the implementation seems correct.

**Review by ematipico — CHANGES_REQUESTED** [review]
The issue is at line 47. If the user doesn't have a middleware, we bail and we emit `export const onRequest = undefined`.

In case the user doesn't have a middleware, we have to create a new one from scratch and **not attempt** to import the one from the user.

This isn't the correct fix.

**Comment by lilnasy** [comment]
@ematipico could you take it from here?

**Comment by lilnasy** [comment]
!preview

**Comment by ematipico** [comment]
@lilnasy I opened a new PR https://github.com/withastro/astro/pull/9057

**Comment by lilnasy** [comment]
> and not attempt to import the one from the user

@ematipico In this PR, the one from the user **does not** get imported, notice the `.filter(Boolean)`. Were you under the impression that it did?

**Pull request closed without merging**
