### PR TITLE
fix: `--experimental-ssr` fixes

### PR DESCRIPTION
**Pull request by JuanM04**
## Changes

~~Replaced `--experimental-ssr` with the internal function `isBuildingToSSR`, which reads the brand-new `adapter` inside the Astro config.~~

- Use `isBuildingToSSR()` everywhere.
- `--experimental-ssr` flag now is required when using 3rd-party adapters.

This change has a side effect: it now respects the output given by the integrations through `buildConfig` and (somehow) doesn't copy the contents of `public/` into the dist folder. @matthewp maybe you can help me with this?

## Testing

TBD

## Docs

TBD

### CODE REVIEW

**Comment by matthewp** [comment]
Hm, so you're saying that `public/` works before this change with the flag but fails just by using this internal code instead? I'm not sure why that would be, you might need to debug it more. I believe Vite is the one doing the copying there, with the `publicDir` config, maybe that is being messed up some how?

**Comment by JuanM04** [comment]
Things were broken in a different way before - for example, now buildConfig is respected. The SSR tests that had both the adapter and `experimentalSsr: true` also failed this new test

**Comment by matthewp** [comment]
Oh, I just read the test. You are expecting to get the `public/` file by calling the adapter, but that test adapter doesn't implement static file serving. That would be a feature of the adapter, not a feature of our SSR implementation.

**Comment by matthewp** [comment]
Yeah, perhaps something about minimal is causing a bug then? I'm not sure.

Talked about this overall idea with the team and we want to make it so that the flag is still required if using a 3rd-party adapter, but not needed if using a built-in adapter. 

This mimics how integrations work, where the flag is needed if using a 3rd party one.

**Comment by JuanM04** [comment]
> we want to make it so that the flag is still required if using a 3rd-party adapter

Perfect, I could add that to `isBuildingToSSR`!

> Yeah, perhaps something about minimal is causing a bug then? I'm not sure.

After some searching, I think the issue is [here](https://github.com/withastro/astro/blob/52d7fec2480e3c8f3f046c229364a9c91cc06821/packages/astro/src/core/build/static-build.ts#L174-L176). When there is no JavaScript to be generated, the build process is omitted. This leads to sites with static assets (and probably some CSS) to not have its assets copied if there is no JS.

**Comment by matthewp** [comment]
> After some searching, I think the issue is [here](https://github.com/withastro/astro/blob/52d7fec2480e3c8f3f046c229364a9c91cc06821/packages/astro/src/core/build/static-build.ts#L174-L176). When there is no JavaScript to be generated, the build process is omitted. This leads to sites with static assets (and probably some CSS) to not have its assets copied if there is no JS.

Ah, yeah that does make sense. I think I can fix that in another PR.

**Comment by matthewp** [comment]
Here's how the integrations flag is implemented: https://github.com/withastro/astro/commit/9d6e0b5dbac1e5c31f580c6234e977a3a3a4918f

**Comment by matthewp** [comment]
Code looks good, maybe need to rebase with `main` to clear up the failing test?

**Comment by matthewp** [comment]
Great, thank you!

**Pull request merged**
