### PR TITLE
fix(middleware): emit warning if `next` is called and nothing is returned

### PR DESCRIPTION
**Pull request by ematipico**
## Changes

Closes https://github.com/withastro/astro/issues/7007

There was a small bug where just calling `next()` without returning anything led to some errors.

Our `next` function, internally, calls an `await` and that can lead to an error if the user **doesn't** await the `next` function.

I applied the following changes:
- added a warning in case the user does `next()` without returning anything;
- fixed this very case; now calling `next()` and returning anything **will throw an error**;
## Testing

I added a test case

## Docs

I removed from the examples:
- `api/`, middleware doesn't support endpoints that return `{ "body": "" }`
- the incorrect case that we want to prevent

### CODE REVIEW

**Comment by matthewp** [comment]
To be clear, it is still required that you return the value of `next()` (or your own Response), right? We are not making it work that you just call next() without returning anything?

**Comment by ematipico** [comment]
> To be clear, it is still required that you return the value of `next()` (or your own Response), right? We are not making it work that you just call next() without returning anything?

We will have to throw an Astro error instead of a warning, is that OK with you? (for now I made this case to work)

**Comment by ematipico** [comment]
I updated the PR. Now calling `next()` and returning anything will throw an error.

**Comment by matthewp** [comment]
@ematipico The error would be that they called `next` *after* the function completes, right? If so then that makes sense to me.

I think we should hold off on allowing this though, as it makes our code more complex and makes "how do you use next()" more difficult to explain. Good errors/warnings for now should help.

**Comment by ematipico** [comment]
> @ematipico The error would be that they called `next` _after_ the function completes, right? If so then that makes sense to me.

Yes, the error will be emitted at the end of the function.

**Pull request merged**
