### PR TITLE
Make `trailingSlash: 'always'` default

### PR DESCRIPTION
**Pull request by bluwy**
## Changes

- https://github.com/withastro/roadmap/discussions/983

There's a lot of work needed to update the test, but creating a stop gap here as something we could discuss before doing more work.

The reason for this change is highlighted in the roadmap link above. For static sites, this should not be a breaking change. For SSR sites, this will be a breaking change for on-demand pages which will now have a trailing slash by default. But you can revert to the previous behaviour for now if you want to not deal with this for now.

### CODE REVIEW

**Comment by bluwy** [comment]
Ignoring trailing slash has an impact on SEO and reducing potential duplicate work, so I don't think it's only an aesthetic preference. For example, Next and Nuxt have trailingslash as `false`/`'never'` by default. (AFAIA only sveltekit is ignore like us). We can't go with `trailingSlash: 'never'` like Next and Nuxt because we already have `build.format: 'directory'` by default, which will cause more conflicts (and `directory` feels like an Astro opinion to me too 😄)

I don't think the RFC discussion is only about `build.format: 'file'`, it's for both file and directory. You need them to match this way to prevent relative path issues:

| build.format        | trailingSlash    |
|---------------------|------------------|
| file                | never            |
| directory   | always           |

If you build your file to `dist/foo/index.html`, you cannot access it with `example.com/foo` (no trailing slash, which `'ignore'` by default allows).

**Comment by matthewp** [comment]
Going to take the discussion over to the RFC thread so that this can focus on code review.

**Review by matthewp — CHANGES_REQUESTED** [review]
blocked while the change is being debated

**Comment by bluwy** [comment]
The changes here are outdated

**Pull request closed without merging**
