### PR TITLE
fix(toolbar): add anchor element to interactive elements

### PR DESCRIPTION
**Pull request by ematipico**
## Changes

This PR adds `a` to the list of element that can be interactive.

Interactive elements are usually marked with the `"widget"` role. [`link`](https://www.w3.org/TR/wai-aria-1.1/#link) role is a `command` role, which is a superclass that includes `"widget"`.

## Testing

I am happy to add a test with some guidance 

## Docs

N/A

### CODE REVIEW

**Review by Princesseuh — APPROVED** [review]
LGTM, just needs a changeset! You can add a test in `e2e/dev-toolbar-audits.test.js` if you want to, but I'm totally okay with not having one right now. We can make a full test suite for audits later

**Comment by HiDeoo** [comment]
Following the discussion from earlier today, I opened #10346.

According to this [MDN reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#interactive_content), an anchor element is only considered interactive content if it has an `href` attribute:

> Some elements belong to this category only under specific conditions:
>
> `<a>`, if the `href` attribute is present
> `<audio>`, if the `controls` attribute is present
> ``, if the `usemap` attribute is present
> `<input>`, if the `type` attribute is not in the hidden state
> `<object>`, if the `usemap` attribute is present
> `<video>`, if the `controls` attribute is present

If my understanding is correct, the rule should check for the presence of the `href` attribute before considering the anchor element as interactive content (and same for the other elements with specific conditions). Any thoughts on this?

**Comment by Princesseuh** [comment]
> Following the discussion from earlier today, I opened #10346.
> 
> According to this [MDN reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#interactive_content), an anchor element is only considered interactive content if it has an `href` attribute:
> 
> > Some elements belong to this category only under specific conditions:
> > `<a>`, if the `href` attribute is present
> > `<audio>`, if the `controls` attribute is present
> > ``, if the `usemap` attribute is present
> > `<input>`, if the `type` attribute is not in the hidden state
> > `<object>`, if the `usemap` attribute is present
> > `<video>`, if the `controls` attribute is present
> 
> If my understanding is correct, the rules should check for the presence of the `href` attribute before considering the anchor element as interactive content (and same for the other elements with specific conditions). Any thoughts on this?

Ah yeah, the optimal solution would be to check in the `match` property. An helper could be made to make that easier to re-use.

**Comment by ematipico** [comment]
Changeset added. I suppose we can create the helper in another PR?

**Comment by Princesseuh** [comment]
> Changeset added. I suppose we can create the helper in another PR?

Well it's not just the helper, the behaviour in this PR is incorrect since a `a` is only interactable under conditions

**Comment by ematipico** [comment]
All right, I'll add the logic tomorrow

**Review by Princesseuh — APPROVED** [review]
Seems fine!

**Pull request merged**
