### PR TITLE
chore: added Git hooks

### PR DESCRIPTION
**Pull request by JuanM04**
## Changes

Added a Git hook ~~with Husky~~ that formats and lints the code when you commit.

### CODE REVIEW

**Comment by JuanM04** [comment]
@matthewp that's a good point. I've found that in SvelteKit they have an [opt-it hook](https://github.com/sveltejs/kit/blob/master/CONTRIBUTING.md#coding-style). The only counterpart is that it's not enabled, so we would still need the format workflow. What do you think?

**Comment by matthewp** [comment]
Want to let others weigh in.

**Comment by jasikpark** [comment]
Personally not a fan of git hooks - I can see having a totally opt-in setup being fine though

**Comment by JuanM04** [comment]
Ok, I've ditched Husky and added it as a opt-in hook

**Comment by FredKSchott** [comment]
I'd like to avoid adding this complexity and extra dependencies if we can help it. Like others here I'm personally -1 on git hooks, and am happy we have auto-formatter as a low-friction, invisible alternative.

I think the criteria to merge should be:
- needs to be opt-in (which I see you did here!)
- needs some meaningful number of monorepo PR-submitting maintainers asking for it (in Discord, in the RFC repo, etc).

**Comment by JuanM04** [comment]
Thank you everyone for your feedback! I'll close this PR since it seems unnecessary

**Pull request closed without merging**
