### PR TITLE
Split support in the Vercel Serverless adapter

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- This adds support for `build.split: true` in the Vercel adapter. Similar to cloudflare, a new function folder is created for each one.

## Testing

Manually testing.

## Docs

TBD

### CODE REVIEW

**Comment by matthewp** [comment]
!vercel-split

**Review by JuanM04 — COMMENTED** [review]
Hey, there! This change is quite nice, should bring high performance benefits. I'm quite out of touch with the codebase, but these changes seems ok. I don't know what `route.pattern.source` outputs, but make sure it's Vercel-complainant (they can be very tricky, I hate them).

**Comment by matthewp** [comment]
!preview vercel-split

**Comment by matthewp** [comment]
Tested with an example app and everything seems to be working.

**Review by natemoo-re — APPROVED** [review]
Code LGTM! Super excited for this!

**Pull request merged**
