### PR TITLE
chore(telemetry): Migrate tests to `node:test`

### PR DESCRIPTION
**Pull request by VoxelMC**
## Changes

- Migrates `chai` tests to `node:test` assertions
- Part of #9873 

> The original test command still runs mocha tests, and a new test command: `test:node` will run the node tests.
I have renamed the mocha tests to `*.mocha.test.js` and added node tests as `*.node.test.js`. An alternative to this might just be using different directories, which I can fix if needed
The above is no longer true. I have removed the progressive tests!

## Testing

Tests should pass! Twice!

## Docs

No docs added as this only affects testing.

### CODE REVIEW

**Comment by ematipico** [comment]
Thank you @VoxelMC !

Can you give us a bit of context, and explain why a test still needs to run via Mocha?

**Comment by VoxelMC** [comment]
> Thank you @VoxelMC !
> 
> Can you give us a bit of context, and explain why a test still needs to run via Mocha?

I added the mocha tests back to align with the notion of Progressively migrating the tests to `node:test`. Do these packages fall under that umbrella (RSS, this, etc.)?

**Comment by ematipico** [comment]
Yeah, the idea was to progressively migrate the tests of the `astro` package. But we can migrate all the tests of the other packages because they aren't that many, so it's doable.

Plus, with this PR you gave me a nice idea of how to progressively migrate `astro` tests!

**Comment by VoxelMC** [comment]
> Yeah, the idea was to progressively migrate the tests of the `astro` package. But we can migrate all the tests of the other packages because there aren't that many with one PR (per package), so it's doable.
> 
> Plus, with this PR you gave me a nice idea of how to progressively migrate `astro` tests!

Ah, I see it clearly now!
Okay, I will remove `mocha` tests from `telemetry` and then it should be ready to merge?

**Comment by VoxelMC** [comment]
Done!

**Review by bluwy — APPROVED** [review]

**Review by ematipico — APPROVED** [review]

**Pull request merged**
