### PR TITLE
make remark-rehype options available in astro config

### LINKED ISSUE #3163: 🐛 BUG: footnotes in markdown generate a <h2 id="footnote-label" class="sr-only">Footnotes</h2> that cannot be translated or removed
### What version of `astro` are you using?

1.0.0-beta.12

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Footnotes in Mardown are managed through remark-gfm. I got pretty confused looking at the chain of things happening during the transformation, but ultimately it will create a `<h2 id="footnote-label" class="sr-only">Footnotes</h2>` at the beginning of the section.

This is an issue for internationalization as we need to be able to (at least) translate this to the site's language, if not customize this html.

Remark-rehype takes an option for this: https://github.com/remarkjs/remark-rehype#optionsfootnotelabel

Note that the documentation mentions "Affects screen readers. Change it when the markdown is not in English."

But this is not reachable through the astro config file. It is possible to add this option right after this: https://github.com/withastro/astro/blob/becdf3e923df1cd604b9157a8d6c2d0bd0b9c24b/packages/markdown/remark/src/index.ts#L69 and customize this label. It looks like it wouldn't be too hard to add this in the markdown rendering options, but there might be some caveats here. Maybe all options offered by remark-rehype should be made available.

I am also wondering about the `sr-only` class here. Given what the documentation is saying, i am wondering if this title is specifically added for screen readers, and if it is expected that this would be hidden otherwise through css. I find it a bit obvious that this section contains footnotes and would rather do away with this title entirely. But I don't use a screen reader and it might very well be that it helps in this case.

I can try to write a PR for making the remark-rehype options available, but am not 100% sure what the general direction should be!

### Link to Minimal Reproducible Example

https://stackblitz.com/github/yqniarrrp?file=src/pages/index.md

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by gtnbssn**
I am scraping #3177 and starting from a clean branch here. Sorry if this is a bit messy i guess i am still learning!

## Changes

- Allows to set remark-rehype options in `astro.config.mjs`
- See options here https://github.com/remarkjs/remark-rehype#options
- Astro has `{allowDangerousHtml: true, passThrough: ["raw", "mdxTextExpression", "mdxJsxTextElement", "mdxJsxFlowElement"]}` by default, this keeps them and will extend the values with what goes in the `astro.config.mjs`
- This should allow to set other options, notably footerLabel to close #3163

## Testing

Add this in astro.config.mjs

```
markdown: {
  remarkRehype: {
    footnoteLabel : "other title for footnotes",
    footnoteBackLabel: 'other text for the link back to content',
  }
}
```

Create a markdown page with a least one footnote and change that the title for the footnotes section has been updated.

## Docs

I'll make a separate PR in the docs repo when this passes all tests.

### CODE REVIEW

**Comment by matthewp** [comment]
Sorry for not following up on this. Are you planning on getting this working? Going to close for now, can reopen if/when everything is passing.

**Comment by EiffelFly** [comment]
@gtnbssn Thanks for your work! This remark-rehype option can be very useful for my project, will you finish this feature? If you are not going to finish it, I am happy to pick it up!

**Comment by gtnbssn** [comment]
hey @EiffelFly ! I am still very interested in finishing this, but this week has been too busy for me to look into it deeply.

I could use some help though, i feel like i have been running around in circles around what looks like the remaining issue for this to me.

The only way i can make it pass the build at the moment is by changing this:

https://github.com/gtnbssn/astro/blob/75ca20b6303e677763b3ce183234d61873e7c986/packages/astro/src/core/config.ts#L1

to

```js
import type { RehypePlugin, RemarkPlugin } from '@astrojs/markdown-remark';
import type { Options as RermarkRehype } from 'mdast-util-to-hast';
```

This feels wrong to me because mdast-util-to-hast is a deeply nested dependency. (It is a dependency of remark-rehype, which is a dependency of @astrojs/markdown-remark, itself a dependency of Astro.) It exports its options type, which are imported and re-exported by remark-rehype, in turn my patch imports it in @astrojs/markdown-remark and re-exports it, and then imports it in astro in the line linked above.

In my IDE, tsserver sees the type properly, but it does tell me `The inferred type of 'AstroConfigSchema' cannot be named without a reference to '.pnpm/mdast-util-to-hast@12.1.2/node_modules/mdast-util-to-hast/lib'. This is likely not portable. A type annotation is necessary.` If i make a reference to mdast-util-to-hast in some astro code, i suppose it would be clean to add it to the dependencies, but it doesn't really make sense to do so. (Actually sounds like a bad idea.) @matthewp do you have an idea on this maybe?

I am doing this mostly because i want to get better at typescript, so there is a high (and infuriating) chance that i am just missing something very obvious. But i also see other people online having similar looking issues with deeply nested dependencies.

Anyway, if you want to talk about it we can meet in the Astro lounge on Discord next week. I'd be quite happy to finally get this to pass!

**Comment by EiffelFly** [comment]
@gtnbssn I think your concern is right, according to the @astro/core package, there has no dependency of `mdast-util-to-hast`, so it seems weird to me to pull some types from it. The better way will be pull the exported `mdast-util-to-hast` Option from the @astro/markdown-remark just as you did. 

After pulling your repo, I rollback your code to use.

```js
import type { RehypePlugin, RemarkPlugin, RemarkRehype } from '@astrojs/markdown-remark';
```

And my tsserver didn't complaint anything, the types look cool and the build works fine, although there is a failed test `Can set multiple` which seems not related to what you want to implement, you may need to rebase new code and try it out.

Anywhere, I think stick with `@astrojs/markdown-remark` is the correct way to go. You may need to check your local dependency or re-install them all to solve your problems!

And I am glad to meet up with you next week. we can schedule it!

**Comment by gtnbssn** [comment]
hey @EiffelFly thanks for taking the time to look into this!

I have tried to clean everything up and start from a new repo and am still getting the same error.

You mentionned you rolled back the code, what exactly did you do? The last commit that wasn't just merging the upstream was the one where i finally got rid of the reference to mdast-util-to-hast, so it was working before this. (Although i could swear it was working before i created my last pr!)

I have tried using different versions of node just in case, no luck.

I am in UTC+2 currently if you want to meet up!

**Comment by EiffelFly** [comment]
@gtnbssn I had pulled the forked repo you have been working on and encountered the same issue.

`The inferred type of 'AstroConfigSchema' cannot be named without a reference to '.pnpm/mdast-util-to-hast@12.1.2/node_modules/mdast-util-to-hast/lib'. This is likely not portable. A type annotation is necessary.`

After digging around, I had tried the following method.

- Change root .npmrc `node-linker=hoist`, this config will bring pnpm symlinking behavior back to npm and yarn's way. In short they lift all the package to the root node_modules without nested dependency. But this is the opposite of what Pnpm offered. After hoisting, the problem was gone. So I am suspecting we may encounter similar problem as this one.

https://github.com/microsoft/TypeScript/issues/42873

In summary, It will happen when we are using the combination of monorepo + Pnpm + Typescript. The root cause is still unknown.

- `astro` depends on `@astrojs/markdown-remark`
- `@astrojs/markdown-remark` depends on `remark-rehype`, and `remark-rehype` export Options type from `mdast-util-to-hast`
- For some reason, typescript can't find the `mdast-util-to-hast@12.1.2` Options types from `@astrojs/markdown-remark`

But what bother me a lot is that in `@astrojs/markdown-remark`, it imports unified for its Plugin type and export it as `RemarkPlugin`, if the reasoning is the same, why this won't cause above typescript inferred type issue?

I think we need some others help to solve this issue, all the solution I have on my have will drastically change the tsconfig. 

@matthewp Could you shed some light toward this issue? I think it will cause more harm when Astro is going to remove `shamefully-hoist=true` and setup fine-grained config. I suggest we combat this issue here. 

The next step may be

- Further test the root cause, but we need your hint
- If we could directly pull `mdast-util-to-hast` the problem will solve with non-perfect solution. But it seems partially wrong imo

**Comment by gtnbssn** [comment]
Wow, thank you so much for looking deeply into this @EiffelFly!

This is definitely a little bit over my head unfortunately... Let's see if the core team has a solution!

**Comment by gtnbssn** [comment]
@EiffelFly i am definitely more stubborn than i should be here, but i might have found a solution, or at least be a bit more on track.

Defining the RemarkRehype type like this works:

```typescript
export type RemarkRehype = Omit<RemarkRehypeOptions, 'handlers' | 'unknownHandler'>;
```
I think this would be because handlers and unknownHandler's types are exported from mdast-util-to-hast, but not from remark-rehype.

I could reopen a PR with this change, but am wondering if this is something that needs to be fixed upstream instead. After all we can pass handlers in the options.

Do you have an opinion on this? The unified maintainers are extremely reactive, so if this is indeed a good idea (and we can provide the relevant patch) this could be solved quickly on that side.

**Pull request closed without merging**
