### PR TITLE
Fix/scoped css does not apply to Picture

### LINKED ISSUE #6574: Scoped CSS does not apply to Picture
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

When using the `<Picture>` element from the `@astrojs/image` integration, the generated `<picture>` tag lacks a scope CSS class (e.g., `class="astro-AUKH742L"`). This prevents authors from targeting these tags with any CSS. The included example is generated from the Portfolio template replaces the main `` tag with a `<Picture>` component and then adds some text before it. It includes the CSS:

```css
.hero > :nth-last-child(-n+2) {
	border: 1px solid hotpink;
}
```

So the last 2 children of the `.hero` container should have a hotpink border. However, only the text above the `<picture>` element renders a border. This is because the `<picture>` is rendered as:

```html
<div class="astro-J7PV25F6">Some text</div>
<picture>
	<source type="image/avif" srcset="/_image?f=avif&amp;w=200&amp;h=258&amp;ar=0.7741935483870968&amp;href=%2Fassets%2Fportrait.jpg 200w,/_image?f=avif&amp;w=400&amp;h=517&amp;ar=0.7741935483870968&amp;href=%2Fassets%2Fportrait.jpg 400w" sizes="(max-width: 375px) 50vw, 75vw"><source type="image/webp" srcset="/_image?f=webp&amp;w=200&amp;h=258&amp;ar=0.7741935483870968&amp;href=%2Fassets%2Fportrait.jpg 200w,/_image?f=webp&amp;w=400&amp;h=517&amp;ar=0.7741935483870968&amp;href=%2Fassets%2Fportrait.jpg 400w" sizes="(max-width: 375px) 50vw, 75vw"><source type="image/jpeg" srcset="/_image?f=jpg&amp;w=200&amp;h=258&amp;ar=0.7741935483870968&amp;href=%2Fassets%2Fportrait.jpg 200w,/_image?f=jpg&amp;w=400&amp;h=517&amp;ar=0.7741935483870968&amp;href=%2Fassets%2Fportrait.jpg 400w" sizes="(max-width: 375px) 50vw, 75vw">
	<img src="/_image?f=jpg&amp;w=400&amp;h=517&amp;ar=0.7741935483870968&amp;href=%2Fassets%2Fportrait.jpg" loading="lazy" decoding="async" class="astro-J7PV25F6">
</picture>
```

Lack of a scoped CSS class on the `<picture>` tag prevents styling it. It is tempting to say "just style the `img` tag", however, that doesn't work for layout concerns. For example, if the `<picture>` element participates in a CSS grid layout, you can't do something like `justify-self: center;` on it -- such a rule must be applied to the containing `<picture>`, not the child ``.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kyjn1r?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by andremralves**
## Changes

fixes #6574

- Pass class attribute to the `<Picture />` component so the scope class is applied.
- I used className as the variable name to prevent any issue with the class keyword.

### Before
```html
<picture>
   <source type="image/avif" srcset="/_astro/mypicture_ZeFaVg.avif 400w,/_astro/mypicture_1Hh42H.avif 800w,/_astro/mypicture_Z2c6PSF.avif 1200w" sizes="(max-width: 375px) 50vw, 75vw">
   <source type="image/webp" srcset="/_astro/mypicture_1tYFrG.webp 400w,/_astro/mypicture_Z1Dfdnh.webp 800w,/_astro/mypicture_ZkvIfu.webp 1200w" sizes="(max-width: 375px) 50vw, 75vw">
   <source type="image/png" srcset="/_astro/mypicture_FXu5O.png 400w,/_astro/mypicture_Z2rgoJ9.png 800w,/_astro/mypicture_m3iDz.png 1200w" sizes="(max-width: 375px) 50vw, 75vw">
   <img alt="image" src="/_astro/mypicture_m3iDz.png" loading="lazy" decoding="async" class="astro-J7PV25F6">
</picture>
```

### After
```html
<picture class="astro-J7PV25F6">
   <source type="image/avif" srcset="/_astro/mypicture_ZeFaVg.avif 400w,/_astro/mypicture_1Hh42H.avif 800w,/_astro/mypicture_Z2c6PSF.avif 1200w" sizes="(max-width: 375px) 50vw, 75vw">
   <source type="image/webp" srcset="/_astro/mypicture_1tYFrG.webp 400w,/_astro/mypicture_Z1Dfdnh.webp 800w,/_astro/mypicture_ZkvIfu.webp 1200w" sizes="(max-width: 375px) 50vw, 75vw">
   <source type="image/png" srcset="/_astro/mypicture_FXu5O.png 400w,/_astro/mypicture_Z2rgoJ9.png 800w,/_astro/mypicture_m3iDz.png 1200w" sizes="(max-width: 375px) 50vw, 75vw">
   <img alt="image" src="/_astro/mypicture_m3iDz.png" loading="lazy" decoding="async" class="astro-J7PV25F6">
</picture>
```

## Testing

O think it's no necessary because the change is simple.

## Docs

No docs necessary.

### CODE REVIEW

**Comment by bluwy** [comment]
It was intentional that the class and other attributes are passed to the `img` only: https://github.com/withastro/astro/pull/5038

**Comment by andremralves** [comment]
> It was intentional that the class and other attributes are passed to the `img` only: #5038

I read the issue related to this PR and I think it rally makes sense. So the issue https://github.com/withastro/astro/issues/6574 shouldn't be considered an issue? I still think that it would be good to support the class attribute for `<picture />` given the arguments provided in the issue.

**Comment by bluwy** [comment]
I think the issue could use `.hero > :global(:nth-last-child(-n+2)) > img` instead so it's not a big issue. We also [document](https://docs.astro.build/en/guides/integrations-guide/image/#picture-) that additional HTML attributes are passed to the `img` tag. So I think the issue was mislabelled and it shouldn't be fixed.

**Comment by bluwy** [comment]
It is documented that the additional attributes (including scoped css via the `class` attribute) are passed to the inner `img` only: https://docs.astro.build/en/guides/integrations-guide/image/#picture-

> In addition to the component-specific properties, any valid HTML attribute for the `` included in the `<Picture />` component will be included in the built `.`

**Pull request closed without merging**
