### PR TITLE
Prevent server hang in MDX when code throws

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Closes https://github.com/withastro/astro/issues/4894

## Testing

Test added

## Docs

N/A, bug fix

### CODE REVIEW

**Comment by matthewp** [comment]
Apparently some tests are relying on this not throwing... checking it out.

**Comment by natemoo-re** [comment]
> Apparently some tests are relying on this not throwing... checking it out.

Multi-framework support for MDX relies on this not throwing. The `skipAstroJSXCheck` is supposed to keep any component from running through this rendering loop twice, but we still want to swallow the first error since it might just be a failed `check`.

**Comment by matthewp** [comment]
Ah interesting, that's helpful for me to investigate then.

**Comment by matthewp** [comment]
@natemoo-re is it ok for it to throw the second time around?

**Comment by matthewp** [comment]
@natemoo-re I changed it so that it doesn't throw the first time, but if it comes back around again and has already run it will throw the original error.

**Comment by natemoo-re** [comment]
> @natemoo-re I changed it so that it doesn't throw the first time, but if it comes back around again and has already run it will throw the original error.

I think this should work, yeah. Guess we'll find out 😅

**Comment by matthewp** [comment]
Hm, the current solution won't work. Rethinking things a bit...

**Comment by matthewp** [comment]
This is being reworked, will open a new PR when it is ready.

**Pull request closed without merging**
