### PR TITLE
feat(next): reference astro/client from astro/config

### PR DESCRIPTION
**Pull request by florian-lefebvre**
## Changes

- Reference astro/client from astro/config
- Swaps the order of our default tsconfig `include` to avoid overriding types

## Testing

Manually

## Docs

Changeset. I'll submit a docs PR if this one is merged

### CODE REVIEW

**Comment by bluwy** [comment]
Is this related to the `@ts-check` PR? it feels odd to add this in the config file.

**Comment by florian-lefebvre** [comment]
It's unrelated. It's the only file I found is in all our starters than can hold this reference (now that env.d.ts is optional)

**Comment by bluwy** [comment]
In that case, can you explain why we need this? Wouldn't there be other types errors if `astro sync` has not been run yet?

**Comment by florian-lefebvre** [comment]
The idea is to get the basic types (thing `import.meta.env`, `astro:action` `defineAction` etc) out of the box, without relying on codegen. That means that users creating a project will not wonder why most things are broken before running `dev` for example. It won't solve everything (eg. precise content types) but better than nothing. I made this PR after feedback from @delucis

**Comment by florian-lefebvre** [comment]
@Princesseuh suggests that we add this reference in `astro/config` instead. I think it's a great idea, wdyt? I don't think there's a case where you'd want to import `astro/config` without getting those basic types

**Comment by bluwy** [comment]
Fine by me if it works. I'm not sure if TypeScript works correctly if referenced this way.

**Comment by florian-lefebvre** [comment]
I know @Fryuni used to rely on that for inox tools, and i think there was a few gotchas. Do you mind reminding us what they are?

**Comment by Fryuni** [comment]
Adding references, directly or indirectly, on the Astro config only works if the config file is being analyzed by TS.

All on Inox Tools provide the virtual modules indirectly, just like the idea of having the reference in `astro/config`. It works fine for the templates, but users that use their own TSconfig probably won't have the types.

It requires on the following configs to work:
- `allowJs` must be `true` (not the default)
- `isolatedModules` must be `false` (the default)
- The config file must be included in the project (match an `include` rule and no `exclude`, the default works)

The TSconfig files shipped with Astro all works, but an empty one using TS defaults won't. A custom one maybe works.

**Comment by florian-lefebvre** [comment]
Interestingly, I had to swap the order of our default tsconfig `include` array, otherwise the new reference in `astro/config` would override the one from `.astro/types.d.ts`

**Review by bluwy — APPROVED** [review]

**Review by Princesseuh — APPROVED** [review]
Looks fine to me!

**Pull request merged**
