### PR TITLE
Fix preact compat support for libraries

### LINKED ISSUE #4093: 🐛 BUG: Using `preact/compat` with `solid-js` leads to "Cannot read properties of null (reading 'useRef')"
### What version of `astro` are you using?

1.0.0-rc.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

See linked stackblitz. Using `client:load` causes the solid-js adapter to mess with preact components. Using `client:only` makes the error go away.

I've also seen other variations of this issue, e.g. the react adapter sometimes messes with solid-js components. Will update this issue with more links (or create a new one) if I bump into that again.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bltmyz?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### LINKED ISSUE #4107: 🐛 BUG: react component + `client:load` fails with `preact/compat` but works fine with `@astrojs/react`
### What version of `astro` are you using?

1.0.0-rc.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows / Stackblitz

### Describe the Bug

I have a `ComboBox` component from `react-aria` that I'm trying to render with `client:load` using the `@astrojs/preact` adapter with `{ compat: true }`. It gives me the following error:
```
Unable to render ComboBox!

This component likely uses @astrojs/react, @astrojs/preact, @astrojs/vue
or @astrojs/svelte, but Astro encountered an error during server-side rendering.

Please ensure that ComboBox:
1. Does not unconditionally access browser-specific globals like `window` or `document`.
   If this is unavoidable, use the `client:only` hydration directive.
2. Does not conditionally return `null` or `undefined` when rendered on the server.
```

Using `client:load='preact'` works fine so I believe this is an SSR issue. However, I noticed that swapping out `preact({ compat: true })` with just `react()` makes it work with `client:load` again.

(I did also come across https://github.com/withastro/astro/issues/3306, but this is `react-aria` not `react-spectrum` (which is a styled wrapper around `react-aria`) so there is no CSS involved. This could be why it works fine on server with `react()`.)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xkptsr?file=src%2Fpages%2Findex.astro,astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bluwy**
## Changes

Fix #4093
Fix #4107

- `compat: true` now `noExternal`-ize all react entrypoints so Vite can process and alias them to preact compat
- Bump to Vite `^3.0.5` to bring in a fix from https://github.com/vitejs/vite/pull/9554

## Testing

Added `preact-compat-component` test fixture to `astro/test`, and a sub package `@test/react-lib` to emulate a React library to be using `preact/compat` instead.

## Docs

N/A

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks @bluwy! We do want to continue to pin vite versions for a little while, so no `^`.

Also needs a changeset.

**Comment by bluwy** [comment]
My bad. Added changesets and pinned Vite to 3.0.5

**Review by matthewp — CHANGES_REQUESTED** [review]
We're holding off on merging new PRs as 1.0 is coming out. Will approve after that is out and we're ready for merges again.

**Review by natemoo-re — APPROVED** [review]

**Review by matthewp — APPROVED** [review]
Good to merge now, thanks!

**Pull request merged**
