### PR TITLE
feat: add support to `@astrojs/cloudflare` directory deploy mode

### PR DESCRIPTION
**Pull request by nrgnrg**
## Changes

Cloudflare Pages has 2 different ways of deploying a worker, the default mode which looks for a `functions` folder in the project root and an `advanced` mode which uses a `_worker.js` in the `dist` directory.

Different frameworks have opted for different approaches: Sveltkit targets advanced mode where as SolidStart and Qwik both target the functions directory.

Advanced mode provides a more consistant experience for users since the entire project gets built into the `dist` folder which is familiar. However the limitation of this is that pages plugins can't be used. As I see it a major use case for pages plugins is for enabling things like [Sentry](https://developers.cloudflare.com/pages/platform/functions/plugins/sentry/), especially in the absence of any logs on the pages platform right now.

This change adds an option to the adaptor to enable uses to change the default `advanced` deploy mode to the functions folder model which would allow the use of pages plugins and middleware. This mode creates a new functions folder in the project root where users can add plugins.

## Docs

Updated readme

### CODE REVIEW

**Comment by nrgnrg** [comment]
@natemoo-re @tony-sull

**Review by matthewp — APPROVED** [review]
This looks great, thanks!

**Comment by matthewp** [comment]
@nrgnrg sorry for the late review. Would you mind rebasing with main? We can then get this in.

**Comment by isaac-mcfadyen** [comment]
Very happy to see this change: I was actually just discussing the merits of `[[path]].ts` vs `_worker.js` the other day and this is one of the things that came up.

**Review by natemoo-re — APPROVED** [review]
LGTM once tests are passing!

**Pull request merged**
