### PR TITLE
fix: better dev routing with base using middleware

### PR DESCRIPTION
**Pull request by AllanChain**
## Changes

Use a base middle for better base handling in dev.

The previous dev routing design is not very friendly with a base path: it has to prioritize the custom 404 page over redirecting to public files, causing some problems:

- False 404 logged and custom 404 returned instead of public files #3808
- `http://localhost:3000/blog/blog/blog/blog/` will redirect to `http://localhost:3000/blog/`

Here I'm using the middleware approach inspired by Vite: return 404, or strip the base path and continue. In other words, the logic for returning 404 based on the base path is moved into the middleware. Thus the public files are correctly handled by the static serving middleware without the need to redirect.

However, just like Vite and the previous approach, requests for public files not starting with the base path are not responded to with 404.

## Testing

Added some tests.

Tested with my real project with base path and custom 404 enabled.

## Docs

No need.

### CODE REVIEW

**Review by natemoo-re — COMMENTED** [review]
This makes a lot of sense to me, thanks for the PR!

Hoping somebody more familiar with this original logic can review as well.

**Comment by matthewp** [comment]
Can you provide some examples of some URLs and how they would previous resolve and how they will resolve now? That would help understand what you have changed here.

> http://localhost:3000/blog/blog/blog/blog/ will redirect to http://localhost:3000/blog/

Why? It seems like `http://localhost:3000/blog/blog/blog/blog/` should be a 404 if there isn't a `blog/blog/blog/blog.astro` file.

**Review by tony-sull — APPROVED** [review]
Very nice, glad to see that redirect hack go away! 🎉 

Thanks for filing this PR and including clean test coverage for it!

**Comment by AllanChain** [comment]
> Why? It seems like `http://localhost:3000/blog/blog/blog/blog/` should be a 404 if there isn't a `blog/blog/blog/blog.astro` file.

If you look at the code here:

https://github.com/withastro/astro/blob/40a45e3ef6284c024d442cf7cb8e36d8354a35d1/packages/astro/src/vite-plugin-astro-server/index.ts#L124-L140

`/blog/blog/blog/blog/` starts with the base `/blog/`, so `redirectTo` has the value `/blog/blog/blog/`, so the browser will request `/blog/blog/blog/`. Then `/blog/blog/blog/` becomes `/blog/blog/`, and so on.

> Can you provide some examples of some URLs and how they would previous resolve and how they will resolve now? That would help understand what you have changed here.

**Example 1:** `http://localhost:3000/blog/blog/blog/blog/`
- __Previous:__ redirect to `http://localhost:3000/blog/`
- __Here:__ return 404

**Example 2:** `http://localhost:3000/blog/image.png` (`image.png` exists)
- __Previous:__
  - without `404.astro`: redirect to `http://localhost:3000/image.png`
  - with `404.astro`: return custom 404 page
- __Here:__ returns the image

**Example 3:** `http://localhost:3000/blog/image.png` (`image.png` not exists)
- __Previous:__
  - without `404.astro`: redirect to `http://localhost:3000/image.png` and 404
  - with `404.astro`: return custom 404 page
- __Here:__ custom for default 404 page

**Comment by natemoo-re** [comment]
Thanks @AllanChain, those specific cases seem much better in this PR! Really appreciate the contribution.

**Pull request merged**
