### PR TITLE
Fix: ignore common dev-tool configs while initializing astro

### LINKED ISSUE #3538: 🐛 BUG: Ignore hidden files/folders with create-astro
### What version of `astro` are you using?

1.0.0-beta.41

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When running `create-astro` inside an cloned empty git repo, I get a CLI error that `.` is not empty (it sees the .git folder)
Screen Shot 2022-06-06 at 3 11 38 PM

### Link to Minimal Reproducible Example

na

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by G3root**
## Changes

fixes #3538

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks @G3root but it looks like this is causing tests to break. Have any idea why?

**Comment by G3root** [comment]
> Thanks @G3root but it looks like this is causing tests to break. Have any idea why?

no idea why the test is not passing 🤔

**Comment by matthewp** [comment]
I bet if you ran the test locally you'd be able to figure it out.

**Comment by matthewp** [comment]
Going to close as its been a while. Please feel free to reopen if you get the tests fixed.

**Pull request closed without merging**
