### PR TITLE
fix: improve error for inferSize and Image component

### LINKED ISSUE #11821: getImage and Image return Failed to parse URL from when inferSize is set to true
### Astro Info

```block
BUN:

Astro                    v4.14.0
Node                     v22.6.0
System                   Linux (x64)
Package Manager          bun
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             astro-expressive-code
                         @astrojs/mdx
                         @astrojs/sitemap
                         unocss
which: no xclip in (....)

Nodejs:

Astro                    v4.14.0
Node                     v22.6.0
System                   Linux (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             astro-expressive-code
                         @astrojs/mdx
                         @astrojs/sitemap
                         unocss

which: no xclip in (....)
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

getImage and Image return `Failed to parse URL from ...` when `inferSize` is set to `true`

```
{
  "input": "/images/bar.jpg",
  "code": "ERR_INVALID_URL"
}
```
```
// This error
<Image src="/images/bar.jpg" alt={p.data.title} width={800} inferSize={true} />

// but this is work
<img src="/images/bar.jpg" />

// this also work
<Image src="/images/bar.jpg" alt={p.data.title} width={800} height={100} />
```

this happen when both when image is loaded from `public/` or from `src/`.

An typeError also happend when pass the image from collection to <Image src={post.data.cover}
```
import { defineCollection, z } from "astro:content";

const blogCollection = defineCollection({
  schema: ({ image }) => z.object({
    title: z.string(),
    cover: image().refine((img) => img.width >= 1080, {
      message: "Cover image must be at least 1080 pixels wide!",
    }),
    coverAlt: z.string(),
  }),
});

export const collections = {
  blog: blogCollection,
};
```

### What's the expected result?

Image is loaded without an error

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-cxn7kx

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by DerTimonius**
## Changes

This PR improves the error message a user will see when using `inferSize` in the `Image` component when the image is hosted locally instead of remote.

The original error message described in the issue (#11821) did not come from Astro, but from `fetch`. Therefore I figured that the check if the image is a remote image or not was incorrect. 

So I added the check for `isRemotePath` which now triggers the correct error.

## Testing

I tested this locally by changing an `` in the examples/portfolio `about.astro` page to the `<Image>` and added `inferSize`. After the change, the error was the expected error.

## Docs

No change to the docs needed

closes #11821

### CODE REVIEW

**Comment by Princesseuh** [comment]
Hmm, I'm not sure about this. This function is used for other things than just checking for http paths. I assume that adding this check makes it so it report that width and height are needed?

**Comment by DerTimonius** [comment]
@Princesseuh no, the check is for showing the user the correct error when `inferSize` is being used on a local image. the original error shown in the issue did not come from Astro, but was bubbled up by `fetch` as it's not provided a valid URL.

if I understand the code correctly, the check that triggers the fetch call is this:
image

so if you think that the check should not be in the `isRemoteImage` function, I would move it to this if block instead

**Comment by Princesseuh** [comment]
Yes, I understand the goal. However the `isRemoteImage` function is used in other parts of the code than just this specific check. What your change does is invisibly ignore `inferSize` when the image is not an actual URL, but I think it'd produce a better experience if we instead had an error that would tell the user explicitly that `inferSize` cannot be used with images in`public`

**Comment by DerTimonius** [comment]
I have checked if the desired error (which I guess is the one in the screenshot) is displayed with this change by adapting one of the examples (a good place would be the about page in the portfolio example)

image

this is the code that triggered this error: 
image

**Comment by DerTimonius** [comment]
@Princesseuh I moved the check for `isRemotePath` to where I think it should fit if it should not be added to the `isRemoteImage` check. Would this meet your expectations or should I create a new error?

**Comment by Princesseuh** [comment]
I think this is better! Ultimately, we'd probably want it done completely differently, but that's something to think through outside of this PR. Thank you!

**Review by Princesseuh — APPROVED** [review]

**Pull request merged**
