### PR TITLE
make Remark rehype options available in astro config

### LINKED ISSUE #3163: 🐛 BUG: footnotes in markdown generate a <h2 id="footnote-label" class="sr-only">Footnotes</h2> that cannot be translated or removed
### What version of `astro` are you using?

1.0.0-beta.12

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Footnotes in Mardown are managed through remark-gfm. I got pretty confused looking at the chain of things happening during the transformation, but ultimately it will create a `<h2 id="footnote-label" class="sr-only">Footnotes</h2>` at the beginning of the section.

This is an issue for internationalization as we need to be able to (at least) translate this to the site's language, if not customize this html.

Remark-rehype takes an option for this: https://github.com/remarkjs/remark-rehype#optionsfootnotelabel

Note that the documentation mentions "Affects screen readers. Change it when the markdown is not in English."

But this is not reachable through the astro config file. It is possible to add this option right after this: https://github.com/withastro/astro/blob/becdf3e923df1cd604b9157a8d6c2d0bd0b9c24b/packages/markdown/remark/src/index.ts#L69 and customize this label. It looks like it wouldn't be too hard to add this in the markdown rendering options, but there might be some caveats here. Maybe all options offered by remark-rehype should be made available.

I am also wondering about the `sr-only` class here. Given what the documentation is saying, i am wondering if this title is specifically added for screen readers, and if it is expected that this would be hidden otherwise through css. I find it a bit obvious that this section contains footnotes and would rather do away with this title entirely. But I don't use a screen reader and it might very well be that it helps in this case.

I can try to write a PR for making the remark-rehype options available, but am not 100% sure what the general direction should be!

### Link to Minimal Reproducible Example

https://stackblitz.com/github/yqniarrrp?file=src/pages/index.md

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by gtnbssn**
## Changes

- Allows to set remark-rehype options in astro.config.mjs
- See options here https://github.com/remarkjs/remark-rehype#options
- Astro has {allowDangerousHtml: true, passThrough: ["raw", "mdxTextExpression", "mdxJsxTextElement", "mdxJsxFlowElement"]} by default, this keeps them and will extend the values with what goes in the astro.config.mjs
- This should allow to set other options, notably footerLabel to close #3163

## Testing

Add this in astro.config.mjs

```
markdown: {
  remarkRehype: {
    footnoteLabel : "other title for footnotes",
    footnoteBackLabel: 'other text for the link back to content',
  }
}
```

Create a markdown page with a least one footnote and check that the title for the footnotes section has been updated.

## Docs

I'll update (if necessary) and reopen [docs#445](https://github.com/withastro/docs/pull/445) if this passes.

### CODE REVIEW

**Comment by gtnbssn** [comment]
@EiffelFly i think this is it! I had to explicitly import the types for handlers and add them back in the RemarkRehype type.

I don't think the failing tests are related to this patch so hopefully this is ok.

**Comment by bholmesdev** [comment]
Making a note to pull this from the MDX integration! I'll make a separate PR for that when this is merged 👍

**Comment by backflip** [comment]
@bholmesdev, should this work with MDX already? The following config does not overwrite the title for me when using `.mdx` files:
```js
export default defineConfig({
  integrations: [
    mdx(),
  ],
  markdown: {
    remarkRehype: {
      footnoteLabel: "Hi Ben",
    },
  },
});
```

`@astro/mdx@0.11.6`

**Comment by bholmesdev** [comment]
@backflip Ah, right you are! I agree this should be applied [when `extendPlugins: 'markdown'` is set in your MDX config](https://docs.astro.build/en/guides/integrations-guide/mdx/#extendplugins) (which is the default). We'd likely apply [the `remark-rehype` plugin](https://github.com/remarkjs/remark-rehype#options) alongside your other remark plugins if this option is set. If you want to make a PR, I'm happy to review 😁

**Pull request merged**
