### PR TITLE
new readme

### PR DESCRIPTION
**Pull request by FredKSchott**
## Changes

- Like the title says, new readme!
- Please leave feedback, any and all comments welcome.
- [Rendered monorepo README](https://github.com/withastro/astro/blob/new-readme/README.md)
- [Rendered astro package README](https://github.com/withastro/astro/blob/new-readme/packages/astro/README.md)

### CODE REVIEW

**Comment by JuanM04** [comment]
As an optional suggestion, the banner in the monorepo README could be theme-sensitive: we could have one for dark theme and one for light theme

```html
<p align="center">
  <a href="https://astro.build" target="_blank" rel="noopener noreferrer">
    <img src="assets/social/banner-minimal-light.png#gh-light-mode-only" alt="Astro logo">
    <img src="assets/social/banner-minimal-dark.png#gh-dark-mode-only" alt="Astro logo">
  </a>
</p>
```

**Comment by FredKSchott** [comment]
Ugh i wanted that SO BAD, but I couldn’t get it to work with an img tag, even though the docs said it should work. If you can get it working in a fork of this branch, I’d happily merge that commit into this PR.

you can use the dark/light logo svgs  that we already have in assets

**Comment by JuanM04** [comment]
@FredKSchott I've made it work [here](https://github.com/withastro/astro/tree/new-readme-plus) with a weird hack

**Comment by FredKSchott** [comment]
Nice!!! @JuanM04 great catch, so it sounds like the anchor tag was the problem? I actually went ahead and removed that tag, and it looks like it now works without the hack (we link to the astro homepage in the text below, so that should be fine).

Thanks for solving! Looks so much better now, imo

**Comment by delucis** [comment]
Just to double check, does the `#gh-light/dark-mode-only` trick work elsewhere that READMEs appear (npm I’m thinking of mainly)? Or do they render both? The other option would be an SVG file containing media queries.

**Comment by FredKSchott** [comment]
Confirmed! We use it on the netlify logo in our readme today: https://www.npmjs.com/package/astro

**Review by matthewp — APPROVED** [review]

**Pull request merged**
