### PR TITLE
feat: noSync flag for astro check

### PR DESCRIPTION
**Pull request by Princesseuh**
## Changes

There's some niche cases where you want to run `astro check`, but don't want to run the type gen step first. This is especially relevant in complex mono repos where some packages have Astro components, but are not Astro projects

## Testing

Tested manually

## Docs

https://github.com/withastro/docs/pull/8838

### CODE REVIEW

**Review by sarah11918 — APPROVED** [review]
Fantastic docs, @Princesseuh 🫡

**Review by florian-lefebvre — APPROVED** [review]

**Comment by Princesseuh** [comment]
!preview noSync

**Review by ematipico — COMMENTED** [review]
Usually flags aren't camelCase, so I think this should be named `--no-sync`

**Comment by Princesseuh** [comment]
> Usually flags aren't camelCase, so I think this should be named `--no-sync`

all the flags of astro check are camel cased

**Review by ematipico — APPROVED** [review]

**Pull request merged**
