### PR TITLE
[WIP] Remove `--parallel` from `astro` test

### PR DESCRIPTION
**Pull request by jonathantneal**
## Changes

- Removes `--parallel` from `astro` test
- No code changes.

## Testing

scripting change only

## Docs

scripting change only

### CODE REVIEW

**Comment by boehs** [comment]
What does this fix?

**Comment by jonathantneal** [comment]
Hey @boehs, see Fred’s suggestion here. I think I would summarize it wrong, because I’m not as up to speed on `--parallel`.
https://github.com/withastro/astro/pull/2446#issuecomment-1020305941

In Discord, Matt added:
> I’d be curious to see the difference in how long the tests take. If it's not much difference then sure.

I’m waiting for the differences to show:
| before | after |
| --- | --- |
| https://github.com/withastro/astro/actions/runs/1745969758 | https://github.com/withastro/astro/actions/runs/1746111358 |

**Comment by FredKSchott** [comment]
yeesh! It looks like its going on 20+ minutes? But its also not actually creating output, so maybe its hung somehow?

Either way, I don't feel too strongly about this if its blocked by some necessary time-consuming CI triage. Happy to see closed if that makes sense!

**Comment by FredKSchott** [comment]
It seems to be hanging. As the original champion of this proposal, I formally rescind it :)

**Pull request closed without merging**
