### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vaynevayne**
fix import React issue

## Changes

- What does this change?
- Be short and concise. Bullet points can help!
- Before/after screenshots can help as well.
- Don't forget a changeset! `pnpm exec changeset`

### CODE REVIEW

**Comment by bluwy** [comment]
The overrides is intentional to handle `react` and `react-dom` used in deps.

**Comment by vaynevayne** [comment]
> The overrides is intentional to handle `react` and `react-dom` used in deps.

Override doesn't work in pnpm. You have to do it my way.

**Comment by bluwy** [comment]
it's a different field in pnpm: https://pnpm.io/package_json#pnpmoverrides

**Comment by vaynevayne** [comment]
I guess you haven't tested it, and you haven't checked the disacard problem.

it works well
https://github.com/preactjs/preact/issues/3983

**Comment by bluwy** [comment]
I did test it myself and wrote that docs, with pnpm specifically

**Pull request closed without merging**
