### PR TITLE
Run all smoke tests with the static build

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Test change only

## Testing

All of the examples that are smoke tested are also run with `--experimental-static-build flag.

## Docs

Test only

### CODE REVIEW

**Comment by natemoo-re** [comment]
This is the same bug tripping me up in https://github.com/withastro/astro/runs/5252193656. Seems like the `astro.build` site is using a relative path or `Astro.resolve` or something?

**Comment by matthewp** [comment]
This PR isn't expected to pass until astro.build converts to the static build.

**Comment by natemoo-re** [comment]
Static build support merged in https://github.com/withastro/astro.build/pull/29

**Review by FredKSchott — CHANGES_REQUESTED** [review]
Since `--experimental-static-build` changes behavior, we should probably move this flag into the package.json of each example. ie:

```diff
-    "build": "astro build",
+    "build": "astro build --experimental-static-build",
```

These get run directly by users via astro.new, so I'd be worried about them passing CI but failing when users actually go to run them. If the package.json were updated instead, our CI can trust that `yarn build` does the right thing for each project.

**Comment by matthewp** [comment]
I don't think we should opt users into an experimental flag on all new projects. The goal of this PR is to ensure that the the experimental flag works on all of the examples. This runs both builds, so we know that both work with `yarn build`, and users are getting the stable version on new projects.

**Review by FredKSchott — APPROVED** [review]
Ah, got it. Makes sense!

**Pull request merged**
