### PR TITLE
Add Astro Blog RSS feed

### LINKED ISSUE #1009: 📘 DOC: Add RSS feed to blog
It would be awesome to add an RSS feed to the Astro blog so that we can follow along using feed readers.

### PR DESCRIPTION
**Pull request by rbardini**
## Changes

Generate a RSS feed for Astro Blog posts, and add an alternate link to the `<head>` for discoverability.

## Testing

Build and serve locally, then check `/rss.xml`.

Or check deploy preview feed: https://deploy-preview-2301--astro-www.netlify.app/rss.xml

## Docs

No documentation updates, blog changes only.

Closes #1009.

### CODE REVIEW

**Comment by FredKSchott** [comment]
I thought that we couldn't enable this originally because it required a final `site` URL to be configured. Is that not the case / does this build without issue?

**Comment by jonathantneal** [comment]
Neat! Yea, it does work.

FWIW, the `sitemap.xml` can also be seen in the preview @ https://deploy-preview-2301--astro-docs-2.netlify.app/sitemap.xml

**Comment by rbardini** [comment]
Yes, it builds fine. I don't think configuration is an issue, since `site` is defined here:

https://github.com/withastro/astro/blob/main/www/astro.config.mjs#L13

and used as base here:

https://github.com/withastro/astro/blob/main/packages/astro/src/core/ssr/rss.ts#L47

I did have to prepend a `blog/` path to every RSS item link though, as I couldn't find a better way—I tried `Astro.resolve`, but it's not exactly what I needed. I'm open to suggestions 🙂

**Comment by jonathantneal** [comment]
This is great. I think we can merge this in now. Thanks, @rbardini!

**Pull request merged**
