### PR TITLE
Adds support base64 encoding in Netlify Functions

### LINKED ISSUE #3586: 🐛 BUG: `@astrojs/netlify/functions` doesn't support base64 encoded responses
### What version of `astro` are you using?

1.0.0-beta.44

### Are you using an SSR adapter? If so, which one?

Netlify

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Netlify Functions requires that the function's `body` is a string.  To support certain use cases like returning a `Buffer` for an image, the response needs to be base64 encoded and include the [`isBase64Encoded`](https://docs.netlify.com/functions/build-with-javascript/#synchronous-function-format) flag

`@astrojs/netlify/functions` currently only supports text responses and doesn't have a way to use the `isBase64Encoded` flag

### Possible Solutions

This is a tricky one since API endpoints only return a standard `Response` object.  For Netlify, it could potentially check if `response.body` is a string, and if not assume it needs to be base64 encoded

Another option would be adding a custom header in the endpoint `Response`, but that could be a little weird since it really is adapter specific

### Link to Minimal Reproducible Example

na

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by tony-sull**
## Changes

Closes #3586 

This updates the `@astrojs/netlify/functions` adapter to check if response body is a base64 encoded string.  This is needed to make sure the `isBase64Encoded` flag is returned if necessary

Because Astro's API endpoints are expected to return a standard `Response` object, the adapter doesn't have access to the raw `BodyInit` object that was used.  The solution here is to encode the response body in the API endpoint, allowing the adapter to check whether `response.text()` is a base64 string.

## Testing

Added a test suite to verify that base64 responses are returned as expected

## Docs

N/A

### CODE REVIEW

**Comment by matthewp** [comment]
Is the use-case about images here? I'm worried about this regular expression and applying it to every request. I'm thinking that it shouldn't be on the developer to base64 encode their images, but rather just include the right Content-Type. And then the adapter could be the one to apply the base64 encoding.

It's a matter of the base64 encoding being an implementation detail of the adapter and not something the application should need to concern itself with.

Also consider cases where you base64 something and *want* it to be delivered as a string (using text/plain). Just feels like using the mimetype here is a better approach. Happy to discuss.

**Review by natemoo-re — APPROVED** [review]
LGTM! Nice fix.

**Review by natemoo-re — COMMENTED** [review]
I initially approved this but on second-thought I agree with @matthewp's suggestion that we should handle this invisibly if at all possible.

**Comment by tony-sull** [comment]
Synced with Matthew offline and think we landed on a better approach that avoids the rather nasty regex :+1:

Updated PR to follow!

**Review by bholmesdev — COMMENTED** [review]
Needs changeset but LGTM!

**Comment by tony-sull** [comment]
@matthewp This one's ready for another review with the non-regex solution we talked about yesterday :+1:

**Review by matthewp — APPROVED** [review]
lgtm

**Review by bholmesdev — APPROVED** [review]
`base`ically perfect 👏

**Pull request merged**
