### PR TITLE
feat: update `astro add vercel`

### PR DESCRIPTION
**Pull request by ematipico**
## Changes

This PR is follow-up of https://github.com/withastro/adapters/pull/424

## Testing

CI should pass

## Docs

N/A

### CODE REVIEW

**Review by florian-lefebvre — APPROVED** [review]

**Comment by florian-lefebvre** [comment]
Actually, what happens if someone adds the vercel adapter and specify a specific version <= 8.0?

**Comment by Princesseuh** [comment]
> Actually, what happens if someone adds the vercel adapter and specify a specific version <= 8.0?

it wouldn't work, but this is on next, so anyway installing an old version would result in a broken build

**Review by Princesseuh — APPROVED** [review]

**Comment by phenomen** [comment]
I changed import in `astro.config.mjs` from `@astrojs/vercel/serverless` to `@astrojs/vercel` and now I get this error on build:

> [AdapterSupportOutputMismatch] The `@astrojs/vercel` adapter is configured to output a static website, but the project contains server-rendered pages. Please install and configure the appropriate server adapter for your final deployment.

```
"@astrojs/vercel": "8.0.0-beta.3",
"astro": "5.0.0-beta.6",
```

**Comment by ematipico** [comment]
@phenomen please open an issue, create a reproduction so we can look after your issue. Please don't comment on closed issues/PRs because they don't get enough visibility

**Pull request merged**
