### PR TITLE
.md only: npm init astro --> npm create astro

### PR DESCRIPTION
**Pull request by mrienstra**
## Changes

For consistency with https://github.com/withastro/docs/pull/360. Docs always use `npm create astro` (never `npm init astro`), README.md files in this repo should do the same.

Search:
`\b(npm|yarn|pnpm) init astro\b`
Replace:
`$1 create astro`

Except for two instances:

1. `packages/create-astro/CHANGELOG.md` -- skipped because changelog.

2. `packages/create-astro/test/create-astro.test.js.skipped` -- skipped, old test file disabled in https://github.com/withastro/astro/pull/3168.

_Q: should I run `pnpm exec changeset` for minor changes only touching *.md files? I would guess no._

## Testing

n/a, no code changes.

## Docs

n/a, changes make README.md files consistent with docs, see above.

### CODE REVIEW

**Review by matthewp — APPROVED** [review]
Thanks!

**Review by delucis — APPROVED** [review]

**Review by bluwy — COMMENTED** [review]
Should we recommend `@latest` too? Since `npm create` always prefers the cache (for some reason). e.g. `npm create astro@latest -- --template with-mdx` (The docs seem to follow this too)

**Review by bluwy — APPROVED** [review]
Looks great! Thanks for making the change.

**Comment by mrienstra** [comment]
> Looks great! Thanks for making the change.

Thank you for catching that! 😅

**Pull request merged**
