### PR TITLE
fix: Fixed errorOverlay theme toggle bug.

### PR DESCRIPTION
**Pull request by liruifengv**
## Changes

Close https://github.com/withastro/astro/issues/10715

- Save `localStorage.astroErrorOverlayTheme` when detected system dark mode
- Update `isDark`
```ts
const isDark = localStorage.astroErrorOverlayTheme === 'dark' || this?.classList.contains('astro-dark');
```

## Testing

null

## Docs

null

### CODE REVIEW

**Comment by Princesseuh** [comment]
Apologies, I'm not sure I understand this PR. What issue is this fixing exactly?

**Comment by liruifengv** [comment]
> Apologies, I'm not sure I understand this PR. What issue is this fixing exactly?

When the system theme is detected as dark, but dark is not stored in localstorage, and we use the value of localstorage to assign isDark, errorOverlay's themeSwitch does not work as expected

**Comment by ematipico** [comment]
I can't replicate the issue. Maybe it's worth opening an issue with clear instructions on how to replicate it. How does an end-user end up with an empty local storage?

**Comment by liruifengv** [comment]
I will open a issue about that.

**Comment by matthewp** [comment]
Here's the issue: https://github.com/withastro/astro/issues/10715

makes sense to me.

**Review by bluwy — APPROVED** [review]

**Review by ematipico — APPROVED** [review]

**Pull request merged**
