### PR TITLE
Update templates to avoid devDependencies and :global

### PR DESCRIPTION
**Pull request by Jutanium**
## Changes

- Move all dependencies from `devDependencies` to `dependencies`
- Instead of `:global`, use a separate `<style is:global>` tag
- Reorder the `dependencies` to make it easier to see which frameworks are used in an example
- Remove the unused explicit `markdown-remark` dependency from the Shiki example

## Testing

No new testable features

## Docs

No new documentation required, unless we want to prescribe `dependencies` over `devDependencies`

### CODE REVIEW

**Comment by Jutanium** [comment]
There was a discussion yesterday - the logic was that `dependencies` and `devDependencies` behave the same in Astro, so we should only use one of the two in templates. And if we're using one of the two, we might as well choose `dependencies`.

Tagging @FredKSchott to verify that this was the explanation!

**Comment by bluwy** [comment]
We would still need to split them depending on how we deploy I think. Say if we're using `@astrojs/node`, we build it, the build output would only require prod dependencies we can install them with `npm install --prod` , with this pR we would also install astro and others unnecessarily. That said I've rarely seen people do this these days, but it was the original usecase for `dependencies` and `devDependencies` by nodejs.

**Comment by Jutanium** [comment]
@bluwy How easy is it for the user to know which of their dependencies is needed in server prod? In the case you'd describe, I think it's better for us to recommend putting everything in `dependencies` so that everything will work whether the `--prod` flag is used or not.

**Comment by Jutanium** [comment]
Hmm... in the case you describe, what if the user split their dependencies between `dependencies` and `devDependencies` but got the split wrong? If they ran `npm install --prod`, it would leave out `devDependencies`, but that could be something they actually needed.

If the default is to put everything in `dependencies`, then either `npm install` or `npm install --prod` would work. It might install unnecessary dependencies, but that's better than not installing something that was the required. A well-informed user can always split it out later.

**Review by matthewp — APPROVED** [review]

**Comment by bluwy** [comment]
That's true too. I guess if the right thing to do is to eventually split out `astro` (and other tooling packages) as `devDependencies`, then it'd be great if that's the default we recommend.

I also think it's good if we can expose the differences between `dependencies` and `devDependencies` early on. Moving all to `dependencies` would be great for newbies to the JS ecosystem, but if they start to expand to other frameworks/libraries, we wouldn't want them to ship `eslint` as a dependency of their library in the future.

**Comment by FredKSchott** [comment]
The main problem being solved here (called out in the livestream) is a new user saying "wait, where should my dependencies go, `dependencies` or `devDependencies`? What's the difference?". For most users there isn't really any difference (that I'm aware of, at least!), but then this still allows an advanced user to move some deps into `devDependencies` if they want to.


All deploy targets that I'm aware of install all dependencies by default. I guess a user could run `npm install --production` and only want their runtime deps, but I think we can consider this an advanced use case, where you would be responsible to move your deps around.

**Review by FredKSchott — APPROVED** [review]

**Pull request merged**
