### PR TITLE
Support Vite 3.1

### PR DESCRIPTION
**Pull request by bluwy**
## Changes

While checking out #4727, I noticed that we're incorrectly accessing the `this` context in the `handleHotUpdate` hook. This was previously the Vite plugin object, but was removed with the object hooks feature: https://github.com/vitejs/vite/issues/9634 and https://github.com/vitejs/vite/pull/9885

## Testing

Tested locally. This issue can be triggered when updating an Astro file. Ideally #4454 should cover this.

## Docs

N/A. internal change.

### CODE REVIEW

**Review by matthewp — APPROVED** [review]

**Review by matthewp — CHANGES_REQUESTED** [review]
Why not go ahead and upgrade to 3.1 here too?

**Comment by bluwy** [comment]
do we still want to pin it to `3.1` or `~3.1`? (or could decide later in pin for now)

**Comment by matthewp** [comment]
Let's try `~3.1`

**Comment by bluwy** [comment]
Updated to `~3.1.0` 👍

**Comment by bluwy** [comment]
Looks like the new Vite types are messing with the Astro build. I reverted the Vite version bump at the meantime and we can probably tackle the types stuff in another PR.

**Review by matthewp — APPROVED** [review]

**Pull request merged**
