### PR TITLE
fix(markdown): file.url fixes

### PR DESCRIPTION
**Pull request by JuanM04**
## Changes

- file.url now respects `trailingSlash`, adding a `/` at the end when it's set to `"always"`
- file.url now respects `base` (needed to change the default of `base` from `./` to `/`)
- Minor fix to this RegEx:

```diff
- fileId.replace(/^.*\/pages\//, sitePathname)
+ fileId.replace(/^.*?\/pages\//, sitePathname)
```

The `?` makes the selection "lazy", which means that it will replace the shortest match. For example:

```js
const fileId = "src/pages/docs/pages/how-to-create-a-page.md"

console.log(fileId.replace(/^.*?\/pages\//, '')) // docs/pages/how-to-create-a-page.md
console.log(fileId.replace(/^.*\/pages\//, '')) // how-to-create-a-page.md
```

### CODE REVIEW

**Comment by FredKSchott** [comment]
LGTM! Would love to see an added test since this feels like something that we could accidentally regress pretty easily

**Comment by JuanM04** [comment]
@FredKSchott I've added some test and also made it work with `base`! While doing that, I've changed the default of `base` from `./` to `/` (so now, `base` always starts with a `/`)

**Review by FredKSchott — APPROVED** [review]
Agreed, that makes way more sense. Most of our tests are testing the default, so if they are passing I have confidence that this change works. Mind confirming that the `dev` and `preview` commands work with an example template? If so the LGTM to merge!

**Comment by JuanM04** [comment]
> Mind confirming that the dev and preview commands work with an example template to be extra sure?

I've tried with a few and all seems normal!

**Comment by FredKSchott** [comment]
woo! sgtm

**Pull request merged**
