### PR TITLE
Fix Docs layout: Themes in Zh-tw

### PR DESCRIPTION
**Pull request by ymcheung**
## Changes
- [x] Fix broken layout in Zh-tw docs (Themes)

## Testing
http://localhost:3000/zh-TW/themes

## Docs
Fix broken layout in Zh-tw

### CODE REVIEW

**Review by tony-sull — APPROVED** [review]
Looks good to me!

**Comment by tony-sull** [comment]
Thanks for fixing this @ymcheung!  Looks like there's a merge conflict but if you don't mind rebasing your branch to resolve the conflict we'll get this merged in

**Comment by drwpow** [comment]
Thank you! There is currently an issue with the docs we’re working on, but will merge that once that’s resolved.

**Comment by ymcheung** [comment]
Rebased!

**Comment by drwpow** [comment]
Looks good but please rebase off latest `main`! Will merge when it’s up-to-date.

**Pull request merged**
