### PR TITLE
Ensure `chunkFileNames` do not include invalid characters

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- We were getting reports of the `@astrojs/netlify` adapter being totally broken for `server` and `hybrid` deployments.
- Turns out Astro would sometimes emit chunks with invalid characters `@_@` which Netlify choked on
- The fix is to ensure `chunkFileNames` sanitizes the filename first
- Also changes our chunk asset filenames from something like `dist/server/chunks/index@_@astro.[hash].[ext]` to something like `dist/server/chunks/index_hash.[ext]`
- Notable change is `[name].[hash].[ext]` to `[name]_[hash].[ext]`
- Changeset added!

## Testing

Tested manually with community reproductions. It works!

## Docs

Bug fix only, will alert folks!

### CODE REVIEW

**Comment by natemoo-re** [comment]
!preview sanitize-filenames

**Comment by natemoo-re** [comment]
!preview sanitize-filenames

**Comment by natemoo-re** [comment]
Tests will need to be updated to match this expected format `[name]_[hash]` instead of `[name].[hash]`

**Review by ematipico — APPROVED** [review]

**Review by FredKSchott — APPROVED** [review]

**Review by FredKSchott — APPROVED** [review]
RE-APPROVED

**Pull request merged**
