### PR TITLE
fix: correctly handle head propagation in content layer deferred rendering

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes
Previously we were not correctly handling head propagation for MDX and Markdoc entries in content layer. This PR ensures the correct flag is included in the resolved Vite ID, and that these assets are correctly included when rendering.

## Testing

The MDX head propagation test is updated to use content layer

### CODE REVIEW

**Review by ematipico — APPROVED** [review]
The code looks. Shouldn't this fix be sent to `main` instead?

**Comment by ascorbic** [comment]
I guess there's nothing to prevent us fixing this in 4.x. I've been avoiding it in other stuff because it touches stuff that's changed, but this should be fine. I'll see if I can rebase it cleanly

**Comment by ascorbic** [comment]
Let's see if this works...

**Comment by ematipico** [comment]
It's just a thought. Considering that we will be in beta for a few months, we should ponder if this fix is worth having in `v4.*` too.

**Review by Princesseuh — APPROVED** [review]

**Review by bluwy — APPROVED** [review]

**Pull request merged**
