### PR TITLE
Type declarations for vite-plugin-pwa example

### PR DESCRIPTION
**Pull request by dsclearuc**
Add types declaration for IDE integration

## Changes

- Add types declaration to vite-plugin-pwa example, defined in tsconfig.json

### CODE REVIEW

**Review by bluwy — CHANGES_REQUESTED** [review]
I think this should be added [here](https://github.com/withastro/astro/blob/b6203a41f70d0911ddcf720e54e51784dc0cead0/examples/with-vite-plugin-pwa/src/env.d.ts#L2) instead, so we don't override away the default global types (due to how TypeScript works)

**Comment by matthewp** [comment]
@dsclearuc do you plan on updating this PR?

**Comment by dsclearuc** [comment]
> @dsclearuc do you plan on updating this PR?

Yes @matthewp , sorry for the late reply, was on vacations with the kids ;)

**Comment by dsclearuc** [comment]
As tsconfig.json definition, @matthewp is correct, configuring types there will overwrite default behavior of auto-import ./node_modules.  I closed this PR since default behavior should work on most IDEs, it was a local issue with my Webstorm

**Pull request closed without merging**
