### PR TITLE
Add new markdown.frontmatterPlugins config option

### PR DESCRIPTION
**Pull request by sylvinus**
Hello!

Currently, when importing Markdown files, one can modify their content via the `markdown.remarkPlugins` and `markdown.rehypePlugins` config options.

However there is currently no supported way to do the same with their frontmatter. This could open up interesting usecases:
 - Auto-registering components in imported Markdown files (just append the imports to `frontmatter.setup`!)
 - Provide a more generic solution to the `frontmatterDefaults` suggestion here: https://github.com/withastro/rfcs/discussions/172#discussioncomment-2558676
 - Probably more that I'm missing!

This patch adds a prototype implementation of a new `frontmatterPlugins` config option.

Let me know what you think!

Thanks,

### CODE REVIEW

**Comment by mattfelten** [comment]
Any progress on this @sylvinus? I'm really excited for this change

**Comment by sylvinus** [comment]
By the way in the meantime I've also been using a custom plugin to register all available components in Markdown files:

```
// src/plugins/inject-components.mjs
import glob from 'fast-glob';
import path from 'path';

export default (dir) => {
  let components = [];
  return {
    name: 'mdInjectComponentsPlugin',
    enforce: 'pre',
    options: async () => {
      components = await glob(dir.replace(/\/$/g, '') + '/**/*');
    },
    transform: (ctx, id) => {
      if (!id.match(/\.md$/)) {
        return false;
      }
      let prepend = "";
      for (const component of components) {
        let name = path.basename(component, path.extname(component));
        prepend += "import "+name+" from '"+component+"';\n";
      }
      ctx = prepend + "\n" + ctx;
      return ctx;
    },
  };
};
```

```
// astro.config.mjs
import { defineConfig } from 'astro/config';
import path from 'path';
import {fileURLToPath} from 'url';
import mdInjectComponentsPlugin from "./src/plugins/inject-components.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export default defineConfig({
  vite: {
    plugins: [mdInjectComponentsPlugin(path.resolve(__dirname, "./src/components/"))],
  },
});
```

**Comment by matthewp** [comment]
Going to close since this branch is fairly stale. Feel free to resubmit when you have it working.

**Comment by mrienstra** [comment]
@delucis, @matthewp, some months have passed and yay, Astro v2! Trying to figure out the status + next steps for this. Aside from rebasing + polishing this PR, maybe the RFC should be reviewed to make sure it's still in alignment with other goals & sufficiently clear?

Context:
RFC PR: https://github.com/withastro/roadmap/pull/196
RFC: https://github.com/withastro/roadmap/blob/main/proposals/0022-frontmatter-plugins.md

The RFC has [two unresolved questions](https://github.com/withastro/roadmap/blob/main/proposals/0022-frontmatter-plugins.md#unresolved-questions), should those be addressed before someone picks up this PR?

(Coming here from https://github.com/withastro/astro/issues/397#issuecomment-1193377064)

**Comment by delucis** [comment]
Modifying frontmatter as proposed in this RFC is now available!

Some docs: https://docs.astro.build/en/guides/markdown-content/#modifying-frontmatter-programmatically

**Comment by mrienstra** [comment]
Nice, I hadn't seen that yet!

Associated issue: https://github.com/withastro/astro/issues/5099
Associated PR: https://github.com/withastro/astro/pull/5687
Bug fix (merged but not unreleased): https://github.com/withastro/astro/pull/5927

Builds on this foundation: https://github.com/withastro/astro/pull/4176

**Pull request closed without merging**
