### PR TITLE
Asset filename delimiter

### PR DESCRIPTION
**Pull request by noone-silent**
## Changes
You can change the delimiter of the optimized image from _ to any.

## Testing
New tests have been added to check the default and for a dash delimiter.

## Docs
This change does not affect users without setting the config.

### CODE REVIEW

**Comment by Princesseuh** [comment]
Thank you, do you have any examples of those SEO tools?

**Comment by noone-silent** [comment]
> Thank you, do you have any examples of those SEO tools?

https://rankmath.com/kb/how-to-name-images-for-seo/
https://seranking.com/blog/image-seo/

They all have tools that flag those filenames.

Also: https://developers.google.com/style/filenames

Google likes to ~~force~~use their own style guides.

**Comment by matthewp** [comment]
Could we do rollup style `[file]_[ext]` instead, to give people full customizability?

**Comment by noone-silent** [comment]
> Could we do rollup style `[file]_[ext]` instead, to give people full customizability?

I don't know what this have to do with changing the delimiter of the filename and the appended hash. I didn't want to make the whole filename configurable, that's out of this scope for this PR.

I asked in the chat if we can change the delimiter and the answer was no and if I could create a PR about this, because many people asked about that. Then I did. So please accept it. If you need more customization, then please create a separate PR for this.

**Comment by noone-silent** [comment]
So will this be used? If it is not enough for what you want, then I will just close it. I can live witch patch-package.

**Comment by Princesseuh** [comment]
We would prefer a solution that offer full customisation like @matthewp suggested. Since there's so many opinions around the naming of the files, we fear that just changing the delimiter won't satisfy users who require changes and will end up being this "one edge-casey thing you can change" vs a solution everyone can enjoy.

**Pull request closed without merging**
