### PR TITLE
Use devalue for island props serialization

### PR DESCRIPTION
**Pull request by bluwy**
## Changes

fixes https://github.com/withastro/astro/issues/12088
partially revives https://github.com/withastro/astro/pull/8004

compared to #8004, this uses `devalue` instead of `seroval` as I don't really understand the main difference with `seroval`, and we're already using `devalue` in our codebase. It also doesn't completely serialize other island information, only the props, to minimize the change surface area.

## Testing

added test for #12088 and removed some irrelevant ones

Using the repro in https://github.com/withastro/astro/issues/7978, this reduces the serialized prop value size ("Astro bytes"):

| Before (4.15.9) | After (this PR, v5) |
|--------|--------|
| Screenshot 2024-09-30 at 10 13 58 AM | Screenshot 2024-09-30 at 10 15 17 AM |

It could get even lower by serializing string values with single quotes to prevent needing escaping, but I think for now it's fine as a stop gap.

## Docs

It doesn't look like we document specific serialization edge cases other than https://docs.astro.build/en/guides/framework-components/#passing-props-to-framework-components, which is still true today (regarding function serialization)

### CODE REVIEW

**Review by Princesseuh — APPROVED** [review]

**Comment by bluwy** [comment]
> For context, `seroval` is used by Solid and has [more comprehensive support](https://github.com/lxsmnsyc/seroval/blob/main/docs/compatibility.md?rgh-link-date=2024-09-30T13%3A22%3A37Z#supported-types) for common cross-environment primitives.

I did some checks and I think they're largely the same. `devalue` can handle typed arrays, holey arrays, and other edge cases well. Except `Error` objects but I think that's fine and not something users usually do.

> The other benefit is that we wouldn't need to generate the `(0, eval)()` step, because `seroval` outputs self-contained JS strings.

I think both devalue and seroval outputs similar JS that still requires us to eval. We're putting the values in attribute values, so we have to manually eval it again.

devalue also seem to be much smaller, which reduces the ssr bundle size. Comparison: [devalue (5.21 kB -> 2.16 kB (gzip))](https://bundlejs.com/?q=devalue&treeshake=%5B%7Buneval%7D%5D) and [seroval (28.2 kB -> 7.75 kB (gzip))](https://bundlejs.com/?q=seroval&treeshake=%5B%7Bserialize%7D%5D)

**Review by ascorbic — APPROVED** [review]
This is great. Makes a lot of sense that this matches the supported types for content layer too.

**Comment by matthewp** [comment]
@ascorbic having much client JS are we adding by bringing `devalue` in? The reason we went with a custom thing is because the file sizes of these tools seemed like too much. Also remember that it gets inlined into the page, you really don't want a several kilobytes dependency to be inlined like that, it's a waste to not have reuse.

Also consider here that the only thing we gain by bringing in a dependency is not needing to maintain our custom serializer/deserializer. But we haven't had much maintenance on the one we have. This `Infinity` thing is the last time we've gotten a request for a new type in probably a couple of years. Adding more kB to everyone's pages to avoid occasionally updating a small amount of custom code doesn't seem like a very good tradeoff to me.

@natemoo-re did a spike a while back (last year IIRC) on going back to inlining the hydration script rather than using astro-island. If we did that we could use these sorts of tools again because there would be no client-side penalty for deserialization. I think that's probably what we should do instead of this. And for now, just add Infinity as a new type in our custom serializer.

**Comment by natemoo-re** [comment]
@matthewp supporting `Infinity` in the custom logic seems like a reasonable conclusion to me! NWTWWHB.

As Astro pushes into more ecomm/interactive usecases, the potential payoff on serialization optimizations will continue to grow. Could pair nicely with any cross-island communication explorations, if that's ever on the table.

**Comment by bluwy** [comment]
> going back to inlining the hydration script rather than using astro-island. If we did that we could use these sorts of tools again because there would be no client-side penalty for deserialization. I think that's probably what we should do instead of this.

We can't do that because that will require `unsafe-inline` again.

> how much client JS are we adding by bringing `devalue` in?

devalue `stringify` is [971B gzip](https://bundlejs.com/?q=devalue&treeshake=%5B%7B+parse+%7D%5D). Our custom implementation is [283B gzip](https://bundlejs.com/?share=KYDwDg9gTgLgBAYwgOwM7zFCYAqBPMYVOAXjgG8AoASGoAYAuOACgDcBDAGwFdgBKUgD44UYKwCWrYAHkARgCtgCGGy68%2BAGhrUAjE1U9%2BQkWMnAAglCjs8B9VtoAmfR0MCSw5MADucAErAAOYAouB2-A7UAMwuakYecF6%2BACLsMMDhmtoALLFuxklwALLsYMyiElKW1rau6lm0AKx56gU%2BcADKwCoVZtU2mQ3UAGwt8cIAQuKBAJLIKnUR2gDsY%2B6e7QCqfgAymZEAHGttvpvi8wf9tXFDAJzHCYVn8zrDV-vaOowsi%2BuJW%2BcYFFHO9fg4AL4AbkoNAA9LC4AA5CDwbioc6BOAAKQ60kRADowOwoKhgCZKsAoHBZEp2GiyeIYAByYiyFEwCAAWwAtNwwNTuPBvGTvOx5nAOWBuQATCDeZA0UCQWCIFDoclmHB8zhksjldjeJhivB8I3IPDGKi0JBoeAAbRgBGAGjgiwAuqQRAbobRRDBuFBkBKnXBznBMNh8IRiAB%2BcNYXBO1AOp1uzJwJjcZDS4AAM3OwGlPqhMOoSug8Bt6t6VSsNk9%2BsNcGNpub5uMjebxCuAB5jYI%2BPjOaVyqYpFqwDq%2BNDFeAK6rbRqpHJFMoG9Ymy2zRaElbqOJcyxHYQIIeN3AAIQkMhMiAKJTMuAAHyfXt817IyG4nE4Aj9AaDDcfWof9AzgFcH3xXMsE5YJ5igcQiGYCDlHxYB4MQ1BG0HYcymYO0AGtgDwF13T%2BQjiJdGtgAnHVMjdPhpxoKEgA).

---

Looks like there's no other way to implement this without size tradeoffs. I do still think the edgecases being handled by devalue is valuable but maybe in the future.

**Pull request closed without merging**
