### PR TITLE
Add action to check if PR can be merged

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- This adds a new action that checks PRs to see if they can be merged, based on whether they have a changeset marked as minor.
- If there is a minor changeset it will add a blocking review that needs to be overridden.
- If there is already a blocking review from this bot, do not apply it a second time.
- Adds the `semver minor` label automatically.

## Testing

- Tested in this PR - https://github.com/withastro/astro/pull/4853

## Docs

N/A

### CODE REVIEW

**Review by bluwy — COMMENTED** [review]
Question:

1. Does the bot always comment when you push new commits, or only once?
2. What about adding a `semver minor` label instead?

**Comment by matthewp** [comment]
> 1. Does the bot always comment when you push new commits, or only once?

It's doing it every time, let me see if I can detect if its already does so to prevent that.

> 2. What about adding a semver minor label instead?

We wanted to block so that it's very clear that the PR shouldn't be merged. But adding a label as well would be nice as it gives the person doing the release an easy way to see what needs to go out, so I'll try to add that.

**Comment by matthewp** [comment]
@bluwy those two things have been done, see https://github.com/withastro/astro/pull/4853 which shows that it's only applied once and that the label is also added.

**Comment by natemoo-re** [comment]
This looks amazing, great job!

My only (not blocking) comment is that this doesn’t handle `major` changesets. Not sure how necessary that is since it will happen very rarely, but we’ve definitely seen external contributors add one of those accidentally. Might be nice to block those automatically as well.

**Review by bluwy — APPROVED** [review]
Looks great! Thanks for verifying that it works too. I think @natemoo-re has a good point too, but also might be a nice to have.

**Comment by matthewp** [comment]
Thanks! I've created a new issue to tackle major as well.

**Pull request merged**
