### PR TITLE
Corrected rss.xml to feed.xml to reflect the actual default value

### PR DESCRIPTION
**Pull request by lucemans**
## Docs

Corrected rss.xml to feed.xml to reflect the actual default value

### CODE REVIEW

**Comment by lucemans** [comment]
Can be merged in accordance with https://github.com/withastro/astro/pull/2142#issuecomment-988055314

**Comment by sarah11918** [comment]
Thanks for noticing this and bringing it to our attention! We are discussing whether we actually want the docs to change, or the code to change back!

**Comment by lucemans** [comment]
Awesome! Do keep me updated! If you would rather have it reverted back I would be happy to make that change and adjust this PR!

**Comment by lucemans** [comment]
Happy to be able to help!

**Comment by jonathantneal** [comment]
Thanks, @lucemans, for putting together the work for this change. Thanks, @sarah11918, for the investigation (so that it turned out the change was unintentional), and for the PR. This is now superseded by https://github.com/withastro/astro/pull/2172 which has been merged. 🎉

**Pull request closed without merging**
