### PR TITLE
Revert "refactor: remove serialize-javascript (#3278)"

### LINKED ISSUE #3303: 🐛 BUG: "Cannot stringify arbitrary non-POJOs" at dev and build
### What version of `astro` are you using?

1.0.0-beta.24

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux, Ubuntu 21.10

### Describe the Bug

Astro server crashes because of an error by `devalue`:
```
Error: Cannot stringify arbitrary non-POJOs
    at walk (/node_modules/.pnpm/devalue@2.0.1/node_modules/devalue/dist/devalue.esm.js?v=5074f74f:51:35)
    at Array.forEach (<anonymous>)
    at walk (/node_modules/.pnpm/devalue@2.0.1/node_modules/devalue/dist/devalue.esm.js?v=5074f74f:40:27)
    at /node_modules/.pnpm/devalue@2.0.1/node_modules/devalue/dist/devalue.esm.js?v=5074f74f:56:72
    at Array.forEach (<anonymous>)
    at walk (/node_modules/.pnpm/devalue@2.0.1/node_modules/devalue/dist/devalue.esm.js?v=5074f74f:56:40)
    at Module.devalue [as default] (/node_modules/.pnpm/devalue@2.0.1/node_modules/devalue/dist/devalue.esm.js?v=5074f74f:60:5)
    at Module.serializeProps (/node_modules/.pnpm/astro@1.0.0-beta.25_sass@1.51.0/node_modules/astro/dist/runtime/server/hydration.js:4:17)
    at Module.renderComponent (/node_modules/.pnpm/astro@1.0.0-beta.25_sass@1.51.0/node_modules/astro/dist/runtime/server/index.js:225:2)
```
 
 Although I have tried to isolate this to reproduce in Astro, my efforts have failed so far, but I have been able to produce the same error with `devalue`. This happens when you pass a class as a prop.

### Link to Minimal Reproducible Example

https://runkit.com/embed/e00mijnhx0gg

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by matthewp**
This reverts commit 13c1f5ff6bc18f05be2f9fee32331d89fc58af94.

## Changes

- Using `devalue` caused some regressions. Reverting to fix this.
- Fixes #3303

## Testing

No

## Docs

N/A, bug fix

### CODE REVIEW

**Comment by matthewp** [comment]
@FredKSchott We need to define what we support, currently it's been "whatever serialize-javascript supports" and thus this regression. Rather than define it on the fly I think we need to take a step back and reassess the tradeoffs (The PR that removed individual script tags was reverted because of this issue) and make a decision on what to support, and then move forward with implementations.

**Comment by FredKSchott** [comment]
Thoughts on using `@nuxt/devalue` instead of `devalue`, which seems to have added drop-in support for non-POJOs? https://www.npmjs.com/package/@nuxt/devalue

I'm not against reverting if we need to, but this feels small enough that we could that "what is expected behavior?" convo here now (or in Discord) vs. reverting and then having the convo. 

This doesn't feel like something impacting many users, based on the bug description.

**Comment by matthewp** [comment]
My concern is that we might want to break this again in the future to fix the "one script tag per island" problem and I'd rather come to one conclusion on what we support and break once than multiple times.

**Comment by FredKSchott** [comment]
ah, gotcha. Okay, that makes sense to me. LGTM with either path.

**Review by FredKSchott — APPROVED** [review]

**Pull request merged**
