### PR TITLE
chore: changed `data-astro-raw` to `is:raw`

### PR DESCRIPTION
**Pull request by JuanM04**
## Changes

Following [the roadmap](https://github.com/withastro/rfcs/discussions/1)

### CODE REVIEW

**Review by natemoo-re — APPROVED** [review]
LGTM! Thanks. ☺️ I'll rerun the test suite to double check the Windows failure.

**Comment by matthewp** [comment]
I say we remove that test and rely on the lit smoke tests to cover lit support. That test has caused us a lot of pain. I'll open a separate PR.

**Comment by JuanM04** [comment]
These lines from the lit test are causing issues:

```js
after(async () => {
	// The Lit renderer adds browser globals that interfere with other tests, so remove them now.
	const globals = Object.keys(globalThis.window || {});
	globals.splice(globals.indexOf('global'), 1);
	for (let name of globals) {
		delete globalThis[name];
	}
});
```

**Comment by JuanM04** [comment]
Found the culprit: https://github.com/lit/lit/pull/2510

**Comment by matthewp** [comment]
@JuanM04 does that PR fix the issue or cause it?

**Comment by JuanM04** [comment]
Fixs it. I'll write my findings in your PR

**Comment by matthewp** [comment]
This can be rebased with main now. Thanks for figuring this out @JuanM04 !

**Pull request merged**
