### PR TITLE
Warn when trying to access headers in SSG mode

### LINKED ISSUE #3018: 🐛 BUG: `Astro.request.headers.get('cookie')` always null
### What version of `astro` are you using?

1.0.0-beta.2

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

In my `index.astro` I have a google sign in button, that redirects to my `auth/success` POST handler. In that POST handler, I verify the JWT token, set it as a cookie, and redirect the user back, like so:

```js
export async function post(_, req) {
  // verify token etc, omitted for brevity
  const headers = new Headers();
  
  headers.append('Set-Cookie', `jwt=${token}; Path=/; HttpOnly`);
  headers.append('Location', '/');

  return new Response('', {
    status: 302,
    headers,
  });
}
```

In the browser I can see that the cookie is indeed set, and I also see it in the network tab in the request:

Screenshot 2022-04-07 at 14 17 13

Screenshot 2022-04-07 at 14 18 12

 In my `index.astro`, I want to check for the presence of the cookie, but the `Astro.request.headers.get('cookie');` is always null, and `Astro.request.headers` is always an empty object. Am I missing something? Shouldnt I be able to access the cookie here?

e.g.:
```astro
---
const cookie = Astro.request.headers.get('cookie');
console.log(cookie); // null
console.log(Astro.request.headers); // {}
---
<html lang="en">
<!-- etc -->
</html>
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-s3uktf?file=src/pages/auth/success.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Adds a warning when trying to get a headers in SSG mode.
- Closes #3018

## Testing

No, can't test warnings very well currently.

## Docs

N/A

### CODE REVIEW

**Comment by JuanM04** [comment]
I can't see the warning when adding `console.log(Astro.request.headers.get('cookies'))` to a `.astro` file

**Comment by matthewp** [comment]
Ah, good reason to actually add a test then, I'll do that now.

**Comment by matthewp** [comment]
@JuanM04 added a test and moved where the warning happens, should work now.

**Review by JuanM04 — APPROVED** [review]
Seems good!

**Pull request merged**
