### PR TITLE
Use magicast for astro add

### PR DESCRIPTION
**Pull request by bluwy**
## Changes

fix https://github.com/withastro/astro/issues/11836

Use magicast to simplify our current code and reduce the dependency (particularly `@babel/generator` and `@babel/traverse`). The generated code is slightly difference where magicast uses recast that injects new lines and trailing commas in some places. I think it's negligable though

Before:

image

image

After:

image

image

## Testing

Ran `astro add` manually with different setups.

## Docs

n/a. internal change.

### CODE REVIEW

**Comment by matthewp** [comment]
Should we do this against `next` instead? `astro add` is a feature we almost never have to do maintenance on. Glad to reduce the footprint, but not sure doing so in a `minor` is a good call. If we do it in 5.0 we'll have months to fix bugs this might cause.

**Comment by bluwy** [comment]
I did another pass and fix some edge cases where they're adding an integration that is already setup. I think it should be fine in the next minor, or even a patch though since the problem magicast solves is well-scoped. I did some tests locally and it's working fine for a lot of happy paths and edge cases. One thing I realize is that before `astro add` is executed, we also load and validate the astro config, so we know that at least we're dealing with a well-formed config.

I think bugs could happen for sure, but I don't think it would be too hard to solve. The worst case is that users have to manually update the config themselves.

**Review by matthewp — APPROVED** [review]
talked it over and @bluwy feels confident

**Comment by bluwy** [comment]
If anything happens, feel free to revert it 😅 (But I'll try to look into it too if it's not urgent)

**Pull request merged**
