### PR TITLE
fix: upgraded vite

### LINKED ISSUE #2639: 🐛 BUG: vite:import-analysis error with `vercel dev`
### What version of `astro` are you using?

0.23.0

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

**Steps to reproduce**
1. `npm init astro` (I used the minimal template)
2. `vercel link`
3. Set the development command to `astro dev --port $PORT`
4. `vercel dev`

This error will be thrown no matter which page you open:

```
[vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
  Plugin: vite:import-analysis
  File: /home/juanm04/dev/tests/test-vercel/src/pages/index.astro?html-proxy=&index=0.js
  6  |                  <meta charset="utf-8" />
  7  |                  <meta name="viewport" content="width=device-width" />
  8  |                  <title>Astro</title>
     |                        ^
  9  |          </head>
  10 |          <body>
      at formatError (/home/juanm04/dev/tests/test-vercel/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38082:46)
      at TransformContext.error (/home/juanm04/dev/tests/test-vercel/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38078:19)
      at TransformContext.transform (/home/juanm04/dev/tests/test-vercel/node_modules/vite/dist/node/chunks/dep-971d9e33.js:69759:22)
      at async Object.transform (/home/juanm04/dev/tests/test-vercel/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38318:30)
      at async doTransform (/home/juanm04/dev/tests/test-vercel/node_modules/vite/dist/node/chunks/dep-971d9e33.js:53014:29)
```

### Link to Minimal Reproducible Example

Described above

### PR DESCRIPTION
**Pull request by JuanM04**
## Changes

Upgraded Vite to v2.8.6 (fixes #2639 via vitejs/vite#7093)

### CODE REVIEW

**Comment by FredKSchott** [comment]
oh no, vite errors! cc @natemoo-re

**Comment by JuanM04** [comment]
@FredKSchott maybe it's related to this? https://github.com/vitejs/vite/pull/7031

**Comment by FredKSchott** [comment]
@JuanM04 🥁 🥁 🥁 🥁

**Comment by JuanM04** [comment]
@FredKSchott Turns out the change that broke the test [was reverted](https://github.com/vitejs/vite/pull/7136), so Vite v2.8.6 works fine

**Review by natemoo-re — APPROVED** [review]
Looks good to me! Thanks!

**Pull request merged**
