### PR TITLE
fix: Cannot read properties of null (reading 'Symbol(astro.headAndContent)')

### PR DESCRIPTION
**Pull request by icaliman**
## Changes
- Fixed the error that we get in our SSR project. This error occurs after 2-3 seconds of page load.
image

## Testing

Can not provide a minimal reproduction example.

## Docs

Docs don't need change.

### CODE REVIEW

**Comment by bluwy** [comment]
I think it would be best if you can figure out how this happens in the first place. A repro or test would help us prevent regressing this in the future.

**Comment by icaliman** [comment]
@bluwy I found the issue and added a test.

**Review by matthewp — APPROVED** [review]
great test!

**Comment by patheticGeek** [comment]
Hey! I have this same issue in prod, could we get this merged faster?

**Comment by matthewp** [comment]
@bluwy can you take a look at this now that you've changed how the test work?

**Comment by bluwy** [comment]
LGTM. We had an internal discussion whether this behaviour is desirable as we've not documented returning `null` as a valid pattern in Astro components, but after further testing, it looks like any values return are rendered as-is. As if you're doing `<div>{<some-value>}</div>` in an Astro file.

Given that I think handling `null` here make sense for now and we can revisit this behaviour again in the future. I'll rebase this PR before merging.

**Pull request merged**
