### PR TITLE
Refactor CSS preprocess and HMR

### LINKED ISSUE #3382: 🐛 BUG: Imported SCSS does not recompile on change when using HMR
### What version of `astro` are you using?

1.0.0-beta.27

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

If I import a SCSS, then modify the imported file, my browser (using HMR) does not update to reflect the changes.

## Steps to reproduce
- Open [example repo](https://stackblitz.com/edit/node-wahdub?file=src/pages/index.astro)
- Run `npm run dev`
- Then try changing the contents of `src/scss/use.scss` and `src/scss/import.scss`
- Observe the preview window does not reflect the changes (although the console _does_ show e.g. `[astro] update /src/scss/use.scss`)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/node-wahdub?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bluwy**
## Changes

Fix #3382

- Refactor CSS preprocess deps tracking for #3382
- Fix HMR handling for `@import` in styles in astro files

Notes:

1. I'll find some time to upstream a feature for Vite to expose its `compileCss` function to make preprocessing a lot easier.

## Testing

The existing tests should cover the preprocess refactor. For HMR, I'd love to add tests, ~~but it doesn't seem like we've setup the infrastructure for it since those require editing files locally~~ will add test tomorrow. For now, I've tested locally with the repro in #3382

## Docs

N/A

### CODE REVIEW

**Comment by matthewp** [comment]
@bluwy to confirm that this example:

```astro
<style>
  @import "./another.css";

  .one {
    color: blue;
  }
</style>
```

That the `another.css` style are __not__ scoped but `.one` is.

**Comment by matthewp** [comment]
Needs a changeset.

**Comment by bluwy** [comment]
@matthewp I tested the `@import` locally, and it looks like they are indeed all scoped. Here's a [stackblitz](https://stackblitz.com/edit/github-kynq5b?file=src%2Fstyle.css,src%2Fpages%2Findex.astro,src%2Fcomponents%2FCard.astro) (The `main` and `Card`s should have a green background).

**Comment by matthewp** [comment]
Thanks! I can see that they are being scoped. I believe this is a bug. But not something to worry about breaking in this PR as it's already broke!

**Review by matthewp — APPROVED** [review]

**Comment by bluwy** [comment]
Adding tests for this today but it requires some small infrastructure change since we skip HMR for files inside Astro, so I'll make a separate PR to easily review it. Can confirm the tests catches this bug though. Merging this for now!

**Pull request merged**
