### PR TITLE
Fixing type to align with Vite configuration

### PR DESCRIPTION
**Pull request by gkatsanos**
## Changes

- What does this change? Fixes: https://github.com/withastro/astro/issues/8192 
- Be short and concise. Bullet points can help!
- Before/after screenshots can help as well.
- Don't forget a changeset! `pnpm exec changeset`

### CODE REVIEW

**Review by bluwy — CHANGES_REQUESTED** [review]
This doesn't fix the issue yet. We need to update the schema to allow passing strings:

https://github.com/withastro/astro/blob/a571a1ac07fad4a898158b04594e03ad0c1de83b/packages/astro/src/core/config/schema.ts#L144

And make sure we're also using the string:

https://github.com/withastro/astro/blob/a571a1ac07fad4a898158b04594e03ad0c1de83b/packages/astro/src/core/dev/container.ts#L59-L64

And also that the CLI accepts it:

https://github.com/withastro/astro/blob/a571a1ac07fad4a898158b04594e03ad0c1de83b/packages/astro/src/cli/flags.ts#L24

**Comment by gkatsanos** [comment]
Quick question, @bluwy , if this is a core vite feature, why do we need to override / rewrite with our own logic? (I'm sorry if this is a dumb question, just figuring things out)

**Comment by bluwy** [comment]
I don't have the full context, but it's likely because we want to present the dev server as Astro's dev server, and not Vite's. Vite would be an implementation detail. So common server options like host and port are top-level in the Astro config, but if you want to tap into Vite specific server options, like setting up proxies, then you'd have to use the `vite.server` config.

**Comment by gkatsanos** [comment]
I see. I'm not sure I have the experience in terms of working with the core of the FW to do all the changes required..

**Comment by matthewp** [comment]
Is this ready for another review? Or still being worked on?

**Comment by gkatsanos** [comment]
@matthewp I don't think I can go through with this, some parts of the codebase are a little blackbox to me.

**Comment by bluwy** [comment]
I'll close this for now to clean up the PRs and track the progress in the issue. Thanks for the PR to kick off the discussion

**Pull request closed without merging**
