### PR TITLE
update node integration README with Fastify code example

### PR DESCRIPTION
**Pull request by edv-ns**
## Changes

Adding astrojs/node + Fastify minimal code example to the docs, with the same functionality as express example has.

## Docs

Will be automatically generated inside docs repo.

### CODE REVIEW

**Comment by edv-ns** [comment]
Ready to review.

**Comment by matthewp** [comment]
Didn't Fastify remove `.use()`? https://github.com/fastify/fastify/pull/3506

**Review by natemoo-re — APPROVED** [review]
LGTM but also cc'ing @matthewp who built [`astro-fastify`](https://github.com/matthewp/astro-fastify)

**Comment by edv-ns** [comment]
@matthewp yes, Fastify removed `.use()` and do not support middleware, but there are two packages `@fastify/express` and `@fastify/middie` which gives the Express-like syntax to use node as middleware.

ref: https://www.fastify.io/docs/latest/Reference/Middleware/

I have chose `@fastify/middie` because of mentioned improved performance, while `@fastify/express` is not meant to be used for long-term (see readme: https://github.com/fastify/fastify-express) as it is meant for transition period.

**Review by sarah11918 — APPROVED** [review]
The README updates are fine by docs!

**Comment by matthewp** [comment]
@edv-ns Got it, thanks that helps a lot.

**Pull request merged**
