### PR TITLE
Fix processing same image multiple times

### LINKED ISSUE #6489: `astro build` shows duplicate lines in the log
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows and Linux

### Describe the Bug

I just build [my site](https://github.com/torn4dom4n/torn4dom4n.github.io) with Astro v2.1.2 and I see [this log](https://github.com/torn4dom4n/torn4dom4n.github.io/actions/runs/4377119434/jobs/7660172919):

```log
 generating optimized images 
  ▶ /_astro/me.ff60ed41_1g8my4.jpg (before: 51kb, after: 13kb) (+666ms)
  ▶ /_astro/logo.759d98d5_Z1SJ5Wi.png (before: 3kb, after: 1kb) (+152ms)
  ▶ /_astro/logo.759d98d5_Z1SJ5Wi.png (before: 3kb, after: 1kb) (+112ms)
```

It shows 2 lines `/_astro/logo.759d98d5_Z1SJ5Wi.png (before: 3kb, after: 1kb) (+152ms)` at the end.
BTW, in the `_astro` folder, I see both optimized images and unoptimized images. I think we just need optimized images because it'll reduce the project's size.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/torn4dom4n/torn4dom4n.github.io

### Participation

- [ ] I am willing to submit a pull request for this issue.

### LINKED ISSUE #6564: Image asset referenced from one Markdown file in a collection is redundantly optimized many times
### What version of `astro` are you using?

2.1.3

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

[This project](https://stackblitz.com/edit/github-w4ctjf-kmbr3n) has a collection with 10 empty Markdown files and one Markdown file referencing a single image asset (using experimental assets). If I run `astro build`, it optimizes this single image 38 times:

```
❯ astro build
12:10:56 AM [content] Types generated 2.35s
12:10:56 AM [build] output target: static
12:10:56 AM [build] Collecting build info...
12:10:56 AM [build] Completed in 2.41s.
12:10:57 AM [build] Building static entrypoints...
12:11:02 AM [build] Completed in 5.34s.

 generating static routes 
▶ src/pages/index.astro
  └─ /index.html (+74ms)
▶ src/pages/blog/[slug].astro
  ├─ /blog/empty-0/index.html (+50ms)
  ├─ /blog/empty-1/index.html (+77ms)
  ├─ /blog/empty-2/index.html (+105ms)
  ├─ /blog/empty-3/index.html (+133ms)
  ├─ /blog/empty-4/index.html (+165ms)
  ├─ /blog/empty-5/index.html (+190ms)
  ├─ /blog/empty-6/index.html (+217ms)
  ├─ /blog/empty-7/index.html (+248ms)
  ├─ /blog/empty-8/index.html (+273ms)
  ├─ /blog/empty-9/index.html (+293ms)
  └─ /blog/with-image/index.html (+317ms)

 generating optimized images 
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+8.74s)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+212ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+196ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+247ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+173ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+166ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+151ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+165ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+221ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+177ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+139ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+130ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+154ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+193ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+170ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+200ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+147ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+181ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+252ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+465ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+241ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+202ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+165ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+175ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+171ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+235ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+254ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+221ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+263ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+219ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+223ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+220ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+189ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+360ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+162ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+148ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+152ms)
  ▶ /_astro/astro-logo-dark.af92bf69_Zp0Xz8.png (before: 10kb, after: 3kb) (+186ms)
Completed in 17.08s.

12:11:19 AM [build] 12 page(s) built in 24.94s
12:11:19 AM [build] Complete!

~/projects/github-w4ctjf-kmbr3n 37s
❯ 
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-w4ctjf-kmbr3n

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ken0x0a**
## Changes

- add a check before generating image with asset service to prevent generating same image multiple time

Fix #6564, close #6489

## Testing

I didn't test only this change.
I'm using astro with few more patches and just extracted only this part, but this changes are very simple and don't even need to verify, I think.

## Docs

No changes for usage

### CODE REVIEW

**Comment by Princesseuh** [comment]
Hmm, this is fine, but I wonder if there isn't an issue higher in the chain that we should fix before doing this fix that would hide other issues.

For instance, in the Markdown one, there's 9 empty Markdown files, and yet a bunch of images are being added. Maybe there's some sort of global state not being reseted correctly.

**Comment by ken0x0a** [comment]
Hmm, maybe.

It's also possible to avoid adding duplicated value for Map by iterate for keys of the map and check objects equality by value of object. I mean something like this https://lodash.com/docs/#isEqual, not `===`, as `transform` objects are created each time.

**Comment by andersk** [comment]
The real underlying bug here is an unnecessarily nested `for` loop. Here’s a fix:

- #6596

**Comment by Princesseuh** [comment]
Thank you for contributing! As this logic was completely removed in https://github.com/withastro/astro/pull/6604, this PR is no longer relevant, so I'll be closing this. Hopefully, the new logic should fix this issue as well!

**Comment by ken0x0a** [comment]
@Princesseuh Thank you for your fix, a problem I couldn't figure out the cause had been fixed.
But it seems this also necessary.
This reduces my build time from `53.62s` to `15.08s` and reduces lots of duplicated command to generate same image.
It's definitely because I'm using patch to resize image using custom assets service to create bunch of image for different sizes to use `img`'s `srcset` attribute though, this has huge impact for me.

My issue due to this line.
https://github.com/withastro/astro/blob/cc90d72197e1139195e9545105b9a1d339f38e1b/packages/astro/src/assets/vite-plugin-assets.ts#L176
Using an `object` as `Map`'s key, and this `object` is created each time this function is called.

So, I guess this issues not only me, but also users who using `import someImg from '../assets/myimg.jpg'` from multiple astro file and more (see implementation of `getImage`)

https://github.com/withastro/astro/blob/1e7d6af41219644516757a1bf21d36cdb8795f50/packages/astro/src/assets/internal.ts#L52

Without this PR's change, every time `getImage` called, new image generation occurs, even if users requested same image.

So, I appreciate if you reopen this or fix this issue in more performant way :D

**Pull request closed without merging**
