### PR TITLE
fix: add property name to rss errors

### PR DESCRIPTION
**Pull request by y-nk**
## Changes

- What does this change?
Add more information to zod error report

- Be short and concise. Bullet points can help!
When generating a rss feed with the rss function, if one prop of an item is missing, the only feedback will be `Invalid input` without much of _where_ is the invalid input.

## Testing

I've added a prop on a string based on zod's doc here: https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md#zodissue

Not sure if this must be tested.

## Docs

No doc as well, it's rather enhanced error handling.

### CODE REVIEW

**Review by natemoo-re — APPROVED** [review]
This LGTM but I'd love for @bholmesdev to take a look as well

**Review by bholmesdev — APPROVED** [review]
Ah, valigreat fix! Thanks for this 👍

**Comment by bholmesdev** [comment]
@y-nk Should be good to merge once you add a changeset. Run `pnpm changeset` at the repository root and choose a patch release.

**Comment by y-nk** [comment]
thanks a lot @natemoo-re 🙏🙏🙏

**Pull request merged**
