### PR TITLE
Highlight a specific line in code block

### PR DESCRIPTION
**Pull request by toyamarinyon**
## Changes

- Astro can syntax highlighting code block with Prism or Shiki but can't highlighting a specific line.
- It's resolve to add markdown spec that specify how to highlighting line and implement this, because Prism and Shiki provide function to highlighting a specific line. 
- I've tried to specify highlighted line ranges within the language meta string (leave a space after the language) with reference to Docusaurus.
[Highlighting with metadata string/Docusaurus](https://docusaurus.io/docs/markdown-features/code-blocks#highlighting-with-metadata-string)
- Add an example of highlighting a specific line

After this PR is merged, we can highlight a specific line in code block like that:
```md
```jsx {1,4-6,11}
import React from 'react';

function MyComponent(props) {
  if (props.isBar) {
    return <div>Bar</div>;
  }

  return <div>Foo</div>;
}

export default MyComponent;
```

It will be displayed like that:

CleanShot 2022-02-16 at 17 52 06@2x

I build `examples/with-markdown-shiki` and captured it on browser.

## Testing 

- yarn test:match "highlight"

## Docs

https://github.com/withastro/astro/pull/2587

### CODE REVIEW

**Comment by FredKSchott** [comment]
This is a bit outside of our focus and scope of what we can maintain inside of Astro core at the moment. Have you considered adding this feature to Shiki directly? I would recommend merging this into Shiki itself, or creating your own `<Code />` component that could support this and then using that component in your markdown.

```
<MyCodeComponent highlight="1,4-6,11" code={someCode} />
```

**Comment by RomanMunar** [comment]
There's already a [pr merged](https://github.com/shikijs/shiki/pull/259) on shiki that adds a specific css-class to a line. Not sure how to integrate it to astro though. Please take a look It might be a small code adjustment.

**Comment by youssefm** [comment]
@FredKSchott I would love to see this feature now that shiki has first class support for `highlightedLines`. Is there a feature request tracking this?

**Comment by toyamarinyon** [comment]
Now, Astro provides Integration API[^1]. If you can use it, it can highlight lines using meta strings, but it is a bit too complex.

I created an article showing how to highlight lines more easily using Rehype Pretty Formatter[^2].

I've also made it available on stackblitz.

If someone is interested so you can try it out.
https://sat0shi.dev/posts/highlight-line-on-codeblock-with-astro/

[^1]: https://docs.astro.build/en/reference/integrations-reference/
[^2]: https://rehype-pretty-code.netlify.app/

**Comment by youssefm** [comment]
Thanks @toyamarinyon, I tried it out and it works really well!

Cheers for the suggestion

**Comment by youssefm** [comment]
It would be cool if Astro just used:

https://rehype-pretty-code.netlify.app/

by default out of the box. It looks like a better version of the Shiki plugin that Astro maintains.

**Comment by RomanMunar** [comment]
Thanks bro @toyamarinyon

**Pull request closed without merging**
