### PR TITLE
Adding StackUp Digital to the list of sponsors

### PR DESCRIPTION
**Pull request by Chrissdroid**
## Changes

- Adds 2 new svg for light and dark mode
- Modifies REAME.md to include new gold sponsor to the list

## Testing

Testing done on forked repo with light and dark mode

## Docs

No doc required

### CODE REVIEW

**Comment by FredKSchott** [comment]
Amazing! Unfortunately I see a missing image when I view this file: https://github.com/withastro/astro/blob/beb95c0ecb52627a32d29019521690614d602cca/packages/astro/README.md

Separately, I'll go ahead and get this added to our homepage

**Comment by Chrissdroid** [comment]
Yeah, sadly it's because the image link doesn't yet exist as this not in the repo yet

**Comment by Chrissdroid** [comment]
Oh yeah I totally forgot about the website homepage, I'll do that !

**Comment by FredKSchott** [comment]
> Yeah, sadly it's because the image link doesn't yet exist as this is not in the repo yet

Oh right, of course! Thanks for confirming

> Oh yeah I totally forgot about the website homepage, I'll do that if you want !

That would be great, thank you!

**Comment by Chrissdroid** [comment]
Pull Request Done
https://github.com/withastro/astro.build/pull/24

**Pull request merged**
