### PR TITLE
fix: lint failing on astro and some integrations

### PR DESCRIPTION
**Pull request by userquin**
The build is failing, this PR just fix the errors.

EDIT: review this https://github.com/withastro/astro/pull/3794/files#diff-3974ff1a07864eae3cb91ceefef360fbc39db051f8036ee2504b9be00764e0ccR734

### CODE REVIEW

**Comment by userquin** [comment]
```shell
pnpm run lint

> root@0.0.0 lint F:\work\projects\quini\GitHub\antfu\astro-pwa-integration
> eslint .


F:\work\projects\quini\GitHub\antfu\astro-pwa-integration\packages\astro\src\cli\index.ts
  201:11  error  'err' is already declared in the upper scope on line 178 column 42  @typescript-eslint/no-shadow   

F:\work\projects\quini\GitHub\antfu\astro-pwa-integration\packages\astro\src\runtime\server\index.ts
  734:7  error  'iterable' is already declared in the upper scope on line 710 column 6  @typescript-eslint/no-shadow

F:\work\projects\quini\GitHub\antfu\astro-pwa-integration\packages\integrations\image\src\index.ts
  150:7  warning  Unexpected console statement  no-console

F:\work\projects\quini\GitHub\antfu\astro-pwa-integration\packages\integrations\image\src\vite-plugin-astro-image.ts
  34:18  error  'config' is already declared in the upper scope on line 10 column 30  @typescript-eslint/no-shadow  

F:\work\projects\quini\GitHub\antfu\astro-pwa-integration\packages\integrations\sitemap\src\index.ts
  74:7  warning  Unexpected console statement  no-console

✖ 5 problems (3 errors, 2 warnings)

 ELIFECYCLE  Command failed with exit code 1.

F:\work\projects\quini\GitHub\antfu\astro-pwa-integration>pnpm run lint

> root@0.0.0 lint F:\work\projects\quini\GitHub\antfu\astro-pwa-integration
> eslint .
```

**Comment by FredKSchott** [comment]
This PR is failing build, and our `lint` CI role is passing on `main`. Maybe there's an issue with your local setup? See: https://github.com/withastro/astro/blob/main/CONTRIBUTING.md

**Comment by FredKSchott** [comment]
Ah you're right, I see lint failing as well. Trying to reopen the PR but I no longer can because the branch was deleted. Feel free to re-submit if you can get CI passing!

**Review by natemoo-re — APPROVED** [review]
LGTM!

**Pull request merged**
