### PR TITLE
Render Custom Element Tag

### PR DESCRIPTION
**Pull request by jonathantneal**
## Changes

- Renders the tag name of a Custom Element (after any renderers).
- Prevents a tag made from an `HTMLElement` from throwing.
- ~Adds a script to register the constructor.~

**Before**:
```astro
<!-- src/components/Button.astro -->
<script hoist>
class Button extends HTMLElement {}
customElements.define('h-button', Button)
</script>
<h-button><slot /></h-button>
```
```astro
---
// src/pages/index.astro
import Button from '../components/Button.astro'
---
<Button>Button</Button>
```

**After**:
```js
// src/components/Button.js
export default class Button extends HTMLElement {}
customElements.define('h-button', Button)
```
```astro
---
// src/pages/index.astro
import Button from '../components/Button.js'
---
<Button>Button</Button>
```

## Testing

testing tbd, if the pr is conceptually acceptable

## Docs

docs tbd

### CODE REVIEW

**Review by natemoo-re — COMMENTED** [review]
I’m in favor of this! You’re incrementally making Astro the best option for using web components. ☺️ 

Would love to hear what everyone else think!

**Comment by tony-sull** [comment]
I'm a big fan of this one as well!

I've actually tried a few different times to use web components in Astro, and while there are ways it can be done it'd be excellent to see web components really pulled in to feel more like a first-party option

**Comment by matthewp** [comment]
I'm conflicted on this idea. I would summarize my feelings like this:

__pro__

* This looks like a convenient way to add interactivity.

__con__

* The before is not bad either, and it can be used to enhance regular elements in addition to web components.
* Special-casing one type of component usage adds maintenance burden. In the long run I feel that this will hurt, not help, web components because now we have to justify the added cost of fixing bugs. Whereas when used with the regular renderer API there isn't an additional cost.
* This is for one specific use-case, using web components to enhance HTML. Web components can also be used to generate HTML and many people use them in this way. This PR promotes the former use-case which implicitly demotes the latter.

__unsure__

* I'd be curious to know how many in-the-wild web components can be loaded and used this way. Would it be possible to find out what the top 100 web components are on npm and see if they will work using this PR?
  * Without this knowledge I'd be concerned that people will use packages they find on npm and then file issues because they don't work in Astro using this technique.

**Comment by jonathantneal** [comment]
> This is for one specific use-case, using web components to enhance HTML. Web components can also be used to generate HTML and many people use them in this way. This PR promotes the former use-case which implicitly demotes the latter.

What would you like to see changed? I am glad this promotes _a_ use-case, and I agree that improving web component usage anywhere will promote that usage more than other usage, until it’s improved everywhere. Support is too far behind. This PR represents one incremental improvement.

> In the long run I feel that this will hurt, not help, web components because now we have to justify the added cost of fixing bugs. Whereas when used with the regular renderer API there isn't an additional cost.

Hear me out. We already maintain all of the renderer APIs. This will be the first time we don’t also have to manage a framework library. Also, this change is not vulnerable to to the "donut" issues we have experienced in all other renderers. And by allowing users to work with Web Components, when we _will_ learn about more bugs, these bugs will likely be issues that we have already introduced. Examples include the special casing of certain attribute booleans and the name-squatting of `<slot>`; which are issues we have and could have caught much earlier had we embraced Web Components more seriously.

I’m also very open to changing this implementation, if there is a suggestion. This PR attempts to make the smallest possible change that provides real improvement.

**Comment by matthewp** [comment]
> What would you want to see changed to make this PR, or a PR like this acceptable? 

- Opt-in via the `client:` directives.
- Some data on compatibility; ie run this against a set of the top 100 ranked packages with "web component" in the tag on npm. This will tell if the polyfills cover enough to load common components users are likely to use.

**Comment by matthewp** [comment]
@jonathantneal I think what you are working on here is a real use-case that needs to be solved better. I'm in support of that.

I think the approach taken here, and in some past proposals, of basing this on the renderer API is the wrong approach though. The renderer API was intended to solve a very specific use-case; framework components that generate HTML. It is *very* common for people to write components in React, etc. that only generate HTML and have no interactivity. But some times they do, and that's why we have the `client:` directives, to allow opting-in to interactivity when its truly needed.

What you are working on is a type of component that *always* needs interactivity. I think that's fine, but probably needs a new kind of plugin API to support it. I'm not exactly sure what that is.

I would challenge you to think beyond the client web components that are interested in and think about other type of client JS that this could be useful for. For example, adding analytics tags. Or YouTube embeds. Or chat widgets. These are all types of client JS that is a little different from our renderer API components in that client JS is the entire point. What can we do to improve DX of these types of use-cases?

Currently we have `<script hoist>` as the solution, but that is a little low-level. Here's an idea that might be a starting point; is this a place where assertions could be of help?

```js
import '../scripts/google-analytics.js' asset { client: 'load' };
```

And then you could maybe use web components in a similar way?

```js
---
import HButton '../components/h-button.js' assert { client: 'idle' };
---

<HButton>Content</HButton>
```

**Comment by jonathantneal** [comment]
Separately, I like the import assertions idea. However, for web components, it would still need the solution provided by this PR, which is to render `HTMLElement` as a tag.

**Comment by jonathantneal** [comment]
I’ve removed the automatic insertion of the `<script>`, pending further discussion.

**Comment by matthewp** [comment]
I think I'm ok with this portion. I will note that I'm still concerned about promoting people to import browser code into Astro as it is possible (likely?) that a lot of code is going to break and that will result in issues being filed. But we can back out the feature later if we run into that problem a lot.

**Comment by jonathantneal** [comment]
🎉

**Pull request merged**
