### PR TITLE
Fixes rendering of HTML comments inside markdown code blocks

### LINKED ISSUE #3460: 🐛 BUG: Braces are displayed when using HTML comments in Markdown code fences.
### What version of `astro` are you using?

1.0.0-beta.35

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When you see the following markdown code fence:

````md
```astro
---
// Component Script (JavaScript)
---
<!-- Component Template (HTML + JS Expressions) -->
```
````

Unwanted curly braces are displayed, as shown below:

```astro
---
// Component Script (JavaScript)
---
{/*<!-- Component Template (HTML + JS Expressions) -->*/}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-j2bchk?file=src%2Fpages%2Fen%2Fintroduction.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by tony-sull**
Closes #3460 

## Changes

Fixes a bug where HTML comments weren't being rendered properly inside markdown code blocks

## Testing

Added tests to the `markdown/remark` and `vite-plugin-markdown` packages to test the remark plugin and markdown page rendering

## Docs

None, bug fix only

### CODE REVIEW

**Review by natemoo-re — APPROVED** [review]
LGTM! Thanks for the fix.

**Comment by natemoo-re** [comment]
Going to cc @hippotastic as I know they were working on a lower-level fix to this issue.

**Comment by hippotastic** [comment]
I think that's a good quick fix for this particular side effect of our current way to allow HTML comments. LGTM!

The fix I'm working on has a far greater scope and will improve interleaving of Markdown and HTML/JSX elements as well as JS expressions in general. There are plenty of scenarios that currently throw parser errors (also with HTML comments), which will become valid afterwards. But this takes some time, and having a quick fix for a single common scenario like this one in the meanwhile is great in my opinion!

**Comment by tony-sull** [comment]
Thanks for the reviews!  Very excited to see what you're cooking up, @hippotastic!

**Pull request merged**
