### PR TITLE
Add `devOptions.tailwindConfig`  for Tailwind setup

### PR DESCRIPTION
**Pull request by flaviocopes**
(Docs site) I had an issue setting up Tailwind, I missed this piece I found explained on https://daily-dev-tips.com/posts/how-to-use-tailwind-css-in-astro/

### CODE REVIEW

**Comment by drwpow** [comment]
Ah that blog post is outdated! That used to be necessary in previous versions, but isn’t any longer. Our docs are the most current instructions on how to use Tailwind: https://docs.astro.build/guides/styling/#-tailwind.

If you experience any issues on the latest version, though, please feel free to suggest other doc edits!

**Comment by flaviocopes** [comment]
Ah sorry! It didn't work for me until I added that line to `astro.config.mjs`, not sure why!

**Comment by drwpow** [comment]
Hm. What version are you on? That is required before `0.21.0`, but won’t be going forward. The change is described here: https://docs.astro.build/migration/0.21.0/#tailwind-css. I know it can be confusing especially since this new version hadn’t been out that long, but we also want to avoid having too much legacy config in our docs, too. It’s hard either way!

**Comment by flaviocopes** [comment]
Sorry @drwpow I was dumb and did not update my site to latest, had a few weeks old site and didn't think about that. 
Things move fast! :D  
It works now without this change, sorry if I made you lose time!

**Comment by drwpow** [comment]
Not dumb at all! It’s confusing when documentation changes! Really appreciate you taking _your_ time to improve the docs! We hope you’ll do so in the future 🙂. No worries—no time lost at all!

**Pull request closed without merging**
