### PR TITLE
chore: removed syntax files

### PR DESCRIPTION
**Pull request by JuanM04**
## Changes

It removes the old syntax files. Shiki used to reference these files to update its grammar, but now it points to `withastro/language-tools` (https://github.com/shikijs/shiki/pull/293)

### CODE REVIEW

**Review by FredKSchott — CHANGES_REQUESTED** [review]
Linguist needs to be updated for GitHub syntax highlighting in code blocks. Mind making a PR similar to https://github.com/github/linguist/pull/5658 to update? Then once merged, we can merge this one!

**Comment by JuanM04** [comment]
@FredKSchott turns out, the new definitions throw errors with linguist. I opened an issue: withastro/language-tools#165

**Comment by jonathantneal** [comment]
Just updating that this is held up due to linguist needing tmLanguages not to use look-behinds without a fixed length.

**Comment by natemoo-re** [comment]
Blocked by https://github.com/github/linguist/pull/5819. 

Also reached out to CodeSandbox and StackBlitz to make sure they redirect their stuff internally.

**Comment by JuanM04** [comment]
https://github.com/github/linguist/pull/5819 has been merged! Is there anything else blocking this PR?

**Comment by FredKSchott** [comment]
Nice! Nope, don't think so. Thanks for making that happen @JuanM04 !

**Comment by FredKSchott** [comment]
just to be 100% safe: @natemoo-re might want to ping codesandbox, stackblitz, etc. to confirm

**Pull request merged**
