### PR TITLE
Mithril

### PR DESCRIPTION
**Pull request by pep108**
## Changes

- Add integration to render Mithril components

## Testing

- An example was created in example/framework-mithril that duplicates the React example and was smoke tested

## Docs

/cc @withastro/maintainers-docs for feedback!

- A README.md was included in integrations/mithril with documentation

### CODE REVIEW

**Comment by matthewp** [comment]
Hey, thanks for building this, it looks really cool! However, we do not want to take on new projects from non-maintainers as the core team will be responsible for its maintenance. We do encourage you to publish this as its own package, though, where it will be visible on https://astro.build/integrations/

**Comment by pep108** [comment]
@matthewp thanks for the feedback. I'll close this pull request. I also opened a pull request yesterday with an integration for WindiCSS. Do you suggest I do the same and publish it as it's own package?

**Comment by matthewp** [comment]
@pep108 Yep, thanks!

**Comment by pep108** [comment]
Hey @matthewp, I was curious how the Astro docs pick up icons for the integrations. Would you be able to point me in the right direction. Thanks!

**Comment by delucis** [comment]
Hi @pep108! Out main docs on getting an integration into our catalogue can be found here: https://docs.astro.build/en/reference/publish-to-npm/#integrations-library

Icons on https://astro.build/integrations/ need to be submitted manually (we generate a random one by default). You can do that by submitting an issue to the astro.build repo: https://github.com/withastro/astro.build/issues/new/choose

**Pull request closed without merging**
